### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by moose999** [Rudloff/alltube#100]
Hi,

I am using Ubuntu 16.04, and alltube 0.7.2-beta (from release). I am using apache 2.4.18 and PHP 7.0.15

When I try and download any Youtube video, I get 

`ERROR: Signature extraction failed: Traceback (most recent call last): File "/var/www/html/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1011, in _decrypt_signature video_id, player_url, s File "/var/www/html/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 925, in _extract_signature_function errnote='Download of %s failed' % player_url) File "/var/www/html/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 519, in _download_webpage res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query) File "/var/www/html/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query) File "/var/www/html/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 406, in _request_webpage return self._downloader.urlopen(url_or_request) File "/var/www/html/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen return self._opener.open(req, timeout=self._socket_timeout) File "/usr/lib/python2.7/urllib2.py", line 421, in open protocol = req.get_type() File "/usr/lib/python2.7/urllib2.py", line 283, in get_type raise ValueError, "unknown url type: %s" % self.__original ValueError: unknown url type: /yts/jsbin/player-en_US-vflRjgXJi/base.js (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflRjgXJi/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. `

Other videos seem fine so far.

I tried to update youtube-dl in /vendor/rg3/ with:

sudo apt-get install python-setuptools
sudo easy_install pip
sudo pip install --upgrade youtube-dl

and I got:
`Successfully installed youtube-dl-2017.4.2`
but I do not know if this has updated the version used by alltube, and still no luck downloading.

Any ideas?
Thanks!!
Justin

**Comment by Rudloff** [comment]
Do you have an example of a video that doesn't work? I can't reproduce your issue with 0.7.2-beta.

Also these commands don't update the youtube-dl in `vendor/`, they update the global youtube-dl.
You can tell Alltube to use the global youtube-dl by adding something like this in `config.yml`:
```yaml
youtubedl: /usr/local/bin/youtube-dl
```

**Comment by moose999** [comment]
Hi,

I trashed my VM (VMWare) and started again, and still have the issue with all youtube videos - even the RickRoll [https://www.youtube.com/watch?v=dQw4w9WgXcQ](url)

This is how I installed my system:

default ubuntu 16.04
sudo apt-get install openssh-server
sudo apt-get install unzip apache2 php libapache2-mod-php php-mcrypt python libav-tools rtmpdump curl php7.0-intl php7.0-mbstring php7.0-curl
sudo a2enmod rewrite
cd /var/www/html
sudo wget https://github.com/Rudloff/alltube/releases/download/0.7.2-beta/alltube-0.7.2-beta.zip
sudo unzip ./alltube-0.7.2-beta.zip
sudo chmod 777 templates_c/
sudo nano /etc/apache2/apache2.conf
•	Find:
•	
•	<Directory /var/www/>
•	        Options Indexes FollowSymLinks
•	        AllowOverride None
•	        Require all granted
•	<//Directory>
•	
•	and change to:
•	
•	<Directory /var/www/>
•	        Options Indexes FollowSymLinks
•	        AllowOverride FileInfo
•	        Require all granted
•	<//Directory>
sudo systemctl restart apache2

The error message suggests to me that the URL was not passed (Download of %s failed' % player_url). Is that a possibility? 

Thanks,
Justin

**Comment by Rudloff** [comment]
I can indeed reproduce the issue with this video. It happens because the version of youtube-dl packaged with this release is outdated.
I published a new beta release that should fix it: https://github.com/Rudloff/alltube/releases/tag/0.7.2-beta2

**Comment by moose999** [comment]
That got it, thanks!
