### ISSUE TITLE
Auto remux DASH video/audio

### ISSUE THREAD

**Issue by guysmiley3** [Rudloff/alltube#103]
Currently more and more youtube and others are topping out at 720p as the "best" and using DASH for 1080p+ forcing you to download twice and remux yourself

Instead of relying on "best" tag either let the user select the video/audio they want and remux on the fly for them similar to running -f with two IDs

Note I did try passing IDs via the config.yml but it didn't really like that and I don't consider this a bug... more like option in future

**Comment by Rudloff** [comment]
We can probably remux on the fly by using pipes:
`avconv -y -i <(curl videourl) -i <(curl audiourl) -c copy -map 0:v:0 -map 1:a:0 'file:remux.mkv'`

But when I try that with a Youtube video, I get a broken result (audio is not correctly synced to video).

**Comment by Rudloff** [comment]
@guysmiley3 I added an experimental feature that allows you to download `bestvideo+bestaudio`.
If you want to test it, you can use the develop branch and add `remux: true` to your `config.yml` file.

**Comment by guysmiley3** [comment]
Works well!

Only issue I had was mpc refused to play the remux with video+audio... video or audio alone was fine
VLC was a skipping/non seeking mess but VLC usually has issues I find
Potplayer worked fine
