### ISSUE TITLE
Stray </div> tag in playlist download template

### ISSUE THREAD

**Issue by stubbers** [Rudloff/alltube#107]
In the develop branch the playlist feature is working however the generated HTML has an extra DIV tag above the footer tag (there are 3, I believe there should be 2).

Problem does not exist for single videos.

The cause appears to be that although the itemscope div is not present in the playlist template the associated closing tag still is.

Produced by going to a normal video link:

```
<body class="video">

<div class="wrapper">
<div itemscope itemtype="http://schema.org/VideoObject">
<div class="main">
<h1 class="logobis">
```

Produced by going to a playlist:

```
<body class="video">

<div class="wrapper">
<div class="main">
<h1 class="logobis">
```

Closing tags are identical even though there are only 2 divs to close for playlists.

```
</div>
</div>
</div>
<footer>
```

**Comment by Rudloff** [comment]
Thanks for noticing this!

**Comment by stubbers** [comment]
No problems. Playing with putting it in an automation workflow using node-red and its parser doesn't like the lack of validation. Thanks for your hard work @Rudloff , I'm just using it!
