### ISSUE TITLE
[FR] - Support bulk/playlist download

### ISSUE THREAD

**Issue by untotren** [Rudloff/alltube#108]
when I put  playlist right now, it generates many links.  It would be nice to bulk download, perhaps even as a .zip.

**Comment by Rudloff** [comment]
I'm currently trying different approaches for this. This is not so far from options we already provide (MP3 conversion, remux) but it can potentially use a lot of resources so we probably won't enable it by default.

JavaScript becomes a nightmare with playlists that have a lot of videos so I'm looking for a server side solution.
We might use a library like [ArchiveStream-php](https://github.com/barracudanetworks/ArchiveStream-php) to stream tar data to the browser.

**Comment by Rudloff** [comment]
I tried two different libraries that could do this but they both have issues that are blocking me:
* https://github.com/barracudanetworks/ArchiveStream-php/issues/42
* https://github.com/Grandt/PHPZip/issues/45

**Comment by Rudloff** [comment]
I added experimental support for this on the develop branch (https://github.com/Rudloff/alltube/commit/d3c68257ac0040e225973fa3df6e9740964bb5a3).
You need to have `stream: true` in your `config.yml` file for it to work.
I have only tested it with Youtube playlists.

**Comment by Rudloff** [comment]
Closing as the basic functionnality is there.
Please feel free to open new issues for bugs or enhancements.

**Comment by untotren** [comment]
@Rudloff Thank you sorry I am travelling for work I will try it out ASAP!!
