### ISSUE TITLE
Audio-only download creates a 0-byte file

### ISSUE THREAD

**Issue by dp87** [Rudloff/alltube#11]
Perhaps this is just a documentation issue, but entering a YouTube (or any other source for that matter) URL and selecting the Audio only (MP3) option results in a 0-byte MP3 file being created.

Everything else works (even download in m4a). I have installed `avconv` and `rtmpdump`. Is this a bug or is there some other missing dependency? In this case, the readme should probably be updated.

**Comment by Rudloff** [comment]
This might be caused by this bug: https://github.com/Rudloff/alltube/commit/41ef2fc836cccbfc75dfb1841453e2bcabb68dea
Can you try again with the latest master?

**Comment by dp87** [comment]
Unfortunately I am still experiencing the same behavior. I even tried restarting apache and clearing the browser cache to make sure I was using the updated file.

**Comment by Rudloff** [comment]
Are you using the latest version of youtube-dl?
Do you get any errors in Apache logs?

**Comment by dp87** [comment]
Yes, youtube-dl is updated. This shouldn't be the issue since mp3 conversion works fine using the youtube-dl CLI.

However, the apache error log shows this entry every time I try to use the MP3 option:

`[Tue Apr 07 20:26:13 2015] [error] [client 192.168.0.7] File does not exist: /var/www/alltube/dist, referer: http://webserver/alltube/`

And yes, the `dist` folder actually doesn't exist, but even creating it results in the same error.

**Comment by dp87** [comment]
Ha! I knew it. It was a codec issue. Turns out I was missing a warning when running youtube-dl: there was a missing codec.

`sudo apt-get install libavcodec-extra-53` solved the issue :)

**Comment by Rudloff** [comment]
Glad you could figure it out :)
I updated the README: https://github.com/Rudloff/alltube/commit/b6b48e8ceae266e0bc5533a96546c6b83650df52
