### ISSUE TITLE
Missing instructions on how to installl on Xenial 16.04

### ISSUE THREAD

**Issue by elico** [Rudloff/alltube#114]
I have found this tutorial:
http://techblog.danielpellarini.com/sysadmin/install-alltube-the-gui-for-youtube-dl-on-apache/

But it was written for old versions.
Can anyone guide me on the installation steps on Xenial or Debian 8 or CentOS 7 ?

**Comment by Rudloff** [comment]
Hello,
Most of what is needed is in the [README](https://github.com/Rudloff/alltube/blob/master/README.md) or the [FAQ](https://github.com/Rudloff/alltube/blob/master/FAQ.md).
If you are missing some info, tell me and I will add it.

(Of course, if someone wants to write a tutorial for Ubuntu, they are more than welcome.)

**Comment by elico** [comment]
@Rudloff I managed to install it using the zip file but not using the git insructions.
I will open another isssue about something In the code I want to find and need some help.
