### ISSUE TITLE
[Help wanted] New translations

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/alltube#115]
I am looking for people interested in translating Alltube into new languages. Please add a comment if you can help 😊

**Comment by cgomezmendez** [comment]
I can help with Spanish translation.

**Comment by Rudloff** [comment]
@cgomezmendez Great! I have created a translation project [here](https://poeditor.com/join/project/GJmE0wN7Xw) so you can easily add translations.
Please tell me if you need any help.

**Comment by Rudloff** [comment]
@cgomezmendez Did you have a chance to look at the translation?

**Comment by cgomezmendez** [comment]
I haven't check, been a little busy, but will look at it.

**Comment by Rudloff** [comment]
@tony199555 We added some new strings since your latest translation. You can translate them [here](https://poeditor.com/join/project/GJmE0wN7Xw) if you want (or do a PR if you prefer).

**Comment by tony199555** [comment]
I have added myself in the project. Please approve..

2017-08-27 6:39 GMT-07:00 Pierre Rudloff <notifications@github.com>:

**Comment by Rudloff** [comment]
@tony199555 @cgomezmendez I have updated your translations on the develop branch. Thanks for your help!

I will now close this issue and add instructions about how to help translating in `CONTRIBUTING.md`.

**Comment by tony199555** [comment]
LGTM!

**Comment by alialghamdi** [comment]
Already done, uploaded.

**Comment by alialghamdi** [comment]
BTW, where do I set the locale?

**Comment by Rudloff** [comment]
@alialghamdi Thanks! I added your translation to the develop branch: https://github.com/Rudloff/alltube/commit/d9bc681b17b4a2b453b9a61615690b2eaed0c222
If your web server supports the `ar_001` locale, it will become available in the locale menu. And if your browser is in Arabic, it should choose this locale automatically.
