### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by jiangjiangflies** [Rudloff/alltube#116]
Hi,
I setup alltube from the release package but I can't find the config file. When I click download, I get a 404 not found error.
You can try here: http://yt-dl.pw/

**Comment by Rudloff** [comment]
Hello,
Please read the [FAQ](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#i-get-a-404-error-on-every-page-except-the-index).

You need to either:
* Configure URL rewriting on Nginx (see [this example](https://github.com/Rudloff/alltube/blob/master/README.md#nginx)).
* Enable ugly URLs (create a `config/config.yml` file with `uglyUrls: true` in it).

**Comment by Rudloff** [comment]
No answer for more than a week so I'm closing. Please feel free to reopen if you find a bug.

**Comment by jiangjiangflies** [comment]
Thank you! It's great!
