### ISSUE TITLE
Password protected access causes subresources not to load

### ISSUE THREAD

**Issue by TimoVerbrugghe** [Rudloff/alltube#118]
Hi Rudloff,

Using alltube for quite some time now, hosted on my own server. I password protect everything on my apache install, but that seems to be causing problems with alltube, since it tries to access its resources (such as css, favicon, etc...) using embedded credentials in the URL, which has recently been blocked by chrome (see https://www.chromestatus.com/feature/5669008342777856).

This is why I'm getting these errors in the chrome console: 
![capture](https://user-images.githubusercontent.com/7707120/27881673-df10fd62-61c9-11e7-9377-c929b060966b.PNG)

Not really an issue/low-priority for me, I can set up a separate config for the alltube url without password access, but thought that I would mention it. Note that this issues seems unrelated for me to #102.

**Comment by Rudloff** [comment]
Hello,

This is a known issue in Slim (see https://github.com/mathmarques/Smarty-View/issues/6 & https://github.com/slimphp/Slim/issues/2248).

I added a workaround in https://github.com/Rudloff/alltube/commit/480271a45e7d7b8801eb8cc48e39ea3b871d7ef4. Can you please test it and tell if it works for you?

**Comment by TimoVerbrugghe** [comment]
Seems that that did it! All fixed, thanks for the quick response!
