### ISSUE TITLE
PHP Fatal error:  Class 'Locale' not found

### ISSUE THREAD

**Issue by s55ma** [Rudloff/alltube#119]
PHP Fatal error:  Class 'Locale' not found in /disk2/www/youtube/vendor/zonuexe/http-accept-language/src/AcceptLanguage.php on line 112

Ubuntu 14.04.5 LTS \n \l 64 bit
php5-intl package is installed

**Comment by Rudloff** [comment]
Hello,
The Locale class is indeed part of the intl extension. Are you sure this extension is correctly enabled? 

Can you please try this:
* In your Alltube folder, create a `test.php` file with the following content:
```php
<?php
var_dump(extension_loaded('intl'));
```
* Load the URL (e.g. http://example.com/path_to_alltube/test.php) in your browser.
* Copy the displayed result here.

**Comment by s55ma** [comment]
I've reinstalled php5-intl extension and it's working now.
