### ISSUE TITLE
Please allow user to choose audio quality.

### ISSUE THREAD

**Issue by AzimsLives** [Rudloff/alltube#122]
Please show the file size before start downloading & allow user to choose audio quality. Thank you!

**Comment by Rudloff** [comment]
Hello,

The filesize is already displayed in the format list when available.
If you are talking about MP3 conversion, we have no way to guess the filesize before converting.

As for audio quality, I am working on it (see #113).

**Comment by beerisgood** [comment]
With that youtube-dlg command you can download audio in best quality:
`-x --audio-format`

Mostly .ogg is the result

**Comment by Rudloff** [comment]
Thanks but we don't use youtube-dl for conversions, we use avconv/ffmpeg directly (and it is what youtube-dl uses internally anyway).

The solution as already been mentioned in #113 so I'm closing this duplicate.
I just need to find some time to implement it (of course, pull requests are welcome 😄).

**Comment by beerisgood** [comment]
You can still use the command, even if you use ffmpeg:
`youtube-dl.exe -o %(title)s.%(ext)s --prefer-ffmpeg --ffmpeg-location "ffmpeg\bin\ffmpeg.exe" -x --audio-format best <YOUTUBE-LINK>`

**Comment by Rudloff** [comment]
This will download the file on the computer then convert it, this it not what Alltube does. We convert the file on the fly and stream it directly to the browser.
Furthermore, we already have MP3 conversion set up with ffmpeg (see [this part of the code](https://github.com/Rudloff/alltube/blob/master/classes/VideoDownload.php#L266)) so there's no need to add youtube-dl calls here.
