### ISSUE TITLE
How to rename 

### ISSUE THREAD

**Issue by shanmugam023** [Rudloff/alltube#123]
Hi,

i need one help how to change the download YouTube videos  name

**Comment by Rudloff** [comment]
Hello,

By default, Alltube only redirects to the video file so we don't have any control over the filename.
If you are self-hosting Alltube, you can enable the [`stream` option](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#how-do-i-enable-streaming-videos-through-the-server) and then the video file will be automatically renamed.

**Comment by Rudloff** [comment]
No answer for a week so I'm closing this. Feel free to reopen if you have another issue.
