### ISSUE TITLE
Help in installation

### ISSUE THREAD

**Issue by sunnyujjawal** [Rudloff/alltube#124]
I am using Cloud Linux Server
Getting this error after uploading it to server:

Warning: require_once(/home2/ftpuser/public_html/tom/dailymotion-downloader/vendor/autoload.php): failed to open stream: No such file or directory in /home2/ftpuser/public_html/tom/dailymotion-downloader/index.php on line 3

Fatal error: require_once(): Failed opening required '/home2/ftpuser/public_html/tom/dailymotion-downloader/vendor/autoload.php' (include_path='.:/opt/php70/lib/php') in /home2/ftpuser/public_html/tom/dailymotion-downloader/index.php on line 3

**Comment by Rudloff** [comment]
Hello,

Did you install from Git or from a release package? If you installed from Git, you probably need to run `composer install` (and other commands from [the README](https://github.com/Rudloff/alltube/blob/master/README.md#setup)).

**Comment by sunnyujjawal** [comment]
I simply download the .zip files and upload to FTP using filezilla.

**Comment by Rudloff** [comment]
What zip file did you download exactly? If you don't have shell access on your server, you need to use the [release package](https://github.com/Rudloff/alltube/releases/download/0.10.0/alltube-0.10.0.zip).

**Comment by sunnyujjawal** [comment]
i downloaded from here https://image.prntscr.com/image/DiWQYF1uTHK3HlVGikbQJw.png
Let me try your link now.

**Comment by Rudloff** [comment]
Can you please have a look at your webserver logs to see if there is any PHP related errors and paste them here?

**Comment by sunnyujjawal** [comment]
Nothing much in error log:

[Wed Aug 16 05:47:03 2017] [error] [client 162.158.50.118] SoftException in Application.cpp:313: File "/home2/ftpuser/public_html/tom/dailymotion-downloader/index.php" is writeable by group

[Wed Aug 16 05:44:50 2017] [error] [client 162.158.50.118] SoftException in Application.cpp:313: File "/home2/ftpuser/public_html/tom/dailymotion-downloader/index.php" is writeable by group

[Wed Aug 16 05:42:17 2017] [error] [client 162.158.50.118] SoftException in Application.cpp:313: File "/home2/ftpuser/public_html/tom/dailymotion-downloader/index.php" is writeable by group

**Comment by Rudloff** [comment]
Sorry but I can't help you if I don't have a specific error.

**Comment by sunnyujjawal** [comment]
Ok.. Thanks a lot :)

**Comment by Rudloff** [comment]
I'm closing this but feel free to reopen if you have more info.
