### ISSUE TITLE
Error:   "Can't find Python at C:\Python27" [WIN]

### ISSUE THREAD

**Issue by seanvree** [Rudloff/alltube#125]
Hey guys! THis is a great project.  

OS:  Windows 10X64 1703
Webserver: IIS 10
Python: 2.7

ISSUE:  

Installed via packaged zip. Installed directly to my webserver at c:\intepub\wwwroot\alltube

When I navigate to localhost/alltube I get the follwing error in the browser:

```

Fatal error: Uncaught Exception: Can't find Python at C:\Python27\ in C:\inetpub\wwwroot\alltube\classes\VideoDownload.php:44 Stack trace: #0 C:\inetpub\wwwroot\alltube\controllers\FrontController.php(86): Alltube\VideoDownload->__construct() #1 C:\inetpub\wwwroot\alltube\index.php(30): Alltube\Controller\FrontController->__construct(Object(Slim\Container), NULL, Array) #2 {main} thrown in C:\inetpub\wwwroot\alltube\classes\VideoDownload.php on line 44
```

alltube\config\config.yaml looks like this:

```
youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py
python: C:\Python27\
params:
    - --no-playlist
    - --no-warnings
    - --playlist-end
    - 1
convert: false
avconv: C:\FFMPEG-win64\
rtmpdump: vendor/bin/rtmpdump
uglyUrls: false
stream: false
```

I run MANY python-based applications on my webserver so I"m not sure why this one is failing. 

THANKS!

**Comment by Rudloff** [comment]
Hello,

```yaml
python: C:\Python27\
```
This needs to point to Python's executable, not Python's folder. I don't use Windows but it its probably something like `C:\Python27\python.exe`.
(Same thing for ffmpeg.)

**Comment by seanvree** [comment]
Awesome! Thanks!
