### ISSUE TITLE
Audio only/in-browser playing

### ISSUE THREAD

**Issue by MarcelloTheArcane** [Rudloff/alltube#126]
2 parts:

1. Is it possible to configure this to download audio only?
2. Is it possible to get it to insert the video/audio as an html element, so it can be played in the browser?

**Comment by Rudloff** [comment]
Hello,
1. For some providers like Youtube, audio only formats are available in the format list. For the others you can enable [audio conversion](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#how-do-i-enable-audio-conversion).
1. I guess it would be possible but I don't really see the point. What is you use case here?

**Comment by MarcelloTheArcane** [comment]
1. Great! thanks :)
2. For when YouTube is blacklisted ;) and as a music streaming website (if you put 1. and 2. together)

**Comment by MarcelloTheArcane** [comment]
is [this](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#how-do-i-enable-streaming-videos-through-the-server) what I'm looking for? Also, if there was a way of forcing [this](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#my-browser-plays-the-video-how-do-i-download-it) behaviour inside an `<audio>` or `<video>` element.

**Comment by Rudloff** [comment]
Yes, the `stream` option can help you if Youtube is blocked (as long as the server itself can reach Youtube).

And we can probably build a player like this:
```html
<video src="http://example.com/alltube/redirect?url=[URL-encoded Youtube video URL]" controls></video>
```

**Comment by seanvree** [comment]
When I try to DL audio only from YouTube IT DLs an empty 1kb MP3 file. Any ideas why it does this @Rudloff ?

My config looks like this:

```
youtubedl: C:\Program Files (x86)\YoutubeDLG\bin\youtube-dl
python: C:\Python27\python.exe
params:
    - --no-playlist
    - --no-warnings
    - --playlist-end
    - 1
convert: true
avconv: C:\FFMPEG-win64\bin\ffmpeg.exe
rtmpdump: C:\rtmpdump\rtmpdump.exe
uglyUrls: true
stream: true
remux: true
```

**Comment by Rudloff** [comment]
@seanvree Please open a separate ticket for your issue.
Also I will need error logs from your web server in order to find the problem.

**Comment by seanvree** [comment]
@Rudloff  will do.

**Comment by Rudloff** [comment]
I'm closing this bug since there was no post since august.
@MarcelloTheArcane, please feel free to open another issue if you find a bug.
