### ISSUE TITLE
Soundcloud error:  "Unable to download JSON metadata: "

### ISSUE THREAD

**Issue by seanvree** [Rudloff/alltube#128]
OS:  windows 10E x64 1703
PHP:  7.1.7 x64
Webserver:  IIS 10
FFMPEG: 7.1.0
Youtube-dl version: 2017.09.02
python version:  2.7.13

When trying to download from a soundcloud link, I get the following error;

```
An error occured

Please check the URL of your video.
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
```

I can download almost anything else.  This used to work, not sure what changed.

config.yaml:

```
youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py
python: C:\Python27\python.exe
params:
    - --no-playlist
    - --no-warnings
    - --playlist-end
    - 1
convert: true
avconv: C:\FFMPEG-win64\bin\ffmpeg.exe
rtmpdump: C:\rtmpdump
uglyUrls: true
stream: true
remux: true

```

Screenshot:

![capture](https://user-images.githubusercontent.com/8906637/30342737-b9306f80-97af-11e7-9598-b41e5161d62f.PNG)

**Comment by Rudloff** [comment]
It's because the version of youtube-dl packaged in Alltube is too (and Soundcloud probably changed something int their website).
Updating it fixes this issue: https://github.com/Rudloff/alltube/commit/01d3b58c2913072744663336cbe93af5c1137dd2

If you want Alltube to use your more recent version, you can set the `youtubedl` parameter in your config file to point to your youtube-dl binary.

**Comment by seanvree** [comment]
@Rudloff  - okay, 

updated to the latest ver of youtube-dl, changed my config to look like this:

```
youtubedl: C:\youtube-dl\bin\youtube-dl.exe
python: C:\Python27\python.exe
params:
    - --no-playlist
    - --no-warnings
    - --playlist-end
    - 1
convert: true
avconv: C:\FFMPEG-win64\bin\ffmpeg.exe
rtmpdump: C:\rtmpdump
uglyUrls: true
stream: true
remux: true
```

Getting a diff error now:

```
An error occurred

Please check the URL of your video.
Could not import runpy module Exception zipimport.ZipImportError: "can't find module 'pkgutil'" in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored 
```

Also, you spelled "Occured" wrong in the code brotha.

**Comment by Rudloff** [comment]
Sorry, forgot to say that Alltube does not work with the .exe version of youtube-dl, you need to use [the standard version](https://yt-dl.org/downloads/2017.09.11/youtube-dl).

**Comment by seanvree** [comment]
Boom. 

Thanks,
