### ISSUE TITLE
display nothing,why ?

### ISSUE THREAD

**Issue by ucas123** [Rudloff/alltube#129]
Dear all:
    I'm trying to learn this open source website. I use the  release package   0.10.0  in my fedora system. I have configured my fedora system for example  install apache,php,mysql, then I put the alltube in my apache directory "/var/www/html/apache", then in my firefox I input  "localhost/alltube", it cann't display ,why. Is there any wrong?    Thanks in advance!

**Comment by Rudloff** [comment]
Hello,
You need to have a look at your Apache server's error log (I think in Fedora it is in `/var/log/httpd/error_log` but I'm not sure) and see if there is any errors.
Without this log, I can't really help you.

**Comment by ucas123** [comment]
Dear Rudloff：
   Thanks for your promptly  reply. The following from error_log:
[Sat Sep 30 23:14:33.243479 2017] [mpm_prefork:notice] [pid 8042] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Sep 30 23:14:34.343753 2017] [core:notice] [pid 8461] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Sat Sep 30 23:14:34.344462 2017] [suexec:notice] [pid 8461] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sat Sep 30 23:14:34.365492 2017] [auth_digest:notice] [pid 8461] AH01757: generating secret for digest authentication ...
[Sat Sep 30 23:14:34.365694 2017] [http2:warn] [pid 8461] AH02951: mod_ssl does not seem to be enabled
[Sat Sep 30 23:14:34.366357 2017] [lbmethod_heartbeat:notice] [pid 8461] AH02282: No slotmem from mod_heartmonitor
[Sat Sep 30 23:14:34.396389 2017] [mpm_prefork:notice] [pid 8461] AH00163: Apache/2.4.23 (Fedora) PHP/7.0.23 configured -- resuming normal operations
[Sat Sep 30 23:14:34.396409 2017] [core:notice] [pid 8461] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Sat Sep 30 23:14:34.397559 2017] [:warn] [pid 8462] ./mod_dnssd.c: No services found to register
[Sat Sep 30 23:14:49.112547 2017] [:error] [pid 8471] [client ::1:56664] PHP Fatal error:  Uncaught  --> Smarty: unable to write file /var/www/html/alltube/templates_c/wrt59cfb4e91b12c23953 <-- \n  thrown in /var/www/html/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_writefile.php on line 49. I  have modified the file "httpd.conf"  and the allowoverride was set all！I don't know why ?thanks for your kind help!

**Comment by Rudloff** [comment]
You need to make sure `templates_c` is writeable:
```bash
chmod 777 templates_c/
```

**Comment by ucas123** [comment]
Dear Rudloff:
    Before the website was runned, I have chomded  777 for all directory in  alltube. Now, I still have no way to solve it.The following link is my apache configulation files [https://pan.baidu.com/s/1sl0oQL3]. Is there any wrong? Thanks for you help again.

**Comment by Rudloff** [comment]
This error clearly states that the user running Apache/PHP can't write to `templates_c`:
```
[Sat Sep 30 23:14:49.112547 2017] [:error] [pid 8471] [client ::1:56664] PHP Fatal error: Uncaught --> Smarty: unable to write file /var/www/html/alltube/templates_c/wrt59cfb4e91b12c23953 <-- \n thrown in /var/www/html/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_writefile.php on line 49
```
You need to fix your permissions.

You can check your permissions with:
```bash
ls -l
```

You can also try using `chown` to make Apache's user the owner of `templates_c`:
```bash
chown apache templates_c
```

**Comment by ucas123** [comment]
Dear Rudloff 
         I have tried many times to use the following command "chown apache:apache -R templates_c chmod 777 ,and other method , but it still tips permissions problems. Now I  use another method to install php and apache that is able to run with root user and root group. The permission problems have solved, but a new error occuring tips the following from the error logs:
Slim Application Error:\nType: Error\nMessage: Class 'Locale' not found\nFile: /usr/local/httpd/htdocs/alltube/vendor/zonuexe/http-accept-language/src/AcceptLanguage.php\nLine: 112\nTrace: #0 /usr/local/httpd/htdocs/alltube/classes/Locale.php(36): Teto\\HTTP\\AcceptLanguage::parse('en_US')\n#1 /usr/local/httpd/htdocs/alltube/classes/LocaleMiddleware.php(71): Alltube\\Locale->__construct('en_US')\n#2 [internal function]: Alltube\\LocaleMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#3 /usr/local/httpd/htdocs/alltube/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Alltube\\LocaleMiddleware), Array)\n#4 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#5 /usr/local/httpd/htdocs/alltube/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(73): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#6 /usr/local/httpd/htdocs/alltube/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#7 /usr/local/httpd/htdocs/alltube/vendor/slim/slim/Slim/App.php(370): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#8 /usr/local/httpd/htdocs/alltube/vendor/slim/slim/Slim/App.php(295): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#9 /usr/local/httpd/htdocs/alltube/index.php(54): Slim\\App->run()\n#10 {main}\nView in rendered output by enabling the "displayErrorDetails" setting.\n. Why it cann't run in my fedora system?

**Comment by Rudloff** [comment]
```
Message: Class 'Locale' not found
```
You need to install the intl extension for PHP (the `php-intl` package in Fedora, I guess).

**Comment by ucas123** [comment]
Dear Rudloff:
   Many thanks to you. Now it can be runned after installing the intl extension!
