### ISSUE TITLE
ERROR: PhantomJS executable not found in PATH

### ISSUE THREAD

**Issue by intanandani** [Rudloff/alltube#132]
![screenshot at nov 02 04-39-04](https://user-images.githubusercontent.com/31055632/32299346-dd862f00-bf87-11e7-97c2-4871fd01e43b.png)

I try to use genereate download for openload link but error like the image shown above.

link : https://openload.co/embed/qTsjMEUtN4U

**Comment by Rudloff** [comment]
Hello,

Openload downloads are a bit tricky because we need a JavaScript engine in order to get the video's URL. And I don't want to install PhantomJS on the server just for this website.

However if you host Alltube on your own server, you can easily install PhantomJS and it will probably work.

**Comment by intanandani** [comment]
Any references to install it ?

I try to install the all tube in localhost but it fail too.
My pc is already installed PhantomJS.

I run youtube-dl for openload and it's work, but for alltube don't work.

Thanks

**Comment by Rudloff** [comment]
Do you get the same PhantomJS error on you local Alltube?
Are you able to download videos from other websites like Youtube with it?

**Comment by intanandani** [comment]
Yes, the local Alltube error like the image before.

For youtube is normal, I can download and the thumbnail is shown,

**Comment by Rudloff** [comment]
If you get this error, it means that PhantomJS is not correctly installed or it is not in your [PATH](https://en.wikipedia.org/wiki/PATH_(variable)).

**Comment by Rudloff** [comment]
No answer so I'm closing. Please feel free to open a new issue if you find another bug.

**Comment by TalmarGrosskotz** [comment]
Hi, I installed phantomjs on my debian system via apt but I still get the message about the executable not being in my PATH. how can I add it there?

**Comment by Rudloff** [comment]
Hello,
You need to add something like this to your `config/config.yml` file:
```yaml
phantomjsDir: /usr/bin/
```

**Comment by q12a** [comment]
my solution to this error was to clean my host file. Everything got to normal after that. No need of anything to add extra. ;)
