### ISSUE TITLE
Find a better way to debug audio conversions

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/alltube#140]
If ffmpeg fails we don't get any error (just an empty file) which makes it very difficult to debug cases like #136.

**Comment by Rudloff** [comment]
Reported upstream: https://github.com/slimphp/Slim/issues/2338

**Comment by githubgobi** [comment]
That options are on progress?

**Comment by Rudloff** [comment]
I'm not sure what you mean? The audio conversion feature is complete, it's just that when it fails we get an empty file instead of an useful error.

**Comment by Rudloff** [comment]
Closing with https://github.com/Rudloff/alltube/commit/4ae585eef1adae94f3abeda84b7d347bacc0752a, since we can't really do better than logging ffmpeg errors. (We should also add checks for individual problems.)
