### ISSUE TITLE
Audio File Not Downloading Only Downloaded Empty File

### ISSUE THREAD

**Issue by githubgobi** [Rudloff/alltube#142]
# New issue

## Your environment  - Localhost

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?** Windows

**What is your web server (Apache, IIS, etc.)?** Apache

**What version of Alltube are you using?** Latest

**How did you install Alltube (with Git or with a release package)?** composer

**What version of PHP are you using?** 5.5

**What version of Python are you using?**2.7

**What version of youtube-dl are you using?**latest

**Do you get any PHP-related errors in your webserver's logs?** no

## Describe your issue
Video File downloading Success But Audio File Not Downloading,When i choose audio file to download it empty file downloaded automatically.

**Comment by Rudloff** [comment]
Hello,

Audio conversion errors are kind of hard to debug, especially on Windows.

Please answer these questions to help diagnose the issue:
* What is the content of your `config/config.yml` file? You need to make sure the `avconv` option points to a working avconv or ffmpeg binary.
* Does avconv/ffmpeg work correctly when called from the commandline?
* Please provide the URL of a video that causes the issue.

**Comment by githubgobi** [comment]
this line runs : popen($avconvProc->getCommandLine(), 'r'); 

result is : object(Slim\Http\Stream)[113]
  protected 'stream' => resource(177, stream)
  protected 'meta' => null
  protected 'readable' => null
  protected 'writable' => null
  protected 'seekable' => null
  protected 'size' => null
  protected 'isPipe' => null

**Comment by Rudloff** [comment]
Can you please answer my questions?

Your test only tells us that popen works but not what ffmpeg returns.
What you can try is this:
```php
var_dump($avconvProc->getCommandLine());
```
It will give you a command that you can then run in your console in order to see if it outputs any errors.

**Comment by githubgobi** [comment]
I have run the console above you mentioned `var_dump($avconvProc->getCommandLine());`

result is : string 'C:\Python27\Scripts\ffmpeg.exe -v quiet -user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)" -i "https://r1---sn-5jucgv5qc5oq-jwce.googlevideo.com/videoplayback?requiressl=yes&initcwndbps=550000&key=yt6&gir=yes&mime=audio"^%"2Fwebm&itag=251&mt=1511182965&expire=1511204652&sparams=clen"^%"2Cdur"^%"2Cei"^%"2Cgir"^%"2Cid"^%"2Cinitcwndbps"^%"2Cip"^%"2Cipbits"^%"2Citag"^%"2Ckeepalive"^%"2Clmt"^%"2Cmime"^%"2Cmm"^%"2Cmn"^%"2Cms"^%"2Cmv"^%"2Cpl"^%"2Crequiressl"^%"2Csource"^%"2'... (length=868)

**Comment by Rudloff** [comment]
Yes and you can now try to run this whole command (maybe without `-v quiet`) in Windows' terminal to see why it fails.
(`C:\Python27\Scripts\ffmpeg.exe` is a weird place to install ffmpeg. Is it really installed here?)

Also, you still haven't answered my initial questions...

**Comment by githubgobi** [comment]
1. **What is the content of your config/config.yml file? You need to make sure the avconv option points to a working avconv or ffmpeg binary?**

Ans :  # Path to your youtube-dl binary
youtubedl: C:\Python27\Scripts\youtube-dl.exe

# Path to your python binary
python: C:\Python27\python.exe

# An array of parameters to pass to youtube-dl
params:
    - --no-playlist
    - --no-warnings
    - --playlist-end
    - 1

# True to enable audio conversion
convert: true

# Path to your avconv or ffmpeg binary
avconv: C:\Python27\Scripts\ffmpeg.exe

# Path to your rtmpdump binary
rtmpdump: vendor/bin/rtmpdump

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
stream: false


2. **Does avconv/ffmpeg work correctly when called from the commandline?** 
ans : Yes

3.**Please provide the URL of a video that causes the issue.**
ans: [](https://www.youtube.com/watch?v=lTTajzrSkCw)

**Comment by githubgobi** [comment]
![screenshot_1](https://user-images.githubusercontent.com/13116643/33021188-f8e8b68e-ce26-11e7-9ade-fdd5afa8b828.png)

Please find the attachment,
Python & ffmpeg are working great. see above attachment

**Comment by Rudloff** [comment]
This looks more and more like #136, but it is **really** hard to see what is happening exactly without an error message.
So I'm afraid I won't be able to help you (at least until #140 is fixed).

**Comment by Rudloff** [comment]
I'm closing this but feel free to reopen if you can provide an error message.
