### ISSUE TITLE
openload.co Error

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#146]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

Linux

**What is your web server (Apache, IIS, etc.)?**

N/A

**What version of Alltube are you using?**

Same of site https://alltubedownload.net/

**How did you install Alltube (with Git or with a release package)?**

N/A

**What version of PHP are you using?**

Same of site https://alltubedownload.net/

**What version of Python are you using?**

Same of site https://alltubedownload.net/

**What version of youtube-dl are you using?**

Same of site https://alltubedownload.net/

**Do you get any PHP-related errors in your webserver's logs?**

N/A

**What is the content of your `config/config.yml` file?**

N/A

**Please provide the URL of a video that causes the issue.**

https://openload.co/embed/a-WWHDWqlSs/

## Describe your issue

Try to download any vídeo from openload and get an error **ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org***

**Comment by Rudloff** [comment]
Hello,
We could install phantomjs on the server.
I'm just waiting to see if youtube-dl could allow to set the path manually (https://github.com/rg3/youtube-dl/issues/15146) so we don't have to mess with `PATH`.

**Comment by Rudloff** [comment]
Alltube now includes a phantomjs binary so openload videos will work in the next release.
