### ISSUE TITLE
Alltube as a LAN cache of Youtube?

### ISSUE THREAD

**Issue by paulcmal** [Rudloff/alltube#149]
Note: This is not a bug but a question so I'm not sure if I'm posting in the right place, but I didn't find a forum or e-mail address to contact. Feel free to close the issue and redirect me elsewhere if appropriate.

Being on a strong LAN with a very weak uplink, I'm looking for a way to cache locally Youtube (mostly) videos. But I didn't find any information in the README/FAQ nor in the config file about where the downloaded videos are stored, and for how long.

I'm curious about the general orientations of this project and if your goals are compatible with what I have in mind. Else I might just try to code something myself using your project as a library. 

Thanks a lot for making and maintaining Alltube, it's already wonderful in a shitton of cases! <3

**Comment by Rudloff** [comment]
Hello,

Alltube never stores videos, it sends them directly to the browser.
It was one of the original goals of the project, so it could be used on a relatively small server.

I guess Alltube could be used [as a library](https://github.com/Rudloff/alltube#use-as-library) for what you are trying to do, although there are other projects like [youtube-dl-php](https://github.com/norkunas/youtube-dl-php) that focus more on downloading the video to the server's drive.

**Comment by Rudloff** [comment]
I'm closing this, but please feel free to reopen if you have new questions.

**Comment by paulcmal** [comment]
Thanks for the straightforward answer!
