### ISSUE TITLE
Youtube downloads fail

### ISSUE THREAD

**Issue by TalmarGrosskotz** [Rudloff/alltube#152]
# Downloads from Youtube fail

## Cubietruck 

Please answer these questions when reporting a new issue:

**I use Armbian (Ubuntu-Xenial Derivative on armfh**

**Apache 2.14**

**Alltube v1.0.0**

**Release Package**

**PHP 7.0.25-0ubuntu0.16.04.1**

**Python 2.7 or 3.5.2**

**Packaged from Release package**

**Error message: [Tue Feb 27 09:17:20.885015 2018] [:error] [pid 23125] [client myextip:57214] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/alltube/vendor/guzzlehttp/psr7/src/Stream.php on line 218, referer: https://myurl/alltube/video?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZSn3Tvc7jQU**

> My config.yml
> ---
>
>#path to phantomjs
>phantomjsDir: /usr/local/bin/
>
># Path to your youtube-dl binary
>youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py
>
># Path to your python binary
>python: /usr/bin/python

># An array of parameters to pass to youtube-dl
>params:
>   - --no-warnings
>    - --ignore-errors
>   - --flat-playlist
>  - --restrict-filenames
>
># True to enable audio conversion
>convert: true
>
>
># True to enable advanced conversion mode
>convertAdvanced: true
>
># List of formats available in advanced conversion mode
>convertAdvancedFormats: [mp3, avi, flv, wav]
>
># Path to your avconv or ffmpeg binary
>avconv: vendor/bin/ffmpeg
>
># avconv/ffmpeg logging level.
>avconvVerbosity: error
>
># Path to the directory that contains the phantomjs binary.
>#phantomjsDir: vendor/bin/
>
># True to disable URL rewriting
>uglyUrls: false
>
># True to stream videos through server
>stream: true

># MP3 bitrate when converting (in kbit/s)
>audioBitrate: 128

**Tried downloading: https://www.youtube.com/watch?v=YE1EoxKV53w**

## Describe your issue
When I want to download a film from Youtube everything works fine for a while, but at a certain undetermined point the download stops and fails. If i rename the "part"-file the Browser saved up to taht point into mp4 it works up to that point.

How can i fix it to ensure complete downloads.

**Comment by Rudloff** [comment]
Hello,

I could not reproduce but it seems downloading a chunk of the video takes too much time and it reaches PHP's maximum execution time.
You can try setting a longer time by changing the [max_execution_time](https://secure.php.net/manual/fr/info.configuration.php#ini.max-execution-time) option in your `php.ini` file.
(Or you could simply disable the `stream` option in Alltube's config and download the video directly.)

**Comment by Rudloff** [comment]
Yes, [most browsers play the video](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#my-browser-plays-the-video-how-do-i-download-it) if it is MP4 or Webm but you can save it. We can't force the download or the filename for a file on another domain so you will have to rename the downloaded video manually.

**Comment by TalmarGrosskotz** [comment]
I understand. Renaming the redirect.htm worked indeed. Please consider my issue closed. Thanks for the quick support.

⁣Gesendet mit BlueMail ​
