### ISSUE TITLE
"Page not found" when making static pages

### ISSUE THREAD

**Issue by elmarcomilani** [Rudloff/alltube#153]
Hi, I'm getting 
```
Page Not Found
The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.
``` 
when making a static HTML ToS page in the root directory of the script.

Is it because of Smarty and its routes?

**Comment by Rudloff** [comment]
Hello,

Are you using Apache?
The rewrite rule in `.htaccess` should be ignored when the URL points to a file that actually exists in the folder.

**Comment by elmarcomilani** [comment]
Oh I thought it was Smarty's fault. Thank you!
