### ISSUE TITLE
I ran into some issues with composer install,

### ISSUE THREAD

**Issue by toproxy** [Rudloff/alltube#155]
New issue
Your environment
Please answer these questions when reporting a new issue:

What is your operating system (Windows, Linux, OSX, etc.)?
Ubuntu 16.04

What is your web server (Apache, IIS, etc.)?
apache 2.4

What version of Alltube are you using?
1.0

How did you install Alltube (with Git or with a release package)?
Git

What version of PHP are you using?
7.2.2

What version of Python are you using?
3.5

What version of youtube-dl are you using?
2018.02.04

Do you get any PHP-related errors in your webserver's logs?
Nope

Describe your issue
hi,bro
I ran into some issues with composer install.

Composer version 1.6.3 2018-01-31 16:28:17

`root@tube:/home/wwwroot/# composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barracudanetworks/archivestream-php 1.0.5 -> satisfiable by barracudanetworks/archivestream-php[1.0.5].
    - barracudanetworks/archivestream-php 1.0.5 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/php/etc/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
`

**Comment by Rudloff** [comment]
```
the requested PHP extension gmp is missing from your system.
```
You need to install the [GMP](https://secure.php.net/manual/en/book.gmp.php) extension. (The package is named `php-gmp` on Ubuntu.)

**Comment by toproxy** [comment]
I try apt-get install php7.0-gmp

extension = gmp.so

But still invalid.

**Comment by Rudloff** [comment]
Are you sure you get the exact same error now? Alltube might require other extensions that you don't have.
If it still does not load the extension, it is probably because something is wrong in your `php.ini` file.

**Comment by toproxy** [comment]
I also think there PHP.INI problems, you can recommend a stable installation environment?, I am very grateful.

**Comment by Rudloff** [comment]
I just noticed that Composer lists only `/usr/local/php/etc/php.ini` as your `php.ini` file whereas on my Ubuntu server the file is `/etc/php/7.0/cli/php.ini`.
Are you using a custom PHP and not the official Ubuntu package? It could explain why it can't load the extension.

Anyway, you might be able to get some help about your configuration on [Ask Ubuntu](https://askubuntu.com/).
