### ISSUE TITLE
Security issues in readme instructions

### ISSUE THREAD

**Issue by Zulgrib** [Rudloff/alltube#156]
# New issue

## Your environnement
ANY

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
ANY

**What is your web server (Apache, IIS, etc.)?**
ANY

**What version of Alltube are you using?**
ANY
**How did you install Alltube (with Git or with a release package)?**
ANY

**What version of PHP are you using?**
ANY
**What version of Python are you using?**
ANY
**What version of youtube-dl are you using?**
ANY
**Do you get any PHP-related errors in your webserver's logs?**
No
**What is the content of your `config/config.yml` file?**
Default 
**Please provide the URL of a video that causes the issue.**
N/A
## Describe your issue

Readme tells to do "chmod 777" which generate a security issue.
No folder should be world writable.

**Comment by Rudloff** [comment]
You're right. I changed it to `770` (which is what Smarty recommends): https://github.com/Rudloff/alltube/commit/2ae2141a46616c25e48ab3eacd83e9061b2a9a32
