### ISSUE TITLE
Use VideoDownload as a library

### ISSUE THREAD

**Issue by fung626** [Rudloff/alltube#157]
How can I use VideoDownload class separately? I have setting heroku server by using your project, but i don't konw how to use VideoDownload as a library. Do I need to setup anything else? Also I replaced index.php as follow code:  
```php
<?php

use Alltube\Config;
use Alltube\VideoDownload;

require_once __DIR__.'/vendor/autoload.php';

$downloader = new VideoDownload(
    new Config(
        [
            'youtubedl' => '/usr/local/bin/youtube-dl',
            'python'    => '/usr/bin/python',
        ]
    )
);

//Extract the URL of a video from a webpage
$downloader->getURL('https://www.youtube.com/watch?v=dQw4w9WgXcQ');

//Get a specific format
$downloader->getURL('https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'worst');

//Get the whole decoded JSON extracted by youtube-dl
$downloader->getJSON('https://www.youtube.com/watch?v=dQw4w9WgXcQ');

//See complete class documentation here: https://alltube.surge.sh/classes/Alltube.VideoDownload.html
```
Unfortunately, I got HTTP ERROR 500 after. Maybe the error caused by importing Config and VideoDownload classes. Can you show me how it works? sorry for my English. Thanks

**Comment by Rudloff** [comment]
Hello,

Could you please have a look at your webserver's logs and see if you get any PHP error?
I can't help you if I don't know what's going on.

**Comment by Rudloff** [comment]
I'm not sure I understand what you are doing here...
First you should test locally before trying to use Heroku.

Then are you using the AllTube repository as a basis? If you want to use it as a library, you need to create a new separate project (or clone alltube-example-project) and install Alltube as a dependency of this project with [Composer](https://getcomposer.org/).

And finally, the PHP error you posted says that [youtube-dl](http://rg3.github.io/youtube-dl/) is not available at the specified path. The `youtubedl` you pass to the `Alltube\Config` constructor must point to where youtube-dl is installed.

**Comment by fung626** [comment]
sorry for confusing. I want to setup a JSON API for my application. The JSON format like

```
{
  "title": "xxx", 
  "thumbnail": "xxx",
  "description":"xxx",
  "url": "https://redirector.googlevideo.com/videoplayback?mn=sn-n4v7knls%2Csn-n4v7sn7y&mm=31%2C29&expire=1521497775&initcwndbps=232500&ipbits=0&key=yt6&lmt=1513190019692712&ip=2600%3A3c01%3A%3Af03c%3A91ff%3Afe24%3Ab564&dur=1217.909&itag=22&pl=63&mv=m&mt=1521476065&ms=au%2Crdu&ei=T-KvWt7BBIHA_APJy6KgDQ&signature=12C004E3CDC4719BAC8DDA46A746019B9C532AF3.99BA15E15751A8B6C40A71C35F9827E05CB6FB35&source=youtube&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&c=WEB&fvip=3&mime=video%2Fmp4&id=o-ALgD7IdBh2yvA2c-LjzUp8YQtE083Pc9jRRarjzC3N8t&ratebypass=yes&requiressl=yes"
}
```

I tried https://alltubedownload.net/json url on https://github.com/Rudloff/alltube/wiki/JSON-API. 

The format I tried as follow: 

https://alltubedownload.net/json?url=Youtube_Url

https://alltubedownload.net/json/url/Youtube_Url

However, it didn't worked

**Comment by Rudloff** [comment]
The JSON API was removed a long time ago because nobody was using it and I totally forgot to delete the wiki page, sorry.

What are you trying to do exactly in your application?

**Comment by fung626** [comment]
The application I am trying to build is a android/iOS application. Just like your project, my application need the video source url to download the video. 

As a result, I want to setup JSON API for application. I am not sure how your JSON API works, but I think that is what exactly I been looking for. As mentioned, I found out JSON API that on your wiki page is not working. And now I want to setup another one.

**Comment by Rudloff** [comment]
If you only need the URL of the video, you could make an HTTP request to https://alltubedownload.net/redirect?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DM7IpKCZ47pU for example and read the `Location` header.

But I might bring the JSON API back, I just need to take some time to figure out the best way to do it.

**Comment by fung626** [comment]
Thanks for your patience and help, you really saved my day. I have figured it out finally. By following your instruction, I just need to download your [example project](https://github.com/Rudloff/alltube-example-project) and modify the composer.json and index.php. The problem was my missing php extension, so all I need to do is to redirect the php location under my **MAMP** php by running this

`export PATH=/Applications/MAMP/bin/php/php7.2.1/bin:$PATH`


```
{
	"name": "rudloff/alltube",
         "description": "HTML GUI for youtube-dl",
	"license": "GPL-3.0",
	"require": {
		"rudloff/alltube": "0.6.0",
		"rg3/youtube-dl": "2018.01.21"
	},
	"repositories": [
    {
      "type": "package",
      "package": {
        "name": "rg3/youtube-dl",
        "version": "2018.01.21",
        "dist": {
          "type": "zip",
          "url": "https://github.com/rg3/youtube-dl/archive/2018.01.21.zip"
        }
      }
    }]
}
```
```
<?php

error_reporting(E_ALL);
ini_set("display_errors","On");

require_once __DIR__.'/vendor/autoload.php';

use Alltube\Config;
use Alltube\VideoDownload;

$config = new Config([]);
$downloader = new VideoDownload($config);

$videoURL = $_GET['videoURL'];

//Extract the URL of a video from a webpage
$url = $downloader->getURL($videoURL);

//Get a specific format
// $url = $downloader->getURL('https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'worst');

//Get the whole decoded JSON extracted by youtube-dl
// $jsonString = $downloader->getJSON('https://www.youtube.com/watch?v=dQw4w9WgXcQ');

echo $url;

```

Then, run `composer update ` in cmd and push the project on heroku. It worked finally. 

But pls, one more question, how many format that I can pass in getJSON() function? Only best or worst? How can tell how many format there are?

**Comment by Rudloff** [comment]
[This part of the youtube-dl doc](https://github.com/rg3/youtube-dl#format-selection) explains what options you can use for the format.

**Comment by Rudloff** [comment]
The JSON API is back in the new 1.1.0 release :smiley: 
https://github.com/Rudloff/alltube#json-api

**Comment by fung626** [comment]
Thanks for your help again

**Comment by Rudloff** [comment]
I'm closing this since it looks like you got what you need but feel free to open another issue if necessary.
