### ISSUE TITLE
Redirect "Page Not Found"

### ISSUE THREAD

**Issue by elmarcomilani** [Rudloff/alltube#159]
Hi,

how can I redirect the default "Page Not Found" to another custom page (ex. 404.html) or to the homepage?

Thanks in advance.

**Comment by Rudloff** [comment]
Hello,

You can use this Slim handler: https://www.slimframework.com/docs/v3/handlers/not-found.html

Here is a very basic example:
```diff
diff --git a/index.php b/index.php
index e59b357..a127b83 100644
--- a/index.php
+++ b/index.php
@@ -35,6 +35,13 @@ $controller = new FrontController($container, null, $_COOKIE);
 
 $container['errorHandler'] = [$controller, 'error'];
 
+$container['notFoundHandler'] = function () {
+    return function (Psr\Http\Message\ServerRequestInterface $request, Psr\Http\Message\ResponseInterface $response) {
+        //Do something with the response here
+        return $response;
+    };
+};
+
 $app->get(
     '/',
     [$controller, 'index']
```

**Comment by elmarcomilani** [comment]
Thanks for the very quick reply.

Where do I place that code? In index.php or in FrontController.php?

**Comment by Rudloff** [comment]
It goes in `index.php` where the other `$container` components are created.

**Comment by elmarcomilani** [comment]
I deleted my comment 30 seconds before your reply realizing how dumb I was haha.

Thanks a lot, it worked perfectly!

**Comment by Rudloff** [comment]
Don't worry, it happens to all of us.

Can I close this issue or did you have any other question?

**Comment by elmarcomilani** [comment]
It was just this question :)

I'll close this, don't worry.
