### ISSUE TITLE
slow conversion with avconv

### ISSUE THREAD

**Issue by gergernaut** [Rudloff/alltube#16]
avconv seems to convert videos to mp3 really slow with the commands used in the api.php
I figured out the problem seems to be fixed with the addition of -vn to the input parameters,
like this:
|  /usr/bin/avconv -v quiet -i - -vn -f mp3 pipe:1

the problem occurs using avconv version 9.18-6:9.18 on ubuntu. 

see: https://askubuntu.com/questions/449978/very-slow-conversion-with-avconv-libav-trusty-tahr-14-04

**Comment by Rudloff** [comment]
I was wondering why it was so slow. Thanks!
