### ISSUE TITLE
Feature Request: Upload local files for conversion

### ISSUE THREAD

**Issue by daCaPo** [Rudloff/alltube#161]
We regularly need to convert different kinds of video or sound files to mp3 with certain parameters (e. g., there must be no embedded images). Wouldn't it be possible to add a file upload function as an alternative to entering a download URL?

**Comment by Rudloff** [comment]
Hello,

This is out of the scope of this project, which is to create a GUI for youtube-dl.

There are other projects that aim to do this like [ffmpeg-web-gui](https://github.com/swooningfish/ffmpeg-web-gui) (although this one is quite old)/

Or if you are a PHP developer, you could have a look at how we handle conversion here (and use this as a basis to build what you need): https://github.com/Rudloff/alltube/blob/2a3612d7ecc9da7dd1abcb364d165b58816c3bec/classes/VideoDownload.php#L270
