### ISSUE TITLE
still cant download from openload

### ISSUE THREAD

**Issue by Q8hma** [Rudloff/alltube#162]
**What is your operating system (Windows, Linux, OSX, etc.)?**
Linux (Centos + cpanel)
**What version of AllTube are you using?**
        "rudloff/alltube": "^1.1",
**How did you install AllTube (with Git or with a release package)?**
composer
**What version of PHP are you using?**
php 7.1
**What version of Python are you using?**
3
**What version of youtube-dl are you using?**
last one
**Do you get any PHP-related errors in your webserver's logs?**
no
**What is the content of your `config/config.yml` file?**
none
**Please provide the URL of a video that causes the issue.**
https://openload.co/embed/0hbclp3FTqQ

## Describe your issue

Hello so sorry for my bad english
i try all the fix code i read here but still can get any fix for my problem
i got this error

 PhantomJS executable not found in PATH, download it from http://phantomjs.org

this is the full error
`Exception Object
(
    [message:protected] => ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org
    [string:Exception:private] => 
    [code:protected] => 1
    [file:protected] => /home/000000/public_html/vendor/rudloff/alltube/classes/VideoDownload.php
    [line:protected] => 119
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /home/0000/public_html/vendor/rudloff/alltube/classes/VideoDownload.php
                    [line] => 137
                    [function] => getProp
                    [class] => Alltube\VideoDownload
                    [type] => ->
                    [args] => Array
                        (
                            [0] => https://openload.co/embed/0hbclp3FTqQ
                            [1] => 
                            [2] => dump-single-json
                            [3] => 
                        )

                )

            [1] => Array
                (
                    [file] => /home/0000/public_html/index.php
                    [line] => 36
                    [function] => getJSON
                    [class] => Alltube\VideoDownload
                    [type] => ->
                    [args] => Array
                        (
                            [0] => https://openload.co/embed/0hbclp3FTqQ
                        )

                )

        )

    [previous:Exception:private] => 
)
`

thnx and so sorry if its fix before with out i see ... note : i try from ur site and same can't get any json info

**Comment by Rudloff** [comment]
Hello,
openload is currently broken in youtube-dl (the library we use to extract videos): https://github.com/rg3/youtube-dl/issues/16136, https://github.com/rg3/youtube-dl/issues/16137
So we have to wait to see if they will fix it. I'll keep you updated.

**Comment by Q8hma** [comment]
thnx bro

**Comment by mindjek07** [comment]
![image](https://user-images.githubusercontent.com/32357822/39740276-909df1c8-52b2-11e8-9bce-48872dfc3ba8.png)
 working fine

**Comment by Rudloff** [comment]
@Q8hma By looking again at your report, I see that your problem is that youtube-dl can't find [phantomjs](http://phantomjs.org/).

Is phantomjs installed in `vendor/bin/` or system-wide? Is it in your [`PATH`](https://en.wikipedia.org/wiki/PATH_(variable))?

**Comment by Q8hma** [comment]
i will try it to install in in "vendor/bin/" ... i install it in other folder

thnx

**Comment by Rudloff** [comment]
It's OK if phantomjs is installed elsewhere but then you need to add the path to `config/config.yml`.
For example, if it is installed in `/usr/bin/`:
```yaml
phantomjsDir: /usr/bin/
```

**Comment by Rudloff** [comment]
@Q8hma Did you manage to get it working?

**Comment by Rudloff** [comment]
No answer so I'm closing.
