### ISSUE TITLE
Vimeo audio only dont working as expected

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#165]
**What is your operating system (Windows, Linux, OSX, etc.)?**
n/a

**What is your web server (Apache, IIS, etc.)?**
n/a 

**What version of AllTube are you using?**
https://alltubedownload.net/

**How did you install AllTube (with Git or with a release package)?**
n/a 

**What version of PHP are you using?**
n/a 

**What version of Python are you using?**
n/a 

**What version of youtube-dl are you using?**
n/a 

**Do you get any PHP-related errors in your webserver's logs?**
n/a 

**What is the content of your `config/config.yml` file?**
n/a 

**Please provide the URL of a video that causes the issue.**
https://vimeo.com/251997032

## Describe your issue
Try to download audio only **(vimeo)** on https://alltubedownload.net/ and file with 0kb is downloaded

**Comment by Rudloff** [comment]
Hello,

Thanks for the report!
I published a new release that fixes the issue.
