### ISSUE TITLE
 Can't find Python at /usr/bin/python

### ISSUE THREAD

**Issue by sukhcha-in** [Rudloff/alltube#166]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Windows
**What is your web server (Apache, IIS, etc.)?**
Apache
**What version of AllTube are you using?**
Latest
**How did you install AllTube (with Git or with a release package)?**
Composer
**What version of PHP are you using?**
5.6
**What version of Python are you using?**
3.7
**What version of youtube-dl are you using?**
Latest
**Do you get any PHP-related errors in your webserver's logs?**
 Can't find Python at /usr/bin/python
**What is the content of your `config/config.yml` file?**
Same as config.example.yml
**Please provide the URL of a video that causes the issue.**
Not even homepage is loading
## Describe your issue
I am getting python error, i have installed python on my pc, configured it in apache httpd.conf, Still getting python error, how can i fix this? I am new to python.

**Comment by Rudloff** [comment]
Hello,

I you are on Windows, your Python binary is probably not at `/usr/bin/python`, so you need to add something like this to `config/config.yml`:
```yaml
python: C:\path\to\python.exe
```

**Comment by sukhcha-in** [comment]
Thank you! It Worked!
