### ISSUE TITLE
Blank Format Option

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#170]
# New issue

## Your environment

https://alltubedownload.net

**What is your operating system (Windows, Linux, OSX, etc.)?**

Windows 10

**What is your web server (Apache, IIS, etc.)?**

N/A

**What version of AllTube are you using?**

https://alltubedownload.net

**How did you install AllTube (with Git or with a release package)?**

N/A

**What version of PHP are you using?**

https://alltubedownload.net

**What version of Python are you using?**

https://alltubedownload.net

**What version of youtube-dl are you using?**

https://alltubedownload.net

**Do you get any PHP-related errors in your webserver's logs?**

N/A

**What is the content of your `config/config.yml` file?**

N/A

**Please provide the URL of a video that causes the issue.**

https://www.youtube.com/watch?v=n_OHjeugEv4

## Describe your issue

Blank format option description on most links

 **Screenshot**
![capturar](https://user-images.githubusercontent.com/6363160/40205204-9052085c-5a01-11e8-8b61-9789260e2d55.PNG)

**Comment by Rudloff** [comment]
Thanks for the report! This will be fixed in the next release.
