### ISSUE TITLE
Name of videos dont appers in some Youtube playlist

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#171]
# New issue

## Your environment

https://alltubedownload.net

**What is your operating system (Windows, Linux, OSX, etc.)?**

Windows 10

**What is your web server (Apache, IIS, etc.)?**

N/A

**What version of AllTube are you using?**

https://alltubedownload.net

**How did you install AllTube (with Git or with a release package)?**

N/A

**What version of PHP are you using?**

https://alltubedownload.net

**What version of Python are you using?**

https://alltubedownload.net

**What version of youtube-dl are you using?**

https://alltubedownload.net

**Do you get any PHP-related errors in your webserver's logs?**

N/A

**What is the content of your `config/config.yml` file?**

N/A

**Please provide the URL of a video that causes the issue.**

https://www.youtube.com/watch?v=cTlshvPrIZo&list=RDGMEMYH9CUrFO7CfLJpaD7UR85wVMcTlshvPrIZo&start_radio=1

## Describe your issue

Name in some YouTube playlist dont appers

URL: https://www.youtube.com/watch?v=cTlshvPrIZo&list=RDGMEMYH9CUrFO7CfLJpaD7UR85wVMcTlshvPrIZo&start_radio=1

 **Screenshot**
![capturar](https://user-images.githubusercontent.com/6363160/40271374-e7db2190-5b72-11e8-8641-0693e6571bb7.PNG)

**Comment by Rudloff** [comment]
The problem here is that it's not a real playlist but a dynamic mix generated by Youtube (so the content will be different for each user) and so youtube-dl gives incoherent results.

For now, I changed the behavior so that it will download the current video and not try to show the playlist.
I'll see if I can get the full playlist info but I'm not sure there is much we can do.

**Comment by ialexsilva** [comment]
Thanks for explanation @Rudloff

**Comment by Rudloff** [comment]
It seems we can't even access the playlist info page: https://www.youtube.com/playlist?list=RDGMEMYH9CUrFO7CfLJpaD7UR85wVMcTlshvPrIZo&pbjreload=10
I get a blank page.

So I don't think we can do anything, I'm closing this.
