### ISSUE TITLE
Error downloading audio

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#172]
# New issue

## Your environment

https://alltubedownload.net

**What is your operating system (Windows, Linux, OSX, etc.)?**

Windows 10

**What is your web server (Apache, IIS, etc.)?**

N/A

**What version of AllTube are you using?**

https://alltubedownload.net

**How did you install AllTube (with Git or with a release package)?**

N/A

**What version of PHP are you using?**

https://alltubedownload.net

**What version of Python are you using?**

https://alltubedownload.net

**What version of youtube-dl are you using?**

https://alltubedownload.net

**Do you get any PHP-related errors in your webserver's logs?**

N/A

**What is the content of your `config/config.yml` file?**

N/A

**Please provide the URL of a video that causes the issue.**

https://www.youtube.com/watch?v=ffxKSjUwKdU&list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG

## Describe your issue

If you try to download a playlist with "audio only" enabled, the server returns a error.

**Comment by Rudloff** [comment]
Thanks for the report. This will be fixed in the next release.
