### ISSUE TITLE
Reddit (requested format not available)

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#173]
# New issue

## Your environment

https://alltubedownload.net

**What is your operating system (Windows, Linux, OSX, etc.)?**

Windows 10

**What is your web server (Apache, IIS, etc.)?**

N/A

**What version of AllTube are you using?**

https://alltubedownload.net

**How did you install AllTube (with Git or with a release package)?**

N/A

**What version of PHP are you using?**

https://alltubedownload.net

**What version of Python are you using?**

https://alltubedownload.net

**What version of youtube-dl are you using?**

https://alltubedownload.net

**Do you get any PHP-related errors in your webserver's logs?**

N/A

**What is the content of your `config/config.yml` file?**

N/A

**Please provide the URL of a video that causes the issue.**

https://www.reddit.com/r/FortNiteBR/comments/8269m0/to_all_the_casual_players_out_there_on_the_wrong/

## Describe your issue

If you try to download any reddit video appers the error: requested format not available.  With youtube-dl only the download works fine...

**Comment by Rudloff** [comment]
Hello,

Reddit stores the video and audio in two different files.
youtube-dl knows how to merge the two files. On Alltube, you need to enable remux mode (by adding `remux: true` to your config file).

It is not enabled on alltubedownload.net because it is still experimental and can use a lot of RAM.

**Comment by ialexsilva** [comment]
Ok, not a good idea to enable this feature 😆

**Comment by Tyde** [comment]
I hosted it on a private server and enabled `remux: true`, but I still get 'requested format not available'. It seems like for reddit the format 'best' isnt accepted.

**Comment by Rudloff** [comment]
@Tyde Please open a new issue and fill the issue template.
