### ISSUE TITLE
Twitter Video  (Error 429)

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#175]
# New issue

## Your environment

https://alltubedownload.net

**What is your operating system (Windows, Linux, OSX, etc.)?**

Windows 10

**What is your web server (Apache, IIS, etc.)?**

N/A

**What version of AllTube are you using?**

https://alltubedownload.net

**How did you install AllTube (with Git or with a release package)?**

N/A

**What version of PHP are you using?**

https://alltubedownload.net

**What version of Python are you using?**

https://alltubedownload.net

**What version of youtube-dl are you using?**

https://alltubedownload.net

**Do you get any PHP-related errors in your webserver's logs?**

N/A

**What is the content of your `config/config.yml` file?**

N/A

**Please provide the URL of a video that causes the issue.**

https://twitter.com/NerdisticoNews/status/1006353373875056640

## Describe your issue

If you try to download any twitter video appers the error: **Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**

_I already tested with youtube-dl only and works fine..._

**Comment by Rudloff** [comment]
Hello,
I think this happens when too many people try to download Twitter videos from alltubedownload.net.
But even without this error, it would not work because Twitter only serves M3U streams and those require stream mode (which is not enabled on alltubedownload.net).
