### ISSUE TITLE
Openload

### ISSUE THREAD

**Issue by ebs111** [Rudloff/alltube#178]
first of all geat app thanks.
but it does not work with openload becuse the resolved link is ip depented is there any way to make it work? thanks alot

**Comment by Rudloff** [comment]
Hello,
If you host Alltube yourself, you can enable [stream mode](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#how-do-i-enable-streaming-videos-through-the-server) so the video is download by the server.

**Comment by Rudloff** [comment]
The video will be streamed through the server, so the browser will start downloading it as soon as the server starts getting chunks.

I hadded an Heroku option for it in fb90545d927eb732e15bdfc5aba378631fc995a9.

I'm not sure what HTML source you are talking about here.

**Comment by Rudloff** [comment]
I don't think we have a way to do this with [youtube-dl](https://rg3.github.io/youtube-dl/).

**Comment by Rudloff** [comment]
Closing since stream mode is the way to go here.
