### ISSUE TITLE
How to save file to server itself?

### ISSUE THREAD

**Issue by CofeeSap** [Rudloff/alltube#179]
# New issue

## Environment
**OS:**   Ubuntu 16.04
**Web server:**   Apache
**AllTube version:**   alltube-1.1.2
**Installation:**   Release package
**PHP version:**   PHP 7.0
**Python version:**   Python 2.7
**youtube-dl version**   2018.07.04

## Describe your issue

I'm running AllTube on my private server (i.e. no public access) and instead of downloading files to my pc I want them saved in the server itself for later  download.  After clicking 'Download' button either of 2 things may happen:

-  Video stream is set to off but 'Download' button opens a new tab video player.
-  'Save As' pop up 

## Questions:
1. Instead of above events how to set a folder in server?

2. How to view the download progress?

Thanks.

**Comment by Rudloff** [comment]
The goal of Alltube is to download videos in the browser so I won't add a way to download to the server.

There are other PHP libraries like [php-youtube-dl](https://github.com/aladdindev/php-youtube-dl) or [youtube-dl-php](https://github.com/norkunas/youtube-dl-php) that do this.
And if you need an user interface, you can try [youtube-dl-webui](https://github.com/d0u9/youtube-dl-webui).
