### ISSUE TITLE
Script Error/PHP

### ISSUE THREAD

**Issue by CMclarty** [Rudloff/alltube#183]
# New issue

## Your environment
Ubuntu 18.04, NGINX
Release package, latest available

**What version of PHP are you using?**
7.2 (have changed the sock address in nginx)

**What version of Python are you using?**
2.7 

**What version of youtube-dl are you using?**
2018.07.21

PHP Error:

`2018/07/27 10:26:39 [error] 24348#24348: *200 FastCGI sent in stderr: "Access to the script '/srv/alltube' has been denied (see security.limit_extensions)" while reading response header from upstream, client: 51.52.179.66, server: mydomain, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "amydomain", referrer: "mydomain"`

Nginx config (running as seperate vhost)

`server {
        server_name mydomain;
        listen 443 ssl;
        root /srv/alltube;
        index index.php;

        access_log /var/log/nginx/alltube.access.log;
        error_log /var/log/nginx/alltube.error.log;

        types {
                text/html html htm shtml;
                text/css css;
                text/cml xml;
                application/x-web-app-manifest+json webapp;
        }

        location ~ /\. {
                deny all;
        }

        location / {
                try_files $uri /index.php?$args;
        }

        location ~ \.php$ {
                try_files $uri /index.php?$args;

                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

                fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                fastcgi_index index.php;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_intercept_errors off;

                fastcgi_buffer_size 16k;
                fastcgi_buffers 4 16k;

                include fastcgi_params;
        }
    ssl_certificate /etc/letsencrypt/live/mydomain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain/privkey.pem; # managed by Certbot
}`

I've searched the issue, but most of the suggested fixes involve adding aspects tot he gninx conf which are already present. I don't understand where the variables in the nginx conf are supposed to come from but i'm assuming that's an issue with my understanding rather than a problem.

/srv/alltube/ is the directory where the .zip was extracted.

Grateful for any and all help!

**Comment by Rudloff** [comment]
It looks more like a Nginx issue than an Alltube issue and I don't use Nginx so I can't really help you, sorry :disappointed: 

I found this post with a similar problem so it might help you: https://askubuntu.com/questions/164627/nginx-php-fpm-access-denied-error

**Comment by Rudloff** [comment]
No answer so I'm closing.

**Comment by newcoderlife** [comment]
Just remove the `fastcgi_index index.php;` in your Nginx config file. Also set php file fix as 1. This works in my situation.

**Comment by lin-wish** [comment]
> Just remove the `fastcgi_index index.php;` in your Nginx config file. Also set php file fix as 1. This works in my situation.

Solved my problem!
