### ISSUE TITLE
Add ability to rewrite /watch?v=[YOUTUBE ID] urls

### ISSUE THREAD

**Issue by no-boot-device** [Rudloff/alltube#184]
Hi, I'd really like to have it so that I could just replace youtube.com with [my alltube instance's url] and have it automagically fill in the URL like the bookmarklet. How would I go about doing this?

Edit: Figured it out. 
```
    RewriteCond %{REQUEST_URI} ^/watch [NC]
    RewriteCond %{QUERY_STRING} ^v=(.*)
    RewriteRule (.*) https://[hostname]/video?url=https://youtube.com/watch?v=%1 [R=302,L]
```
Add this/fix it up if you want.

**Comment by Rudloff** [comment]
Thanks for the suggestion!
I added a route for this in the code: https://github.com/Rudloff/alltube/commit/b8b6180609d182c12bfc7e2be8fd0adc420bb49a
