### ISSUE TITLE
No only Audio

### ISSUE THREAD

**Issue by RedxLus** [Rudloff/alltube#185]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Linux
**What is your web server (Apache, IIS, etc.)?**
Apache
**What version of AllTube are you using?**
Ult
**How did you install AllTube (with Git or with a release package)?**
Release package
**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

**Please provide the URL of a video that causes the issue.**

## Describe your issue
No appear the option of only Audio

**Comment by Rudloff** [comment]
Please fill the full template when reporting an issue.

As explained [here](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#how-do-i-enable-audio-conversion), you need add some parameters to your config file.

**Comment by Rudloff** [comment]
No answer so I'm closing.
