### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by harisnaeemofficial** [Rudloff/alltube#190]
![screenshot 5](https://user-images.githubusercontent.com/24369463/45357034-8bf11580-b5de-11e8-95f7-be6b473003cf.png)

**Comment by harisnaeemofficial** [comment]
https://www.youtube.com/watch?v=q2gICJFG6uw This is the URL . i think youtube change the method to get signature of the video because i have created another youtube-dl project which is not getting the signature for most of the videos  .

**Comment by Rudloff** [comment]
Yes, they changed something that brokle youtube-dl. But this was fixed in a recent youtube-dl update, so I published a new Alltube release that include a more recent youtube-dl.
