### ISSUE TITLE
Stream through server

### ISSUE THREAD

**Issue by FaArIsH** [Rudloff/alltube#192]
How to Stream through server without downloading to server ?
if i try to skip the video to 10 minutes it will not do if the server has not loaded the file completely.
can you make this possible ?

**Comment by FaArIsH** [comment]
> 
> 
> Hello,
> I'm not sure I understand what you need. There is already [a stream option](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#how-do-i-enable-streaming-videos-through-the-server) that allows streaming the video through the server, but it does not let you skip to another part of the video.

i want to be able to skip to another part of the video.
and also  i  can't access directly to https://r4---sn-h557.... (youtube blocked)

look at this file
https://github.com/You2php/you2php/blob/master/stream.php
https://github.com/You2php/you2php/blob/master/downvideo.php
i used you2php to download/watch videos and it will not give me direct link of youtube (r4--) instead it gives
example.com/downvideo.php?v=nOoYG764bjI&quality=360P&name=Fancy&Format=mp4
and it also does not download to server but act like a proxy to server the video so i was able to skip part of the video

**Comment by Rudloff** [comment]
> it will not give me direct link of youtube (r4--) instead it gives
example.com/downvideo.php?v=nOoYG764bjI&quality=360P&name=Fancy&Format=mp4

This is exactly what the `stream` option of Alltube does :slightly_smiling_face:

**Comment by FaArIsH** [comment]
but why this does not let we skip parts

**Comment by Rudloff** [comment]
What do you mean exactly by "skip"?
Do you mean you want to be able to play the video directly in your browser instead of downloading it?

**Comment by FaArIsH** [comment]
yes i want to play in my browser using you2php ui here how i replace https://github.com/FaArIsH/you2php/commit/c51f4df35b5e4e2a2f4bf3d71719b4b0216f91ee
by skip i mean when watching a video i may need to skip few minutes or seconds by pulling the seek bar dot to time line. but i cannot skip to desired time lapse with this libriary except when the video is loaded to server fully

**Comment by Rudloff** [comment]
Thanks for posting your code. This is a very specific usage of Alltube and it is much easier to understand what you are doing when I can see your code.

I added support for range requests here: https://github.com/Rudloff/alltube/commit/4cbc21de464e2ffa827a3b616a45e70e67c033c2
Now you should be able to seek to another part of the video (it might be a bit slow though, because youtube-dl is called again everytime you seek).

**Comment by FaArIsH** [comment]
Thankyou. now its working great.
