### ISSUE TITLE
Alltube Behind a Nginx Reverse proxy

### ISSUE THREAD

**Issue by rvjpub** [Rudloff/alltube#196]
Thanks for this beautifull web app.

How can we use behind Reverse proxy ?

I have try lot of tips but not work;-)

Thanks for your help 

Best regards

**Comment by Rudloff** [comment]
Hello,

It should be possible to use Alltube behind a reverse proxy but I don't use Nginx so I can't really help you, sorry.
But please tell me if there are specific things I can change to make this easier.

**Comment by Rudloff** [comment]
I don't really understand what your problem is.
What exactly is not working?

**Comment by Rudloff** [comment]
No answer for a month so I'm closing this.
Feel free to reopen if you can provide additionnal information.

**Comment by Nottt** [comment]
If anyone else lands here, I can confirm you can use alltube behind a nginx reverse proxy fine... I'm using it with a nginx docker out of the box
