### ISSUE TITLE
Error Saying "Unable to extract Initial JS player signature function name"

### ISSUE THREAD

**Issue by manitaggarwal** [Rudloff/alltube#197]
# Complete Error
**ERROR: Signature extraction failed: Traceback (most recent call last): File "/app/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1192, in _decrypt_signature video_id, player_url, s File "/app/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1103, in _extract_signature_function res = self._parse_sig_js(code) File "/app/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1164, in _parse_sig_js jscode, 'Initial JS player signature function name', group='sig') File "/app/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 880, in _search_regex raise RegexNotFoundError('Unable to extract %s' % _name) youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. **

**Comment by manitaggarwal** [comment]
Sorry, I will use the template from next time.
I deployed it using your 1 click Heroku button.

URL of video
"https://www.youtube.com/watch?v=Ydp5fLbxUbk"

**Comment by Rudloff** [comment]
I can't reproduce this locally. What version of Alltube and youtubedl are you using?
(If you created your Heroku app a while ago, you probably need to update it.)

**Comment by manitaggarwal** [comment]
After redeploying it works. Thanks a lot. Is there a way the app auto updates when you commit to this repo?

**Comment by Rudloff** [comment]
Yes, you can enable [automatic deploys](https://devcenter.heroku.com/articles/github-integration#automatic-deploys).
