### ISSUE TITLE
Live streaming video has no audio

### ISSUE THREAD

**Issue by 10362227** [Rudloff/alltube#198]
https://www.youtube.com/watch?v=XxJKnDLYZz4
Live streaming video has no audio, please fix

**Comment by Rudloff** [comment]
Hello,
Please don't remove the issue template!
What version of Alltube and youtube-dl are you using? Is stream mode enabled? What format are you trying to download?

**Comment by Rudloff** [comment]
No answer so I'm closing.
Please reopen if you can provide more information.
