### ISSUE TITLE
ffmpeg in composer file gives 404 error at download

### ISSUE THREAD

**Issue by nicolass67** [Rudloff/alltube#202]
Hello, 

When building a docker image from alltube the build fails on the ffmpeg-4.0.2-static.tar.xz download. 
It gives a 404 not found.
Further it seems the builds from https://www.johnvansickle.com/ffmpeg/ changed to 4.1.  

A workaround / fix is to change the url in the compser.json file. Below what I modified to have the build ok gain : 

```
diff -Nu composer.json.save composer.json
--- composer.json.save	2018-11-20 14:14:06.464760705 +0100
+++ composer.json	2018-11-20 14:16:30.625228736 +0100
@@ -22,7 +22,7 @@
     "squizlabs/php_codesniffer": "~3.2.2",
     "phpunit/phpunit": "~6.5.2",
     "doctrine/instantiator": "~1.0.0",
-    "ffmpeg/ffmpeg": "4.0.2",
+    "ffmpeg/ffmpeg": "4.1",
     "rg3/youtube-dl": "2018.11.07",
     "heroku/heroku-buildpack-php": "*",
     "anam/phantomjs-linux-x86-binary": "~2.1.1"
@@ -50,9 +50,9 @@
       "type": "package",
       "package": {
         "name": "ffmpeg/ffmpeg",
-        "version": "4.0.2",
+        "version": "4.1",
         "dist": {
-          "url": "https://johnvansickle.com/ffmpeg/releases/ffmpeg-4.0.2-64bit-static.tar.xz",
+          "url": "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz",
           "type": "xz"
         },
         "bin": [
```

Regards,

**Comment by Rudloff** [comment]
Hello,

This was fixed on the develop branch recently: https://github.com/Rudloff/alltube/pull/201
The fix will be included in the next release.

In the mean time, develop docker images seem to build correctly: https://hub.docker.com/r/rudloff/alltube/builds/
