### ISSUE TITLE
No audio in video on custom format selections

### ISSUE THREAD

**Issue by Henrocker** [Rudloff/alltube#204]
# No audio in video on custom format selections

## My environment

**What is your operating system (Windows, Linux, OSX, etc.)?**
Debian 9 stretch

**What is your web server (Apache, IIS, etc.)?**
caddy 0.11.1

Config:

```
https://ytdl.domain.com {
        tls /etc/caddy/crt.crt /etc/caddy/key.key
        gzip {
                ext *
                level 4
        }
        fastcgi / unix:/run/php/php7.2-fpm.sock php {
                root    /etc/caddy/html/yt-dl
        }
        header / {
                Strict-Transport-Security "max-age=31536000; includeSubdomains; preload"
                X-XSS-Protection "1; mode=block;"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "SAMEORIGIN"
        }
        limits {
                header 64kb
                body 8gb
        }
        root /etc/caddy/html/yt-dl
        ext .html .htm .php
        rewrite {
                to {path} /index.php?{query}
        }
        mime {
                .html text/html
                .htm text/html
                .shtml text/html
                .css text/css
                .xml text/xml
                .webapp application/x-web-app-mainfest+json
        }
        log / /etc/caddy/logs/access.log {
                rotate_size     10
                rotate_age      14
                rotate_keep     10
                rotate_compress
}
        errors /etc/caddy/logs/error.log
        timeouts none
}
```

**What version of AllTube are you using?**
Release 1.2.4

**How did you install AllTube (with Git or with a release package)?**
Release package

**What version of PHP are you using?**
PHP Version 7.2.13-1

**What version of Python are you using?**
Python 2.7.13

**What version of youtube-dl are you using?**
2018.11.07

**Do you get any PHP-related errors in your webserver's logs?**
No

**What is the content of your `config/config.yml` file?**
```
---
# Path to your youtube-dl binary
youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: false

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: /usr/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
stream: false

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 256
```

**Please provide the URL of a video that causes the issue.**
Any YouTube video.

Example: https://r1---sn-4g5e6ne6.googlevideo.com/videoplayback?sparams=aitags,clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mip,mm,mn,ms,mv,pl,requiressl,source&requiressl=yes&ip=2a06%3A1c40%3A3%3A%3A165&pl=21&id=o-APCMgM2Ocvsn9Z79AlaLExuKARcuU3KZ4awqkvof5eAK&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&source=youtube&lmt=1545269058198284&ei=NlIjXJS3EsKM1wacs4S4Bg&c=WEB&keepalive=yes&key=cms1&gir=yes&mime=video%2Fmp4&txp=5532432&signature=2C636D545A784B288513CE2C85E9CDDFA77ABB52.562BD33163530EA281A023383EBDDAD187B5777D&clen=171686987&itag=299&expire=1545840278&fvip=1&dur=258.199&ipbits=0&ratebypass=yes&redirect_counter=1&rm=sn-i5hes7e&fexp=23763603&req_id=2f7f9d39d582a3ee&cms_redirect=yes&ipbypass=yes&mip=84.63.125.45&mm=31&mn=sn-4g5e6ne6&ms=au&mt=1545818568&mv=m

## Describe your issue
Submitting a video and selecting "Best MP4" format, it brings me to the googlevideo page where the video can be played back with sound, can be downloaded, etc. all good.
However when selecting another custom format, e.g. 1080p, I get redirected again to the googlevideo page, where the video can bee streamed in the browser, downloaded, but theres no audio.
Downloading the video did also reveal no audio.

Also tried directly changing fileformat before selecting Best MP4 beforehand. Didn't work.

Any idea?

Thank you!

**Comment by Rudloff** [comment]
Hello,
See [this FAQ entry](https://github.com/Rudloff/alltube/blob/develop/resources/FAQ.md#download-1080p-videos-from-youtube). You need to either download a lower quality or enable remux mode.

**Comment by Henrocker** [comment]
I tried remux mode now:

When inserting a video, it always converts it to mkv (highest res incl. 60 fps, if the video is 60 fps), while mkv files cannot be skipped through using the windows media player, etc.

Is it possible to remux a video into other formats such as MP4?

**Comment by Rudloff** [comment]
We use MKV because it supports multiple streams in various formats so we only have to copy the streams into an MKV file. And MP4 has various issues when writing directly to a stream so it is not the best fit here.

You should use VLC to play the video or convert the downloaded file with a tool like [HandBrake](https://handbrake.fr/).

**Comment by Henrocker** [comment]
Okay, got it, thanks
