### ISSUE TITLE
How Can I Change Name And Logo For Public Installation? 🤔

### ISSUE THREAD

**Issue by SusanneNussbaum** [Rudloff/alltube#205]
# How Can I Change Name And Logo For Public Installation? 🤔

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Linux, cPanel 76
**What is your web server (Apache, IIS, etc.)?**
Apache 2.4.37
**What version of AllTube are you using?**
1.2.4
**How did you install AllTube (with Git or with a release package)?**
release package
**What version of PHP are you using?**
7.3
**What version of Python are you using?**
not installed I suppose
**What version of youtube-dl are you using?**
no idea
**Do you get any PHP-related errors in your webserver's logs?**
no
**What is the content of your `config/config.yml` file?**
not created
**Please provide the URL of a video that causes the issue.**
all videos I tested worked 😃
## Describe your issue
You mentioned in the Readme that you wish public installations to use a different name and logo.
I would love to follow your wishes but do not know how to do so.
Can you please write a little guide?

**Comment by Rudloff** [comment]
Hello,

I might add a config variable for this in the future, but for now you need to manually replace at least:
* The logo file: https://github.com/Rudloff/alltube/blob/master/img/logo.png
* The title here: https://github.com/Rudloff/alltube/blob/4aabbd1ee34cb637436d248b67e7bcd28c61be06/templates/inc/head.tpl#L13

**Comment by Rudloff** [comment]
I added a way to change the app name but I also removed this requirement from the README.
Now that I think of it, I don't really care if other instances use the same name.
