### ISSUE TITLE
Updating youtube dl ?

### ISSUE THREAD

**Issue by nebmesemaou** [Rudloff/alltube#206]
need to update youtube-dl to 2019.01.10

can i update youtube dl version on heroku ?

**Comment by Rudloff** [comment]
Hello,

If you are using Heroku, the preferred way to update youtube-dl would be to edit `composer.json`: https://github.com/Rudloff/alltube/blob/4aabbd1ee34cb637436d248b67e7bcd28c61be06/composer.json#L45

You can also download a more recent youtube-dl any way you want and then point to it in `config/config.yml`:
```yaml
youtubedl: path/to/youtube-dl
```

**Comment by nebmesemaou** [comment]
thx
