### ISSUE TITLE
geting urls with json api not found

### ISSUE THREAD

**Issue by nebmesemaou** [Rudloff/alltube#207]
hey,

cant open urls from geting json api with some youtube videos.
also try normaly download from home page it works.
also try youtube-dl dump-json with youtube-dl.exe it works too with "--simulate --no-check-certificate --no-cache-dir --dump-json --id <videoURL>"

upgrade youtube-dl version to 2019.01.10 on heroku but nothing change

sample video: https://www.youtube.com/watch?v=aJOTlE1K90k

**Comment by Rudloff** [comment]
Hello,
Please don't remove the issue template, it gives useful information to help diagnose the problem.

What version of Alltube are you using? Do you get an error when trying to get the JSON?
I tried calling `/json?url=https://www.youtube.com/watch?v=aJOTlE1K90k` and it works for me.

**Comment by nebmesemaou** [comment]
Sorry for remove,

latest version alltube 
/json?url=https://www.youtube.com/watch?v=aJOTlE1K90k works but result urls in formats object for example format_id: 136 not open it returns 403
