### ISSUE TITLE
Ubuntu 18 && Php 7.2

### ISSUE THREAD

**Issue by bystefu** [Rudloff/alltube#209]
`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rudloff/alltube 1.2.0 requires barracudanetworks/archivestream-php ~1.0.5 -> satisfiable by barracudanetworks/archivestream-php[1.0.5, 1.0.6, 1.0.7].
    - rudloff/alltube 1.2.1 requires barracudanetworks/archivestream-php ~1.0.5 -> satisfiable by barracudanetworks/archivestream-php[1.0.5, 1.0.6, 1.0.7].
    - rudloff/alltube 1.2.2 requires barracudanetworks/archivestream-php ~1.0.5 -> satisfiable by barracudanetworks/archivestream-php[1.0.5, 1.0.6, 1.0.7].
    - rudloff/alltube 1.2.3 requires barracudanetworks/archivestream-php ~1.0.5 -> satisfiable by barracudanetworks/archivestream-php[1.0.5, 1.0.6, 1.0.7].
    - rudloff/alltube 1.2.4 requires barracudanetworks/archivestream-php ~1.0.5 -> satisfiable by barracudanetworks/archivestream-php[1.0.5, 1.0.6, 1.0.7].
    - rudloff/alltube 1.2.5 requires barracudanetworks/archivestream-php ~1.0.5 -> satisfiable by barracudanetworks/archivestream-php[1.0.5, 1.0.6, 1.0.7].
    - barracudanetworks/archivestream-php 1.0.7 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - barracudanetworks/archivestream-php 1.0.6 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - barracudanetworks/archivestream-php 1.0.5 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - Installation request for rudloff/alltube ^1.2 -> satisfiable by rudloff/alltube[1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-apcu.ini
    - /etc/php/7.2/cli/conf.d/20-apcu_bc.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
`
I don't know how i must to do., i have just apache2, without any control panel.Is a fresh vps.
Thank u !

**Comment by Rudloff** [comment]
Hello,

> the requested PHP extension gmp is missing from your system.

You need to install the php-gmp package.

**Comment by bystefu** [comment]
Fixed, thank u. If i want in php to download video or just extract mp3, it is possible?You have doc about this?
Thank u again, the method are awseome.Before that, i used youtube-dl in php with shell_exec, and was little frustrating for me.

**Comment by Rudloff** [comment]
AllTube does not handle the download.
You need to use [`getURL()`](https://alltube.surge.sh/classes/Alltube.VideoDownload.html#method_getURL) and then pass the URL to an HTTP library like [Guzzle](http://docs.guzzlephp.org/en/stable/) to get the file.
As for MP3, you can use [`getAudioStream()`](https://alltube.surge.sh/classes/Alltube.VideoDownload.html#method_getAudioStream) to get a stream and then use functions like `fget()` and `fwrite()` to write the stream to disk.

I will try to add some examples.

**Comment by Rudloff** [comment]
I added some examples that could help you:
* https://github.com/Rudloff/alltube-example-project/blob/master/download.php
* https://github.com/Rudloff/alltube-example-project/blob/master/convert.php

**Comment by bystefu** [comment]
Thank u very much, finally i did it. I have one question, i work with example from you, to download and i receive "Downloading video to /tmp/alltubeJ5mEmQ"  and "Converting MP3 to /tmp/alltubeFJm38C" , but i can't view folder "tmp" in public_html, or in linux root (/tmp/alltubeKEY). I can set custom directory for "tmp" to put files there?

**Comment by Rudloff** [comment]
I am just using a file in `/tmp` in the example because this folder is pretty much always writeable by PHP, but you can use any path you want instead:
```php
$client->request('GET', $urls[0], ['sink' => '/my/custom/path']);
```

**Comment by bystefu** [comment]
Apologize, i solved.

```
$links = $downloader->getURL($url, "best");
$client = new Client();
$client->request('GET', $links[0], ['sink' => 'downloads/'.$downloader->getFileNameWithExtension("mp4", $url, "best")]);
```

Working, but i'm not sure if is a good solution.I'm not sure that getUTRL and Filenamewithext is always be the same,maybe getURL return webm or 3gp because i request for "best",and maybe best is not mp4.And i'm  suspicious because i must to 2 request (one is get for url and another is for name and extension.).

**Comment by Rudloff** [comment]
You should not use `getFileNameWithExtension()` here; use `getFilename()` instead, it will return the filename with the correct extension.

If you are worried about multiple requests, the other solution is to use `getJSON()`, which returns a lot of information (including the URL and the filename).

**Comment by Rudloff** [comment]
No answer so I am closing this.
