### ISSUE TITLE
Improve bookmarklet

### ISSUE THREAD

**Issue by nodiscc** [Rudloff/alltube#21]

**Comment by Rudloff** [comment]
Hello,

You do have a bookmarklet in the footer: https://github.com/Rudloff/alltube/blob/master/templates/footer.tpl#L18

**Comment by nodiscc** [comment]
Right, I see it now; Maybe it could be made more visible? Move it below `See all supported websites`, styled as a button, like

```
Drag this to your bookmarks bar:
[↓ Download with Alltube]
```

Currently the bookmarklet just reads `Bookmarklet` in your bookmarks bar.

**Comment by Rudloff** [comment]
Yes, the bookmarklet could certainly be improved.
I don't have time to work on this, but feel free to do a pull request.
