### ISSUE TITLE
Crunchyroll

### ISSUE THREAD

**Issue by louanbastos** [Rudloff/alltube#211]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

**Please provide the URL of a video that causes the issue.**

## Describe your issue

I cant download crunchyroll files and subtitles :/

**Comment by Rudloff** [comment]
Hello,
Please fill the issue template.
I will at least need the URL of the video and what error Alltube displays.

**Comment by Rudloff** [comment]
No answer, so I'm closing.
