### ISSUE TITLE
Allow the user to decide whether or not to stream through the server

### ISSUE THREAD

**Issue by jeffli678** [Rudloff/alltube#218]
I think it would be better if the user can have a chance to decide if s/he wants to stream the video through the server. Because sometimes it is faster to download directly, and sometimes it is faster to stream through the server. Of course, this should only be allowed if the server allows the user to stream the video in the first place. 

A viable way to implement this is to offer a switch in the HTML UI -- a dropdown or something?

By the way, I really like this project. I need it and thought about writing one. And I found you already did the job. Thx!

**Comment by Rudloff** [comment]
Thanks for the suggestion, I added a checkbox for that.
