### ISSUE TITLE
Show an URL input field on download pages

### ISSUE THREAD

**Issue by nodiscc** [Rudloff/alltube#22]
Currently there is no download url field/button on download pages (`https://all.tube.example/api.php?url=...`). Adding one at the bottom (top?) of the page would save using the back button each time you want to enter another URL in an existing alltube browser tab.

**Comment by Rudloff** [comment]
I have been reluctant to implement this because I don't want to clutter the layout and I didn't find a way to do this that's not potentially confusing for new users. So I'm closing this ticket.
But please reopen if you can provide mockups that we can discuss.
