### ISSUE TITLE
Error 403 Access Denied

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#222]
# Error 403 Access Denied

## Describe your issue

When i try to download this https://www.youtube.com/watch?v=ZB9UvUJL_lE on https://alltubedownload.net i get the error 403

**Comment by ialexsilva** [comment]
@Rudloff

**Comment by Rudloff** [comment]
Yes, Vevo videos have an IP address check (https://github.com/Rudloff/alltube/issues/56). Workarounds for this are explained here: https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#i-cant-download-videos-from-some-websites-eg-dailymotion

I will add this specific case to the FAQ.
