### ISSUE TITLE
Add more generic formats

### ISSUE THREAD

**Issue by Nottt** [Rudloff/alltube#223]
## Your environment

**What is your operating system (Windows, Linux, OSX, etc.)?** Ubuntu 18;04

I'm using `rudloff/alltube:latest` so I'm running everything as the default for the docker

**What is the content of your `config/config.yml` file?**

```
---
# Path to your youtube-dl binary
youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, vp9, opus, wav]

# Path to your avconv or ffmpeg binary
avconv: vendor/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
stream: false

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 256

# App name
appName: AllTube Download
```

## Describe your issue

I'd like to add more generic formats, either as a option in the `config.yml` file or having it added as defaults.

I propose a `best audio` generic format, that would be `.opus` files of highest bitrate available usually.

And maybe removing `Best (mp4)` when remux is enabled and rename remux to just  `Best video & audio `

**Comment by Rudloff** [comment]
Hello,

Thanks for the suggestion.
I added an (experimental) option for that: https://github.com/Rudloff/alltube/blob/develop/resources/FAQ.md#use-other-youtube-dl-generic-formats-eg-bestaudio

However, I will not enable `bestaudio` by default because it does not work on a lot of websites.

> And maybe removing Best (mp4) when remux is enabled and rename remux to just Best video & audio 

I think we should keep it because it can still be useful (for example, it is usually much faster than remuxing: https://github.com/Rudloff/alltube/issues/221).
