### ISSUE TITLE
Move the Video class to a separate Composer package

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/alltube#224]
This could be useful for people who want to use it without pulling all of our dependencies (Slim, etc.).
But I am not sure if real people want to use it that way.

**Comment by Rudloff** [comment]
There does not seem to be much interest for this.

**Comment by sulemankhann** [comment]
that would be great because what if people need in other PHP framework to use it like i am using it in laravel 6 and getting Symfony  conflicts.

**Comment by Rudloff** [comment]
https://github.com/Rudloff/alltube/issues/268 would be another reason to use a separate package.

**Comment by Rudloff** [comment]
The library is now available here: https://github.com/Rudloff/alltube-library
