### ISSUE TITLE
Audio m4a

### ISSUE THREAD

**Issue by next2non** [Rudloff/alltube#227]
1st it seems you have removed the mp3 download from you site (don’t see it any more) any reasons? 

2nd the main issue is when I download m4a audio from YouTube site, the audio length is double the actual. For example if the audio file is for 2min the m4a download will show 4min where as the extra 2min is just silent audio (no noise). Can this issue be fixed? 

Tested on Youtube so far

Please answer these questions when reporting a new issue:

Downloading the file on my iPhone iOS 12 while using you website to get the download links.

Regards

**Comment by Rudloff** [comment]
Hello,
Please don't remove the issue template.

> 1st it seems you have removed the mp3 download from you site (don’t see it any more) any reasons?

It was using too much resources on the server.

> 2nd the main issue is when I download m4a audio from YouTube site, the audio length is double the actual.

Please provide the URL of the video you are trying to download.

**Comment by next2non** [comment]
Hi,

So far any YouTube link I try to convert to M4a has this issue, for example try this please 

https://m.youtube.com/watch?v=pH4q6OXhZgU

**Comment by Rudloff** [comment]
How are you "converting" it? I tried selecting the M4A / Dash audio format and the audio file plays correctly.
Could this be an issue with your audio player?

**Comment by next2non** [comment]
It's really strange. I have tested no on my iPhone and Mac. if I use my iPhone (open your website and paste the youtube link) and download through Safari app, Firefox app, Chrome app, Document app, Goodreader app and iCab mobile app all of them give me the same issue of extra time with no sound. 

On my Mac Safari does the same thing (extra time with no sound), but when I use Firefox on the Mac it gives the correct time for the m4a. So not sure why all give incorrect m4a time except for Firefox on the Mac.

**Comment by Rudloff** [comment]
If it does not work on iOS/Safari, then it is probably a WebKit bug.
Anyway, it is probably not caused by Alltube, since we don't modify the M4A file, we download it as is.
