### ISSUE TITLE
Can't download videos or convert to mp3, 403 from Google

### ISSUE THREAD

**Issue by hbh7** [Rudloff/alltube#228]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?** Ubuntu 18.10, also tried alltubedownload.net

**What is your web server (Apache, IIS, etc.)?** Apache

**What version of AllTube are you using?** Just ran update

**How did you install AllTube (with Git or with a release package)?** Git

**What version of PHP are you using?** 7.2.17

**What version of Python are you using?** 2.7.16

**What version of youtube-dl are you using?** 2019.04.24

**Do you get any PHP-related errors in your webserver's logs?** No

**What is the content of your `config/config.yml` file?** 

```
cat config/config.yml
---
# Path to your youtube-dl binary
#youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py
youtubedl: /usr/local/bin/youtube-dl

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav, flac, mp4]

# Path to your avconv or ffmpeg binary
avconv: /usr/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
stream: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 192
```

**Please provide the URL of a video that causes the issue.** https://www.youtube.com/watch?v=rNYaw4EJpZo

## Describe your issue
I put in a video url and hit download and I get sent to a 403 page from Google. "Access to r5---sn-aigzrn7z.googlevideo.com was denied You don't have authorization to view this page.
HTTP ERROR 403"
Happens with or without convert to mp3 option.

**Comment by hbh7** [comment]
Nevermind, I updated youtube-dl and things seem to be better now. I guess it's now just an issue with alltubedownload.net

**Comment by Rudloff** [comment]
Hello,
Thanks for the report. I was just working on releasing a new release with an updated youtube-dl in order to fix this :stuck_out_tongue:

**Comment by hbh7** [comment]
Lol sounds good, glad I'm not going crazy. Thanks!
