### ISSUE TITLE
npm WARN cannot run in wd alltube@0.2.1

### ISSUE THREAD

**Issue by kevin25** [Rudloff/alltube#23]
Hello,

I got the error: 
npm WARN cannot run in wd alltube@0.2.1 ./node_modules/grunt-cli/bin/grunt;

When i used the command line:
npm install

I also got the error:

PHP message: PHP Fatal error:  require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/php55/lib/php') 

How can i fix it? 

Thanks!

**Comment by Rudloff** [comment]
The setup was changed a little recently. I updated the README (https://github.com/Rudloff/alltube/commit/641f107b372e14bd7fae9f7b62ac3b2065544247).

Can you please install [Composer](https://getcomposer.org/) and run this:
```
composer install
```
It should fix the PHP error.

The npm error looks like you are trying to run npm with root privileges.
You should run it with a normal user or run ```npm install --unsafe-perm``` (not a good practice).

**Comment by kevin25** [comment]
You're right. Thanks. It works for me.

**Comment by kevin25** [comment]
I have to create the templates_c and give it full permissions. You should add it to your document too. Thanks!

**Comment by Rudloff** [comment]
You are right, thanks!
I added the folder to the repository and updated the README: https://github.com/Rudloff/alltube/commit/1f169228fc0c8600eca33b5b9d35ccdb74170650
