### ISSUE TITLE
Why doesn’t AllTube auto update YouTube-DL?

### ISSUE THREAD

**Issue by mattjis** [Rudloff/alltube#234]
There’s a new version of YouTube-DL that fixes Soundcloud.

Why doesn’t AllTube use the “—update” argument and update itself automatically?

**Comment by Rudloff** [comment]
Hello,
This would require additional work with a cron task or something similar and would add new requirements to the hosting.
Also, I prefer to check that a new version does not break compatibility before using it.

However, if you host your own Alltube instance, you are free to install/update youtube-dl the way you want.

**Comment by mattjis** [comment]
Well the “—update” argument could be applied to all YouTube-DL commands instead of a cron task, but I see where you’re coming from.

**Comment by mattjis** [comment]
Would you be able to update it to the latest YouTube-DL? Soundcloud is currently broken. Thanks

**Comment by Rudloff** [comment]
> Well the “—update” argument could be applied to all YouTube-DL commands instead of a cron task

This would make the request very slow for the person getting the update.

> Would you be able to update it to the latest YouTube-DL? 

Done :slightly_smiling_face:
