### ISSUE TITLE
Slower download mp3 main page

### ISSUE THREAD

**Issue by TheNickSkater** [Rudloff/alltube#235]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?** Linux (Ubuntu Server 16.04)

**What is your web server (Apache, IIS, etc.)?** Apache2

**What version of AllTube are you using?** Newest (2.0.4)

**How did you install AllTube (with Git or with a release package)?** Release package

**What version of PHP are you using?** 7.2

**What version of Python are you using?** 2.7.12

**What version of youtube-dl are you using?** The one included?

**Do you get any PHP-related errors in your webserver's logs?** No

**What is the content of your `config/config.yml` file?** https://pastebin.com/s9GAxsbj

**Please provide the URL of a video that causes the issue.** Any Video (at least tested with multiple youtube videos)

## Describe your issue

So, when I want to convert a Video to MP3 using this feature on the main page of alltube (this: http://prntscr.com/oaqt03) the download speed is very slow.. (Like 500KB or lower). But when I use the other conversion thing (this: http://prntscr.com/oaqtnt) then the download is pretty fast.

Is this ment to be like that? Can this be changed somehow?

Thanks!

**Comment by Rudloff** [comment]
Hello,
This is probably caused by https://github.com/Rudloff/alltube/issues/229 (and the fact that both methods don't use the same source format).

**Comment by TheNickSkater** [comment]
> Hello,
> This is probably caused by #229 (and the fact that both methods don't use the same source format).

Oh ok. Well, is it possible to let it use the same methode? Because it would be quiet nice.

**Comment by Rudloff** [comment]
Custom conversion uses a video format as the source (because you could be converting to a video format) whereas audio conversion uses an audio file as the source.
Audio formats seem to always be throttled so what should faster ends up being slower.

I don't want to change the source format for audio conversion because it makes no sense to download a full video file only to get the audio, when an audio alternative is available.

The best solution would be to work around Youtube throttling. (We already started some work on this in https://github.com/Rudloff/alltube/issues/217.)

**Comment by TheNickSkater** [comment]
> Custom conversion uses a video format as the source (because you could be converting to a video format) whereas audio conversion uses an audio file as the source.
> Audio formats seem to always be throttled so what should faster ends up being slower.
> 
> I don't want to change the source format for audio conversion because it makes no sense to download a full video file only to get the audio, when an audio alternative is available.
> 
> The best solution would be to work around Youtube throttling. (We already started some work on this in #217.)

Ah okay, so this may get better in the future?

Either way, thanks for the info!
