### ISSUE TITLE
i try install at heroku...Application error

### ISSUE THREAD

**Issue by bhoeyong** [Rudloff/alltube#238]
i try install at heroku...Application error

**Comment by Rudloff** [comment]
Hello,
I can't help you with so little information.
Do you at least have an exact error message to provide?

**Comment by bhoeyong** [comment]
Hi bro..U try install at heroku...Will know error problem..

**Comment by Rudloff** [comment]
I can't magically guess what that error is if you do not copy it here.
https://alltubedownload.net/ runs on Heroku and I did not get any error when deploying f33e938bd5a2e4700060b753bb6696e405c98cfe.

**Comment by bhoeyong** [comment]
Morning bro...Maybe is free version problem? After work I try copy error to
u..thanks

**Comment by Rudloff** [comment]
Any news on this error?

**Comment by yassineim** [comment]
@Rudloff Here is what I get:
```

-----> Installing dependencies

       Installing node modules (yarn.lock)

       yarn install v1.19.1

       [1/4] Resolving packages...

       [2/4] Fetching packages...

       [3/4] Linking dependencies...

       warning " > grunt-phpdocumentor@0.4.1" has incorrect peer dependency "grunt@~0.4.1".

       [4/4] Building fresh packages...

       warning Error running install script for optional dependency: "/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/iltorb: Command failed.

       Exit code: 1

       Command: detect-libc prebuild-install || node-gyp rebuild

       Arguments: 

       Directory: /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/iltorb

       Output:

       gyp ERR! configure error 

       gyp ERR! stack Error: Can't find Python executable \"/app/.heroku/python/bin/python\", you can set the PYTHON env variable.

       gyp ERR! stack     at PythonFinder.failNoPython (/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/node-gyp/lib/configure.js:484:19)

       gyp ERR! stack     at PythonFinder.<anonymous> (/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/node-gyp/lib/configure.js:406:16)

       gyp ERR! stack     at F (/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/which/which.js:68:16)

       gyp ERR! stack     at E (/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/which/which.js:80:29)

       gyp ERR! stack     at /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/which/which.js:89:16

       gyp ERR! stack     at /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/isexe/index.js:42:5

       gyp ERR! stack     at /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/isexe/mode.js:8:5

       gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)

       gyp ERR! System Linux 4.4.0-1048-aws

       gyp ERR! command \"/tmp/build_120c4e514904701233d3b3de90f84773/.heroku/node/bin/node\" \"/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/iltorb/node_modules/.bin/node-gyp\" \"rebuild\"

       gyp ERR! cwd /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/iltorb

       gyp ERR! node -v v12.13.0

       gyp ERR! node-gyp -v v3.8.0

       gyp ERR! not ok"

       info This module is OPTIONAL, you can safely ignore this error

       $ grunt

       Running "cssmin:combine" (cssmin) task

       >> 1 file created. 12.53 kB → 9.89 kB

       

       Running "potomo:dist" (potomo) task

       >> Total compiled 6 ".mo" files.

       

       Running "phpdocumentor:doc" (phpdocumentor) task

       php "/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/grunt-phpdocumentor/bin/phpDocumentor.phar" --target=docs --directory=classes/,controllers/,tests/>> The 'php -v' command returned the error code '127' !

       >> Please check that PHP CLI is available.

       Error: Command failed: php -v

       /bin/sh: 1: php: not found

       

       /bin/sh: 1: php: not found

       

       Warning: Task "phpdocumentor:doc" failed. Use --force to continue.

       

       Aborted due to warnings.

       error Command failed with exit code 3.

       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

-----> Build failed

       

       We're sorry this build is failing! You can troubleshoot common issues here:

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       

       Some possible problems:

       

       - Node version not specified in package.json

         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

       

       Love,

       Heroku

       

 !     Push rejected, failed to compile Node.js app.

 !     Push failed

```

**Comment by jason123santa** [comment]
> @Rudloff Here is what I get:
> 
> ```
> -----> Installing dependencies
>        Installing node modules (yarn.lock)
>        yarn install v1.19.1
>        [1/4] Resolving packages...
>        [2/4] Fetching packages...
>        [3/4] Linking dependencies...
>        warning " > grunt-phpdocumentor@0.4.1" has incorrect peer dependency "grunt@~0.4.1".
>        [4/4] Building fresh packages...
>        warning Error running install script for optional dependency: "/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/iltorb: Command failed.
>        Exit code: 1
>        Command: detect-libc prebuild-install || node-gyp rebuild
>        Arguments: 
>        Directory: /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/iltorb
>        Output:
>        gyp ERR! configure error 
>        gyp ERR! stack Error: Can't find Python executable \"/app/.heroku/python/bin/python\", you can set the PYTHON env variable.
>        gyp ERR! stack     at PythonFinder.failNoPython (/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/node-gyp/lib/configure.js:484:19)
>        gyp ERR! stack     at PythonFinder.<anonymous> (/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/node-gyp/lib/configure.js:406:16)
>        gyp ERR! stack     at F (/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/which/which.js:68:16)
>        gyp ERR! stack     at E (/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/which/which.js:80:29)
>        gyp ERR! stack     at /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/which/which.js:89:16
>        gyp ERR! stack     at /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/isexe/index.js:42:5
>        gyp ERR! stack     at /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/isexe/mode.js:8:5
>        gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
>        gyp ERR! System Linux 4.4.0-1048-aws
>        gyp ERR! command \"/tmp/build_120c4e514904701233d3b3de90f84773/.heroku/node/bin/node\" \"/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/iltorb/node_modules/.bin/node-gyp\" \"rebuild\"
>        gyp ERR! cwd /tmp/build_120c4e514904701233d3b3de90f84773/node_modules/iltorb
>        gyp ERR! node -v v12.13.0
>        gyp ERR! node-gyp -v v3.8.0
>        gyp ERR! not ok"
>        info This module is OPTIONAL, you can safely ignore this error
>        $ grunt
>        Running "cssmin:combine" (cssmin) task
>        >> 1 file created. 12.53 kB → 9.89 kB
>        
>        Running "potomo:dist" (potomo) task
>        >> Total compiled 6 ".mo" files.
>        
>        Running "phpdocumentor:doc" (phpdocumentor) task
>        php "/tmp/build_120c4e514904701233d3b3de90f84773/node_modules/grunt-phpdocumentor/bin/phpDocumentor.phar" --target=docs --directory=classes/,controllers/,tests/>> The 'php -v' command returned the error code '127' !
>        >> Please check that PHP CLI is available.
>        Error: Command failed: php -v
>        /bin/sh: 1: php: not found
>        
>        /bin/sh: 1: php: not found
>        
>        Warning: Task "phpdocumentor:doc" failed.� Use --force to continue.
>        
>        Aborted due to warnings.
>        error Command failed with exit code 3.
>        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> -----> Build failed
>        
>        We're sorry this build is failing! You can troubleshoot common issues here:
>        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
>        
>        Some possible problems:
>        
>        - Node version not specified in package.json
>          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
>        
>        Love,
>        Heroku
>        
>  !     Push rejected, failed to compile Node.js app.
>  !     Push failed
> ```

I also get that

**Comment by Rudloff** [comment]
@jason123santa @yassineim This looks like https://github.com/Rudloff/alltube/issues/243. It is fixed on the develop branch and will be in the next release.

@bhoeyong No answer, so I am closing.
