### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Cr0iX** [Rudloff/alltube#239]
Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Centos 7

**What is your web server (Apache, IIS, etc.)?**
Apache

**What version of AllTube are you using?**
Newest with git pull

**How did you install AllTube (with Git or with a release package)?**
Git pull

**What version of PHP are you using?**
PHP 7.3.9 

**What version of Python are you using?**
Python 2.7.5

**What version of youtube-dl are you using?**
Newest downloaded with curl (2019.08.13)

**Do you get any PHP-related errors in your webserver's logs?**
None?

**What is the content of your `config/config.yml` file?**
---
# Path to your youtube-dl binary
youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: false

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: /usr/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
stream: false

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 320

# App name
appName: MySiteName

**Please provide the URL of a video that causes the issue.**
Any youtube url, ive used: https://www.youtube.com/watch?v=tuyiWx1NRDo
But works if using youtube-dl cli

## Describe your issue
An error occurred
Please check the URL of your video.
ERROR: Signature extraction failed: Traceback (most recent call last): File "/var/www/DIR/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature video_id, player_url, s File "/var/www/DIR/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function res = self._parse_sig_js(code) File "/var/www/DIR/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js jscode, 'Initial JS player signature function name', group='sig') File "/var/www/DIR/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex raise RegexNotFoundError('Unable to extract %s' % _name) RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. (caused by RegexNotFoundError(u'Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Rudloff** [comment]
Hello,

I updated youtube-dl on the develop branch: 2dbcdbeb688b733801beee3d1d4e68b477cbf063

>  Newest downloaded with curl (2019.08.13)

If you want to use the version downloaded with curl, you have to set the `youtubedl` option in `config.yml` accordingly. Here it is using the version installed by Composer.
