### ISSUE TITLE
Get the real name of video 

### ISSUE THREAD

**Issue by kevin25** [Rudloff/alltube#24]
Is there any way to get the real name of the video when people download it? 

Best (mp4)
nondash-171 - audio only (DASH audio) (webm)
nondash-140 - audio only (DASH audio) (m4a)
nondash-278 - 144p (DASH video) (webm)
nondash-160 - 144p (DASH video) (mp4)
nondash-242 - 240p (DASH video) (webm)
nondash-133 - 240p (DASH video) (mp4)
nondash-243 - 360p (DASH video) (webm)

When i downloaded mp4 for example, i got the file named videoplayback.mp4 instead of the video name.mp4.

**Comment by Rudloff** [comment]
There is no easy solution for this.
We used to stream the video through the server and rename it, but this unnecessarily slowed the downloads down.
Now we have [download](https://developer.mozilla.org/fr/docs/Web/HTML/Element/a#attr-download) attributes on links but most browsers only use it on links to the same domain.

**Comment by Rudloff** [comment]
The `feature/stream` branch has been merged into `develop` and you can now enable this functionality by adding `stream: true` to your `config.yml` file.
