### ISSUE TITLE
youtube-dl is currently not working with YouTube URLs

### ISSUE THREAD

**Issue by hifihedgehog** [Rudloff/alltube#240]
This issue appears to impact all current public releases of youtube-dl and all programs in existence that rely on its current dependencies. Awaiting a new release when the fix comes for youtube-dl and that is integrated here.

**Comment by Rudloff** [comment]
Hello,

Is there a youtube-dl issue for this?

**Comment by hifihedgehog** [comment]
Yes, there is and it has been just fixed, within an hour flat of reporting it. They were right on top of it. Here is the emergency release:

https://github.com/ytdl-org/youtube-dl/releases/tag/2019.09.12

**Comment by Rudloff** [comment]
Thanks for the report. I updated youtube-dl on the develop branch: 2dbcdbeb688b733801beee3d1d4e68b477cbf063
