### ISSUE TITLE
How to hide sites that host inappropriate content?

### ISSUE THREAD

**Issue by hifihedgehog** [Rudloff/alltube#241]
I would like to use this but not have the link to the list of supports sites including the names of sites hosting inappropriate content.  Is there an easy way to do this without relying on the webpage hosted from the project's main site?

**Comment by Rudloff** [comment]
Unfortunately, `youtube-dl --list-extractors` does not give us any information about the websites so we have no way to hide some of them.

**Comment by hifihedgehog** [comment]
Is there a way I can manually disable specific extractors or only allow certain extractors?

**Comment by Rudloff** [comment]
I don't think youtube-dl provides a way to do that.
We could add a domain-based blacklist to Alltube but it would be quite tedious.

A quick and dirty solution for you would be to edit this file: https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/extractors.py

**Comment by Rudloff** [comment]
I just discovered that youtube-dl provides a `--age-limit` option that hides some extractors, so I think we could use that.

**Comment by Rudloff** [comment]
@hifihedgehog You can add something like this to `config.yml`

```yaml
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist
    - --age-limit
    - 12
```
(The last 2 lines are important. The rest are the default options used by Alltube.)

It should disable most porn websites. (You can of course adjust the age according to your needs.)

**Comment by Rudloff** [comment]
No answer so I'm closing.

**Comment by javadfk** [comment]
Hi,
--age-limit not work!
use this link for test: https://www.youtube.com/watch?v=zNrF_V_VgyA

**Comment by javadfk** [comment]
Worked, 
finds details but not show/download video.
