### ISSUE TITLE
Cannot deploy to heroku.

### ISSUE THREAD

**Issue by CookieCoder15** [Rudloff/alltube#243]
### Hi, I can't deploy to heroku using the deploy button. Here is the full build log:

-----> Locale app detected
=== Updating or installing language-pack-en-base
Get:1 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease [46.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages [274 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [777 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [680 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,295 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [975 kB]
Fetched 17.2 MB in 7s (2,481 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 33 not upgraded.
Need to get 419 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 language-pack-en-base all 1:18.04+20180712 [419 kB]
Fetched 419 kB in 1s (603 kB/s)
Download complete and in download only mode
=== Updating or installing language-pack-fr-base
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
The following additional packages will be installed:
  language-pack-fr
The following NEW packages will be installed:
  language-pack-fr language-pack-fr-base
0 upgraded, 2 newly installed, 0 to remove and 33 not upgraded.
Need to get 4,612 kB of archives.
After this operation, 20.7 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 language-pack-fr-base all 1:18.04+20180712 [2,875 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 language-pack-fr all 1:18.04+20190718 [1,738 kB]
Fetched 4,612 kB in 2s (2,516 kB/s)
Download complete and in download only mode
=== Updating or installing language-pack-es-base
Hit:1 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
The following additional packages will be installed:
  language-pack-es
The following NEW packages will be installed:
  language-pack-es language-pack-es-base
0 upgraded, 2 newly installed, 0 to remove and 33 not upgraded.
Need to get 2,847 kB of archives.
After this operation, 12.4 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 language-pack-es-base all 1:18.04+20180712 [2,845 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 language-pack-es all 1:18.04+20180712 [1,904 B]
Fetched 2,847 kB in 1s (2,478 kB/s)
Download complete and in download only mode
=== Updating or installing language-pack-pt-base
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
The following additional packages will be installed:
  language-pack-pt
The following NEW packages will be installed:
  language-pack-pt language-pack-pt-base
0 upgraded, 2 newly installed, 0 to remove and 33 not upgraded.
Need to get 2,621 kB of archives.
After this operation, 12.7 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 language-pack-pt-base all 1:18.04+20180712 [2,619 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 language-pack-pt all 1:18.04+20180712 [1,900 B]
Fetched 2,621 kB in 1s (2,312 kB/s)
Download complete and in download only mode
=== Updating or installing language-pack-de-base
Hit:1 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
The following additional packages will be installed:
  language-pack-de
The following NEW packages will be installed:
  language-pack-de language-pack-de-base
0 upgraded, 2 newly installed, 0 to remove and 33 not upgraded.
Need to get 5,008 kB of archives.
After this operation, 21.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 language-pack-de-base all 1:18.04+20180712 [2,972 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 language-pack-de all 1:18.04+20190117 [2,036 kB]
Fetched 5,008 kB in 2s (2,716 kB/s)
Download complete and in download only mode
=== Unpacking and configuring all locales
-----> Gettext library app detected
-----> Installing gettext...
      gettext (GNU gettext-tools) 0.19.3
       Installing profile file...
       Exporting path for subsequent buildpacks...
-----> done in /app/.heroku/gettext
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 10.x...
       Downloading and installing node 10.16.3...
       Using default npm version: 6.9.0
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.19.1)...
       Installed yarn 1.19.1
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.19.1
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       warning " > grunt-phpdocumentor@0.4.1" has incorrect peer dependency "grunt@~0.4.1".
       [4/4] Building fresh packages...
       warning Error running install script for optional dependency: "/tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/iltorb: Command failed.
       Exit code: 1
       Command: detect-libc prebuild-install || node-gyp rebuild
       Arguments: 
       Directory: /tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/iltorb
       Output:
       gyp ERR! configure error 
       gyp ERR! stack Error: Can't find Python executable \"/app/.heroku/python/bin/python\", you can set the PYTHON env variable.
       gyp ERR! stack     at PythonFinder.failNoPython (/tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/node-gyp/lib/configure.js:484:19)
       gyp ERR! stack     at PythonFinder.<anonymous> (/tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/node-gyp/lib/configure.js:406:16)
       gyp ERR! stack     at F (/tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/which/which.js:68:16)
       gyp ERR! stack     at E (/tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/which/which.js:80:29)
       gyp ERR! stack     at /tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/which/which.js:89:16
       gyp ERR! stack     at /tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/isexe/index.js:42:5
       gyp ERR! stack     at /tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/isexe/mode.js:8:5
       gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
       gyp ERR! System Linux 4.4.0-1048-aws
       gyp ERR! command \"/tmp/build_7e0864e26fc7116d8e67f3a3737eea32/.heroku/node/bin/node\" \"/tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/iltorb/node_modules/.bin/node-gyp\" \"rebuild\"
       gyp ERR! cwd /tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/iltorb
       gyp ERR! node -v v10.16.3
       gyp ERR! node-gyp -v v3.8.0
       gyp ERR! not ok"
       info This module is OPTIONAL, you can safely ignore this error
       $ grunt
       Running "cssmin:combine" (cssmin) task
       >> 1 file created. 12.53 kB → 9.89 kB
       
       Running "potomo:dist" (potomo) task
       >> Total compiled 6 ".mo" files.
       
       Running "phpdocumentor:doc" (phpdocumentor) task
       php "/tmp/build_7e0864e26fc7116d8e67f3a3737eea32/node_modules/grunt-phpdocumentor/bin/phpDocumentor.phar" --target=docs --directory=classes/,controllers/,tests/>> The 'php -v' command returned the error code '127' !
       >> Please check that PHP CLI is available.
       Error: Command failed: php -v
       /bin/sh: 1: php: not found
       
       /bin/sh: 1: php: not found
       
       Warning: Task "phpdocumentor:doc" failed. Use --force to continue.
       
       Aborted due to warnings.
       error Command failed with exit code 3.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by Rudloff** [comment]
Thanks for the report. It is now fixed on the develop branch.

**Comment by nk932714** [comment]
heroku showing me error when opening the app,
Deployment is successful but app is crashing 
![image](https://user-images.githubusercontent.com/29853208/71620506-5b2c5980-2bf0-11ea-8561-ef010d18c9e1.png)

``` 

 !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.

			Detected buildpacks: Python,PHP

			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order

-----> Python app detected

-----> Installing python-2.7.17

-----> Installing pip

-----> Installing SQLite3

Sqlite3 successfully installed.

-----> Installing requirements with pip

       You must give at least one requirement to install (see "pip help install")

-----> Discovering process types

       Procfile declares types -> web

-----> Compressing...

       Done: 30.1M

-----> Launching...

       Released v3

       https://foo.herokuapp.com/ deployed to Heroku

 ```

**Comment by Rudloff** [comment]
As your screenshot suggests, you should have a look at the logs to see if you get any error message.

**Comment by nk932714** [comment]
Thanks i got the error, just using php and python build-packs the deployment is successful with no error,
