### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by dandud100** [Rudloff/alltube#244]
I dont see any option where i can change the language, how do i do this? @Rudloff

**Comment by Rudloff** [comment]
Hello,
Please don't remove the issue template.
If you are using https://alltubedownload.net/, this is a known issue: https://github.com/Rudloff/alltube/issues/216

**Comment by kalak-sudo** [comment]
I am using Alltube with "Yunohost", and I see the folder "i18n" with some locales, but I can't find the way to make any of them the default language. 

How can I do it??? 

Thanks in advanced,

Kalak

**Comment by Rudloff** [comment]
Hello @kalak-sudo,

The locales need to be enabled on your server. If you have SSH access, you can run `locale -a` to see which locales are enabled.

Once the required locales are enabled, Alltube provides two ways of switching locale :
* It will try to detect the locale used by the browser.
* If several locales are available, it will display a menu in the top-left corner of the page.

**Comment by kalak-sudo** [comment]
I finally made it using:

`sudo dpkg-reconfigure locales`

And selecting my language. 

Thanks in advanced!

**Comment by Rudloff** [comment]
Starting with 2.1.0, locales don't need to installed on the OS anymore.
