### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by Ockaie** [Rudloff/alltube#248]
I received the following error message:
`
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by Rudloff** [comment]
There is nothing we can do so I am closing.
