### ISSUE TITLE
Mp3

### ISSUE THREAD

**Issue by next2non** [Rudloff/alltube#25]
Hi,

When I select MP3 only it takes me to streaming and won't give me a link to download as it does with video. How can I fix this?

**Comment by Rudloff** [comment]
That's because when you use the *Audio only* option, it doesn't download an actual existing MP3 file, but rather converts the media on the fly and directly streams it to the browser.
I'm curious, why do you need a link for?

**Comment by next2non** [comment]
I use the links to download the videos as well audio to my iPhone directly. Since alltube uses YouTube-dl which allows to download from quite a big list of sites, it is great, but wish I could get a download links where I can download them to my iPhone using a download app from the apple store.

**Comment by Rudloff** [comment]
This is a pretty specific use case so I won't change of the audio download works, but you can use this bookmarklet to get the URL: https://gist.github.com/Rudloff/b93937279fa36226300c
(Create a new bookmark in your browser with the code in the Gist as the URL.
You can then click on it to get the URL.)
