### ISSUE TITLE
Can we get a Youtube-DL update?

### ISSUE THREAD

**Issue by mattjis** [Rudloff/alltube#253]
Soundcloud links no longer work.

**Comment by Rudloff** [comment]
I updated it on the develop branch: https://github.com/Rudloff/alltube/commit/b3294b3dbc6d8164a3358707a4dfef5a05f8eee5

**Comment by mattjis** [comment]
Soundcloud still doesn’t work @Rudloff :(

**Comment by Rudloff** [comment]
What version of Alltube are you using?
And can you please provide the URL of the page you are trying to download from?

**Comment by mattjis** [comment]
@Rudloff I’m using your website.

And here’s a link: https://soundcloud.com/perkopair/stutter-3

**Comment by Rudloff** [comment]
The fix is only on the develop branch for now.
This should be fixed in the next release.
