### ISSUE TITLE
alltubedownload.net gives error no matter what video I'm trying to download

### ISSUE THREAD

**Issue by developerfromjokela** [Rudloff/alltube#254]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Linux in Firefox, accessing https://alltubedownload.net

## Describe your issue
**alltubedownload.net converter:**

So, I get error no matter what video I put there:

"ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

Please fix as soon as possible.

**Comment by Rudloff** [comment]
> Too Many Requests

As the error said, the server was blacklisted for making too many requests to the video website. (I assume this is a YouTube video ?)
There is nothing we can do about it. People should host their own instance of Alltube if we want to work around this.
