### ISSUE TITLE
Add option to stream via server OR not

### ISSUE THREAD

**Issue by nahventure** [Rudloff/alltube#255]
# New issue
I'd like to see an option to where I can enable server streaming in the config but not enforce it by default, basically allow the client to choose. Config option would have an added "default option" in case I'd like said check box to be by default enabled or disabled.
## Your environment
Latest Debian. Latest Alltube. Latest YTDL
Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Debian Linux
**What is your web server (Apache, IIS, etc.)?**
Apache
**What version of AllTube are you using?**
2.1.0
**How did you install AllTube (with Git or with a release package)?**
Release

## Describe your issue
Not an issue. Just a feature I'd like to see since only sometimes do we need streaming from the server, but this causes us to use it 100% of the time since my users don't understand when and why. so I'd like for them to learn and reduce strain. (I'd like to give the option to server stream, but have it disabled on the client side by default, therefore they have to hit the checkmark or such to enable it.)

**Comment by kinglyl** [comment]
well, I have not understand you clearly....
I mean, there is a button will be shown when users try to download a video, it allows users to switch whether download from remote server or directly

**Comment by Rudloff** [comment]
Indeed, we already provide a checkbox (since #218).
Or do you mean you would like the checkbox to not be checked by default?

**Comment by nahventure** [comment]
To have an option to make the default not go through the server yes.

**Comment by Rudloff** [comment]
This would be easy to implement but I need to think about the best structure for the YAML setting, in order to not make it more bloated than it already is.

**Comment by Rudloff** [comment]
I added (on the develop branch) a way to have the checkbox not checked by default:
```yaml
stream: ask
```

**Comment by nahventure** [comment]
thank you, when will it make it to the default branch?

**Comment by Rudloff** [comment]
I am working on this project on my free time, so I can not guarantee a release date. But I might publish a new release in the next few weeks if there is no blocking issue.

**Comment by nahventure** [comment]
Thanks dude great work
