### ISSUE TITLE
Some YouTube videos dont download in best quality

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#256]
# New issue

https://alltubedownload.net/

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Windows 10

**What is your web server (Apache, IIS, etc.)?**
Original

**What version of AllTube are you using?**
Original

**How did you install AllTube (with Git or with a release package)?**
Yes

**What version of PHP are you using?**
Original

**What version of Python are you using?**
Original

**What version of youtube-dl are you using?**
Same of site

**Do you get any PHP-related errors in your webserver's logs?**
N/A

**What is the content of your `config/config.yml` file?**
N/A

**Please provide the URL of a video that causes the issue.**
https://www.youtube.com/watch?v=WILNIXZr2oc 
https://www.youtube.com/watch?v=DVkkYlQNmbc

## Describe your issue

Some YouTube vídeos when i choose best quality on combobox he dont respect then.

**Comment by kinglyl** [comment]
It seems that you have not answer the questions...

**Comment by ialexsilva** [comment]
> It seems that you have not answer the questions...

I dont using a fork.
Its official https://alltubedownload.net

**Comment by kinglyl** [comment]
> > It seems that you have not answer the questions...
> 
> I dont using a fork.
> Its official https://alltubedownload.net

Sorry for that.
The author said it is not a high performance server, this may be caused the problem.
You can try it in your own server.
I would like to help you, but my server just broke down....So I can not test that link

**Comment by Rudloff** [comment]
"Best" for Youtube videos means the highest quality that contains both audio and video in the same file.
That's because higher quality videos are distributed as separate video and audio files: https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#download-1080p-videos-from-youtube

When listing available formats for your first example, we can see that almost every format is "video only" so it falls back to 640x360:
```
[youtube] WILNIXZr2oc: Downloading webpage
[youtube] WILNIXZr2oc: Downloading video info webpage
[youtube] WILNIXZr2oc: Downloading js player vflLL20EX
[youtube] WILNIXZr2oc: Downloading js player vflLL20EX
[info] Available formats for WILNIXZr2oc:
format code  extension  resolution note
249          webm       audio only tiny   61k , opus @ 50k (48000Hz), 1.45MiB
250          webm       audio only tiny   80k , opus @ 70k (48000Hz), 1.89MiB
140          m4a        audio only tiny  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 3.38MiB
251          webm       audio only tiny  153k , opus @160k (48000Hz), 3.63MiB
394          mp4        256x144    144p   83k , av01.0.00M.08, 24fps, video only, 1.73MiB
278          webm       256x144    144p   97k , webm container, vp9, 24fps, video only, 2.02MiB
160          mp4        256x144    144p  108k , avc1.4d400c, 24fps, video only, 1.53MiB
395          mp4        426x240    240p  200k , av01.0.00M.08, 24fps, video only, 3.20MiB
242          webm       426x240    240p  222k , vp9, 24fps, video only, 3.42MiB
133          mp4        426x240    240p  260k , avc1.4d4015, 24fps, video only, 2.96MiB
396          mp4        640x360    360p  375k , av01.0.01M.08, 24fps, video only, 5.73MiB
243          webm       640x360    360p  410k , vp9, 24fps, video only, 6.03MiB
134          mp4        640x360    360p  501k , avc1.4d401e, 24fps, video only, 5.54MiB
397          mp4        854x480    480p  715k , av01.0.04M.08, 24fps, video only, 10.11MiB
135          mp4        854x480    480p  727k , avc1.4d401e, 24fps, video only, 8.28MiB
244          webm       854x480    480p  754k , vp9, 24fps, video only, 9.31MiB
136          mp4        1280x720   720p 1018k , avc1.4d401f, 24fps, video only, 11.75MiB
247          webm       1280x720   720p 1371k , vp9, 24fps, video only, 16.07MiB
398          mp4        1280x720   720p 1498k , av01.0.05M.08, 24fps, video only, 20.45MiB
248          webm       1920x1080  1080p 2667k , vp9, 24fps, video only, 41.32MiB
399          mp4        1920x1080  1080p 2706k , av01.0.08M.08, 24fps, video only, 35.92MiB
137          mp4        1920x1080  1080p 4014k , avc1.640028, 24fps, video only, 42.56MiB
18           mp4        640x360    360p  479k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 12.51MiB (best)
```

**Comment by ialexsilva** [comment]
> outube videos means the highest quality that contains both audio and video in the same file.
> That's because higher quality videos are distributed as separate video and audio files:

I understand... tks for reply
