### ISSUE TITLE
Having Error

### ISSUE THREAD

**Issue by wasim231** [Rudloff/alltube#258]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

**Please provide the URL of a video that causes the issue.**

## Describe your issue
http://vidzgrab.epizy.com/info?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D68ByBlpwG_0

Having error when click download button

**Comment by wasim231** [comment]
http://vidzgrab.epizy.com/info?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D68ByBlpwG_0

**Comment by wasim231** [comment]
not working giving an error

**Comment by Rudloff** [comment]
Hello,
Please fill the issue template when reporting an issue.

Here is the error I get when following your link:
> The Process class relies on proc_open, which is not available on your PHP installation. 

As the error says, the [`proc_open`](https://www.php.net/manual/fr/function.proc-open.php) function needs to be available on your server.

**Comment by Rudloff** [comment]
No answer so I'm closing.
Feel free to reopen if you still have a problem.
