### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by mertozturk** [Rudloff/alltube#259]
Hi,

Some videos fail error, how can I update youtube-dl?

https://alltubedownload.net/info?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DAh0Ys50CqO8

`ERROR: Signature extraction failed: Traceback (most recent call last): File "/app/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature video_id, player_url, s File "/app/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function cache_res = res(test_string) File "/app/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1356, in <lambda> return lambda s: initial_function([s]) File "/app/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 258, in resf res, abort = self.interpret_statement(stmt, local_vars) File "/app/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement v = self.interpret_expression(expr, local_vars, allow_recursion) File "/app/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression m.group('expr'), local_vars, allow_recursion - 1) File "/app/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression m.group('x'), local_vars, allow_recursion - 1) File "/app/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement v = self.interpret_expression(expr, local_vars, allow_recursion) File "/app/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression m.group('x'), local_vars, allow_recursion - 1) File "/app/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement v = self.interpret_expression(expr, local_vars, allow_recursion) File "/app/vendor/rg3/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression raise ExtractorError('Unsupported JS expression %r' % expr) ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. (caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. `

**Comment by AndreasTheDead** [comment]
I have the same Problem with the docker container (https://hub.docker.com/r/rudloff/alltube)

**Comment by Rudloff** [comment]
Hello,
Thanks for the report.
I upgrade youtube-dl on the develop branch, so it will be fixed in the next release: https://github.com/Rudloff/alltube/commit/18abd00c9ce0b5fb97ade90e6e35052193f5e38a
