### ISSUE TITLE
error downloading youtube mp3 

### ISSUE THREAD

**Issue by samarun** [Rudloff/alltube#26]
Hi,

i have noticed recently that downloading mp3 from youtube.com is not working....
getting this error 
Fatal error: Cannot use object of type stdClass as array in /var/www/api.php on line 80

all other sites mp3 download works fine

**Comment by Rudloff** [comment]
Hum, it works for me.
What version are you using?
What is the URL of the video you are trying to download?

**Comment by samarun** [comment]
im using the latest version 

trying to download this https://www.youtube.com/watch?v=F-qBD17wwrQ
http://www.fetchclip.com
