### ISSUE TITLE
Latest error 2020-2-14

### ISSUE THREAD

**Issue by BOBMASRER** [Rudloff/alltube#261]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

**Please provide the URL of a video that causes the issue.**

## Describe your issue

Hello, developers
I am using your demo site and it come out with a problem

![Screenshot from 2020-02-14 16-45-43](https://user-images.githubusercontent.com/32976627/74515556-bf5d6f80-4f49-11ea-9539-9472446c3d83.png)

**Comment by BOBMASRER** [comment]
The video i download is https://youtu.be/IBcnfrmDi7I

**Comment by Rudloff** [comment]
This has already been fixed on the develop branch: https://github.com/Rudloff/alltube/issues/259
I will try to publish a new stable release before the end of the month.
