### ISSUE TITLE
How to use referer option?

### ISSUE THREAD

**Issue by sam9177** [Rudloff/alltube#264]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?** Debian

**What is your web server (Apache, IIS, etc.)?** Apache

**What version of AllTube are you using?** 2.1.0

**How did you install AllTube (with Git or with a release package)?** Composer

**What version of PHP are you using?** 7.3.15

**What version of Python are you using?** 2.7.13

**What version of youtube-dl are you using?** 2020.02.16

**Do you get any PHP-related errors in your webserver's logs?** Invalid filter specification u'referer=https://xhamster.com'

**What is the content of your `config/config.yml` file?** No file

**Please provide the URL of a video that causes the issue.** Any video of xhamster.com

## Describe your issue

Hello,
Youtube-dl has problems with xhamster.com. It shows 403 error for any video. But it works with option --referer='https://xhamster.com'

youtube-dl -f '[height<=720]' --referer='https://xhamster.com' https://xhamster.com/....... (any video)

How can I use this option in alltube?

$video = new Video($url, [protocol=https][height<=720]);
$video_url = $video->getUrl();

**Comment by kinglyl** [comment]
first, I think it should be
```php
$video = new Video($url, "[protocol=https][height<=720]");
```

**Comment by kinglyl** [comment]
If you want to add more options
Please write the code like this
```php
Config::setOptions(
    [
        'youtubedl' => '/usr/local/bin/youtube-dl',
		'python' 	=> '/usr/bin/python3',  //set it accustom your env
		'params'	=> array("--no-warnings","--ignore-errors","--flat-playlist","--restrict-filenames","--no-playlist"),  //add your options like this
		
    ]
);
```

**Comment by sam9177** [comment]
I have tried like this.  No result.
'params'	=> array("--no-warnings","--ignore-errors","--flat-playlist","--restrict-filenames","--no-playlist","--referer='https://xhamster.com'"),

**Comment by Rudloff** [comment]
I think you should set it like this:
```php
'params' => array("--no-warnings","--ignore-errors","--flat-playlist","--restrict-filenames","--no-playlist","--referer", "https://xhamster.com"),
```
