### ISSUE TITLE
css throwing 404 in the latest version

### ISSUE THREAD

**Issue by msbt** [Rudloff/alltube#267]
# New issue
As the title suggests, I tried updating to the latest version as I usually do, but this time it didn't work as expected. After updating it wouldn't render the css properly getting 404 on both css/fonts.css and css/style.css (git release shows them in the root directory), the rest is working normally. Any ideas what went wrong there? Just figured that the `dist` dir is missing in the 2.2.0 package, in 2.1.0 it is there.

Best regards, M

## Your environment

**What is your operating system (Windows, Linux, OSX, etc.)?**
Ubuntu Server

**What is your web server (Apache, IIS, etc.)?**
Apache behind Nginx

**What version of AllTube are you using?**
2.2.0

**How did you install AllTube (with Git or with a release package)?**
Release package

**What version of PHP are you using?**
7.2

**What version of Python are you using?**
2.7

**Comment by Rudloff** [comment]
Thanks for the report! The CSS files were moved and it seems I did not update the release script correctly.
I published a new release that fixed the issue.
