### ISSUE TITLE
npm-asset/open-sans-fontface not found

### ISSUE THREAD

**Issue by ismailkarsli** [Rudloff/alltube#268]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Windows
**What is your web server (Apache, IIS, etc.)?**
Apache
**What version of AllTube are you using?**
Trying to install 2.2.1
**How did you install AllTube (with Git or with a release package)?**
Composer
**What version of PHP are you using?**
7.4

## Describe your issue
Composer didn't find npm-asset/open-sans-fontface.

PS D:\Apache24\htdocs\Drive> composer require rudloff/alltube
Using version ^2.2 for rudloff/alltube
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rudloff/alltube 2.2.1 requires npm-asset/open-sans-fontface ^1.4 -> no matching package found.
    - rudloff/alltube 2.2.0 requires npm-asset/open-sans-fontface ^1.4 -> no matching package found.
    - Installation request for rudloff/alltube ^2.2 -> satisfiable by rudloff/alltube[2.2.0, 2.2.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by Rudloff** [comment]
Hello,
You need to add [Asset Packagist](https://asset-packagist.org/) to your `composer.json` file.
I updated the example project to reflect that: https://github.com/Rudloff/alltube-example-project/commit/1383f08da76553779da046a92b37d0642e1f9b3e

**Comment by ismailkarsli** [comment]
Thanks for help.
