### ISSUE TITLE
Download stored YouTube Livestreams

### ISSUE THREAD

**Issue by tmaex** [Rudloff/alltube#269]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Debian 10

**What is your web server (Apache, IIS, etc.)?**
Apache

**What version of AllTube are you using?**
master branch (2.2.1)

**How did you install AllTube (with Git or with a release package)?**
git

**What version of PHP are you using?**
7.3

**What version of Python are you using?**
2.7.16

**What version of youtube-dl are you using?**
2020.02.16

**Do you get any PHP-related errors in your webserver's logs?**
no

**What is the content of your `config/config.yml` file?**

```
---
# Path to your youtube-dl binary
youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: vendor/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
# Set to "ask" if you want to allow it but not enable by default.
stream: true

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 256

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    best: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst: Worst

# Enable debug mode.
debug: false
```

**Please provide the URL of a video that causes the issue.**
https://www.youtube.com/watch?v=BY4eGESChHc

## Describe your issue

When using the "only audio" feature on the startpage there occures this message:
`ERROR: requested format not available`

**Comment by Rudloff** [comment]
Thanks for the report! It is now fixed on the develop branch.
