### ISSUE TITLE
dailymotion not working

### ISSUE THREAD

**Issue by samarun** [Rudloff/alltube#27]
Hi,

i noticed that downloading videos from dailymotion.com no longer working 

Please check the URL of your video.
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by nodiscc** [comment]
> please report this issue on https://yt-dl.org/bug .

**Comment by Rudloff** [comment]
Hello,
You need to update youtube-dl:
```
./youtube-dl -U
```
(Note that the master branch always installs the latest youtube-dl now: https://github.com/Rudloff/alltube/commit/9013d0af4d61ecde32bbb53c249dc4e005bc2632)
