### ISSUE TITLE
500 internal server error - what is missing?

### ISSUE THREAD

**Issue by csjjpm** [Rudloff/alltube#270]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?** FreeBSD

**What is your web server (Apache, IIS, etc.)?** Apache 24

**What version of AllTube are you using?** latest 2.2.1

**How did you install AllTube (with Git or with a release package)?** downloaded zip files

**What version of PHP are you using?** 7.2

**What version of Python are you using?** 3.8.1

**What version of youtube-dl are you using?** whatever composer installed

**Do you get any PHP-related errors in your webserver's logs?** not sure

**What is the content of your `config/config.yml` file?** default

**Please provide the URL of a video that causes the issue.** not applicable

## Describe your issue
I get the following error when I type the path to the webpage

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at myemail@mydomain.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by Rudloff** [comment]
Hello,

> Do you get any PHP-related errors in your webserver's logs? not sure

I can't do anything with an error log.

You can also try to add this to `config.yml` to get a more verbose error:
```yaml
debug: true
```

**Comment by csjjpm** [comment]
[Sun Apr 05 15:50:25.897603 2020] [core:alert] [pid 30935] [client x.x.x.x:52889] /usr/local/www/alltube/.htaccess: Unknown filter provider DEFLATE
[Sun Apr 05 15:50:27.393858 2020] [core:alert] [pid 36828] [client x.x.x.x:52891] /usr/local/www/alltube/.htaccess: Unknown filter provider DEFLATE
[Sun Apr 05 15:50:28.366347 2020] [core:alert] [pid 36788] [client x.x.x.x:52892] /usr/local/www/alltube/.htaccess: Unknown filter provider DEFLATE

**Comment by csjjpm** [comment]
I didnt get anymore error information changing the config to verbose

**Comment by Rudloff** [comment]
Thanks! It should now be fixed on the develop branch.

**Comment by csjjpm** [comment]
Thank you.  How do I get the development branch?

**Comment by Rudloff** [comment]
If you are not using Git, you wil have to wait for the next release.

You can also apply [this change](https://github.com/Rudloff/alltube/commit/15c17c67509329f7513cad9a6bf2a9ecabfbbf94) manually or enable mod_deflate on your server.

**Comment by csjjpm** [comment]
I've made that change manuall and now get a blank page.  Python 3.7.7 is installed but the error.log shows this

[Sun Apr 12 16:24:13.838933 2020] [php7:error] [pid 47918] [client X.X.X.X:56425] PHP Fatal error:  Uncaught Exception: Can't find Python at /usr/bin/python in /usr/local/www/alltube/classes/Config.php:212\nStack trace:\n#0 /usr/local/www/alltube/classes/Config.php(274): Alltube\\Config->validateOptions()\n#1 /usr/local/www/alltube/index.php(21): Alltube\\Config::setFile('/usr/local/www/...')\n#2 {main}\n  thrown in /usr/local/www/alltube/classes/Config.php on line 212
