### ISSUE TITLE
Smarty could not compile the template file

### ISSUE THREAD

**Issue by sgorki** [Rudloff/alltube#271]
#  Smarty could not compile the template file

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Debian 10
**What is your web server (Apache, IIS, etc.)?**
Apache
**What version of AllTube are you using?**
Develop branch
**How did you install AllTube (with Git or with a release package)?**
Git
**What version of PHP are you using?**
PHP 7.2
**What version of Python are you using?**
3.8.2
**What version of youtube-dl are you using?**
Lastest, maybe
**Do you get any PHP-related errors in your webserver's logs?**
No
**What is the content of your `config/config.yml` file?**
As default
**Please provide the URL of a video that causes the issue.**
https://truedl.quangthang.men
## Describe your issue
```
Smarty could not compile the template file: unable to write file /var/www/truedl.quangthang.men/public_html/templates_c/wrt5e8c0c3b4f46d7_30672065
```
I saw this error when I accessed my site, I've chmod templates_c folder and edit `AllowOveride`.

**Comment by Rudloff** [comment]
Hello,
What are the permissions on `templates_c`. This error happens when the Apache user can't write to it.

**Comment by yas9999** [comment]
Hello,
i just have the same issue, if you set 'templates_c' folder to 770 you will get this error
you can just do chmod 755 templates_c

**Comment by Rudloff** [comment]
I don't recommend using 755. It is a better practice to set the correct/user group on this folder with chown so that your web server user can write to it.

**Comment by sgorki** [comment]
> I don't recommend using 755. It is a better practice to set the correct/user group on this folder with chown so that your web server user can write to it.
```
drwxr-xr-x 2 root root 4096 Apr  7 11:59 templates_c
```
I did but nothing changed

**Comment by sgorki** [comment]
Issue resolve!

**Comment by kinglyl** [comment]
> I don't recommend using 755. It is a better practice to set the correct/user group on this folder with chown so that your web server user can write to it.

I will get an error too if use 770.So I always use 777
