### ISSUE TITLE
PHP Fatal Error: Uncaught Exception: Can't find python

### ISSUE THREAD

**Issue by csjjpm** [Rudloff/alltube#273]
I made the change manually you recommended from my previous ticket #270 and now get a blank page. Python 3.7.7 is installed but the error.log shows this

# New issue
Ongoing issue
## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?** Freebsd

**What is your web server (Apache, IIS, etc.)?** Apache 2.4

**What version of AllTube are you using?** latest

**How did you install AllTube (with Git or with a release package)?** downloaded zip file

**What version of PHP are you using?** 7.2.29

**What version of Python are you using?** 3.7.7

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**
[Sun Apr 12 16:24:13.838933 2020] [php7:error] [pid 47918] [client X.X.X.X:56425] PHP Fatal error: Uncaught Exception: Can't find Python at /usr/bin/python in /usr/local/www/alltube/classes/Config.php:212\nStack trace:\n#0 /usr/local/www/alltube/classes/Config.php(274): Alltube\Config->validateOptions()\n#1 /usr/local/www/alltube/index.php(21): Alltube\Config::setFile('/usr/local/www/...')\n#2 {main}\n thrown in /usr/local/www/alltube/classes/Config.php on line 212

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

**Comment by Rudloff** [comment]
Does `/usr/bin/python` exist? Is the user that runs Apache authorized to execute it?

**Comment by csjjpm** [comment]
I've found it in /usr/local/bin/python
Can I just do a string search and replace on a file?
Thank you for your help.

**Comment by Rudloff** [comment]
You can add this to your `config/config.yml` file:
```yaml
python: /usr/local/bin/python
```

**Comment by csjjpm** [comment]
This is annoying me now! :-)  the error now is:
PHP Fatal error:  Uncaught Exception: Can't find Python at /usr/bin/local/python

But if I type in:
/usr/bin/local/python --version
I get returned
Python 3.7.7

that is a symlink to
/usr/bin/local/python3.7

**Comment by Rudloff** [comment]
> Can't find Python at /usr/bin/local/python

Wasn't it `/usr/local/bin/python`?

**Comment by csjjpm** [comment]
Haha! well spotted.  Fixed.  All working.  Thanks for your help,
