### ISSUE TITLE
Feature request: SOCKS5 proxy with authentication

### ISSUE THREAD

**Issue by csjjpm** [Rudloff/alltube#274]
# New issue
implement the SOCKS param for youtube_dll
## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
FreeBSD
**What is your web server (Apache, IIS, etc.)?**
Apache2.4
**What version of AllTube are you using?**
latest main
**How did you install AllTube (with Git or with a release package)?**
zip download
**What version of PHP are you using?**

**What version of Python are you using?**
3.7.7
**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

## Describe your issue
I would like to implement the SOCKS option
socks5://username:password@hostname:port --simulate https://www.youtube.com/watch?v=jNQXAC9IVRw

**Comment by Rudloff** [comment]
You can add custom youtube-dl parameters to `config.yml`:

```yaml
# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist
    - --proxy
    - socks5://username:password@hostname:port
```

**Comment by Rudloff** [comment]
No answer so I'm closing.
Feel free to reopen if you still have a problem.
