### ISSUE TITLE
bug report: from your DEMO web page

### ISSUE THREAD

**Issue by inglesuniversal** [Rudloff/alltube#277]
Tried this url: https://www.youtube.com/watch?v=vQW-zB_JHbs

and got this error

`
ERROR: Signature extraction failed: Traceback (most recent call last): File "/app/vendor/ytdl-org/youtube-dl/youtube_dl/extractor/youtube.py", line 1385, in _decrypt_signature video_id, player_url, s File "/app/vendor/ytdl-org/youtube-dl/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function raise ExtractorError('Cannot identify player %r' % player_url) ExtractorError: Cannot identify player u'https://www.youtube.com/s/player/52b1e972/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/s/player/52b1e972/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

`

Any pointer how to fix it or prevent it in the future?

Thanks

**Comment by Rudloff** [comment]
Thanks for the report.
This will be fixed in the next release (https://github.com/Rudloff/alltube/commit/95977c556460678c4fae39071483e5bfa5f0745e).
