### ISSUE TITLE
CSS and JS file Load issue.

### ISSUE THREAD

**Issue by ankitsnlq** [Rudloff/alltube#28]

**Comment by ankitsnlq** [comment]
Hi , 

I have installed this on Apache server , everything went well and video download is also work. But main.css and main.js file is not loading so break site from properly loading.

![untitled](https://cloud.githubusercontent.com/assets/7347629/9058484/22ca06e0-3abf-11e5-9777-2a10644f1c0d.png)

**Comment by Rudloff** [comment]
Hello,

As explained [here](https://github.com/Rudloff/alltube/pull/12), you need to either:
* Use a release package: https://github.com/Rudloff/alltube/releases
* Use [Grunt](http://gruntjs.com/) in order to build the CSS and JS files

**Comment by ankitsnlq** [comment]
Thank you Rudloff for fast reply and your precious time.
