### ISSUE TITLE
Docker image exposing a lot of files

### ISSUE THREAD

**Issue by Pofilo** [Rudloff/alltube#281]
Hello,

The Docker image is exposing a lot of files due to `COPY . /var/www/html/`.
For example the `.git` directory is available and the files in it: `example.com/.git/index`.

Shouldn't alltube be built on a specific folder and the `COPY` made on this folder ?
Or maybe using the zip generated in the releases and adding an apache (or whatever) to expose it ?
I can help with a PR if needed but I never used composer and php stuffs.

Thanks.

**Comment by Rudloff** [comment]
Hello,
I don't use Docker anymore so the image is not really maintained.
However, pull requests are welcome.

**Comment by Rudloff** [comment]
I added the `.git` folder to `.dockerignore`.
It also now only installs production Composer dependencies.

**Comment by Pofilo** [comment]
That's a good idea I think !
But I was looking for a way to include all the content of the .gitignore, I don't know if some files are necessary for the running ..

**Comment by Rudloff** [comment]
I am not sure I understand what you are suggesting.
`.dockerignore` is currently a symlink to `.gitignore` so the only files included in the Docker image will be the source code from the Git repository + the dependencies installed with Composer.
