### ISSUE TITLE
On latest update after installing master zip on BITNAMI LAMP 7.3 server (as is)

### ISSUE THREAD

**Issue by inglesuniversal** [Rudloff/alltube#282]
I got these error codes on console.log:

mydomain.com/:82 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-xxxxxxxxxxxxxxxxxx='), or a nonce ('nonce-...') is required to enable inline execution.

mydomain.com/:84 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

Even though I get above message, script ran successfully !!!

Can region restricted videos (outside the US) be pulled for testing purposes? Got ERROR displaying such restriction on link shown below:

https://www.youtube.com/watch?v=vQW-zB_JHbs

**Comment by Rudloff** [comment]
Please don't remove the issue template.

> mydomain.com/:82 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-xxxxxxxxxxxxxxxxxx='), or a nonce ('nonce-...') is required to enable inline execution.

Unless debug mode is enabled, the app does not contain any inline script so I am not sure where this error comes from. (Unless you clicked on the bookmarklet?)

> Can region restricted videos (outside the US) be pulled for testing purposes? Got ERROR displaying such restriction on link shown below:

The IP address used by AllTube is the IP address of your server. There is not easy way to work around that (see https://github.com/Rudloff/alltube/issues/97).
