### ISSUE TITLE
Downloaded videos download as Download.htm instead of Download.mp4

### ISSUE THREAD

**Issue by jdaviescoates** [Rudloff/alltube#283]
# New issue

I don't understand why, when saving a video the download is called Download.htm instead of Download.mp4

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

Well, this happens wherever I do it/ on whatever machine, but I've most recently test using Android 8.1.0 and Ubuntu 20.04

**What is your web server (Apache, IIS, etc.)?**

Not sure actually, but I think perhaps Nginx. I'm using my install at https://download.uniteddiversity.coop/ which is powered by https://cloudron.io/

**What version of AllTube are you using?**

2.3.0

**How did you install AllTube (with Git or with a release package)?**

I installed the Cloudron package (which is based on Docker)

**What version of PHP are you using?**

Not sure. I guess whatever the default in Ubuntu 18.04 is.

**What version of Python are you using?**

Not sure. I guess whatever the default in Ubuntu 18.04 is.

**What version of youtube-dl are you using?**

Whatever AllTube 2.3.0 uses

**Do you get any PHP-related errors in your webserver's logs?**

Haven't looked.

**What is the content of your `config/config.yml` file?**

Where do I find that?

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

Every single video I've ever tried, e.g. https://www.youtube.com/watch?v=9cGh8oeA724&feature=youtu.be

## Describe your issue

On Ubuntu 20.04 with Firefox 76.0.1

1. I paste [the video URL](https://www.youtube.com/watch?v=9cGh8oeA724&feature=youtu.be) into the box on https://download.uniteddiversity.coop/ and hit the Download button

2. I think click the Download button

3. The [source video](https://r1---sn-vgqskne6.googlevideo.com/videoplayback?expire=1590180819&ei=c-fHXqO-AdiT1gLwg4TQBQ&ip=116.203.252.254&id=o-AP3-MDC48WmOqnu1Ylg4ju07RpOF1jhIYxiXHhfz97tA&itag=22&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=37.430&lmt=1589911807328877&fvip=1&c=WEB&txp=6216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgMU6nakutOaTPVMQ-QqBqTmZe7RUzYf_vVUPxgdwws_ICIQCm555uawhEP3ar5W9wAzxXIvjRHlfyS4UR41yIZZODhw%3D%3D&redirect_counter=1&cm2rm=sn-4g5ezz7e&fexp=23812955&req_id=99014ac019f7a3ee&cms_redirect=yes&mh=H7&mip=90.252.158.6&mm=34&mn=sn-vgqskne6&ms=ltu&mt=1590159149&mv=D&mvi=0&pl=0&lsparams=mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRAIgEgL8mWET7sG6URfys7ll0f3aVwq7IuZ6LZVezc7dI_ECIDY6TluZ9gTcvyuPzA-pJnvU_vGyl6zCQG5v0OK_m2J8) opens in my browser (instead of actually downloading as one might expect after clicking a 'Download' button)

4. I right-click Save Video As... and automatically the name is download.htm instead of .mp4.  On Ubuntu I can choose at this point to rename the file before the download actually begins.  On Android I get no such choice and the file just automatically downloads using the default download.htm name.

**Comment by Rudloff** [comment]
By default, AllTube only redirects you to the video file, so its name and wether you get a download prompt or not depends on what response the server hosting the video returns.
It you want AllTube to rename the file and force a download prompt, you have to enable the "Stream the video through the server" option.

**Comment by jdaviescoates** [comment]
Thanks @Rudloff "Stream the video through the server" could perhaps be better/ more clearly worded, but yes checking that box does indeed result in the behaviour I want.  Is there are way to configure it to auto-check that box so I don't have to manually select it each time? Thanks!

**Comment by Rudloff** [comment]
I just noticed there was a bug in how #255 was implemented.
Cloudron seems to use `stream: true` (cf. [here](https://git.cloudron.io/cloudron/alltube-app/-/blob/55dbff3aba97c2410622b713b037a6b6a6fcc77e/start.sh#L20)) so the checkbox should be checked by default.
This will be fixed in the next release.

**Comment by jdaviescoates** [comment]
Great, thanks for the update. I look forward to the next release :)

**Comment by mellowfunk** [comment]
a question??

anyone know how can I download this video https://www.kadgroove.net/watch.php?vid=cd4a48874

regards

**Comment by Rudloff** [comment]
@mellowfunk Please don't hijack an unrelated issue. I created a new issue here: https://github.com/Rudloff/alltube/issues/284
