### ISSUE TITLE
kadgroove.net not supported

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/alltube#284]
a question??

anyone know how can I download this video https://www.kadgroove.net/watch.php?vid=cd4a48874

regards

_Originally posted by @mellowfunk in https://github.com/Rudloff/alltube/issues/283#issuecomment-633908139_

**Comment by Mennaruuk** [comment]
I just want to point out that this month, kadgroove.net started redirecting to KadGroove's Vimeo page. So I think this issue can be closed.
