### ISSUE TITLE
Call to undefined function Alltube\_()

### ISSUE THREAD

**Issue by ivanioannovich** [Rudloff/alltube#286]
I try download Youtube video, but error:

Fatal error: Uncaught Error: Call to undefined function Alltube\_() in /vendor/rudloff/alltube/classes/Config.php:158
Stack trace:
#0 /vendor/rudloff/alltube/classes/Config.php(257): Alltube\Config->__construct()
#1 /vendor/rudloff/alltube/classes/Config.php(288): Alltube\Config::getInstance()
#2 /alltube_getURL.php(14): Alltube\Config::setOptions(Array)
#3 {main}
  thrown in /vendor/rudloff/alltube/classes/Config.php on line 158

Try "php composer.phar update" and nothing.

**Comment by Rudloff** [comment]
Please don't remove the issue template.

What version of Alltube are you using? I don't think we use `_()` anymore.

**Comment by ivanioannovich** [comment]
if (empty($this->genericFormats)) {
            // We don't put this in the class definition so it can be detected by xgettext.
            $this->genericFormats = [
                'best'                => _('Best'),
                'bestvideo+bestaudio' => _('Remux best video with best audio'),
                'worst'               => _('Worst'),
            ];
        }

**Comment by Rudloff** [comment]
You are clearly not using the latest version since this was removed in https://github.com/Rudloff/alltube/commit/cc55fabe14f62cb297c3740831ea7d1a796873b1.

Anyway, the `_()` function is an alias for `gettext()` so you need to install the [gettext extension](https://www.php.net/manual/en/book.gettext.php).
