### ISSUE TITLE
Run on Openwrt?

### ISSUE THREAD

**Issue by sindhus** [Rudloff/alltube#29]
hi! Openwrt still doesnt have nodejs packaged and i didnt see composer packaged. Do you perhaps know of a way I can install this on Openwrt? Thanks!

**Comment by Rudloff** [comment]
I am not familiar with OpenWrt but you can try the release package that does not need node or Composer: https://github.com/Rudloff/alltube/releases/download/0.3.1/alltube-release.zip

**Comment by sindhus** [comment]
Oh super! thanks :)
