### ISSUE TITLE
about file name and support for link advertiser

### ISSUE THREAD

**Issue by askfriends** [Rudloff/alltube#299]
This is very nice and useful project.
i have two questions

1. When i click on download, it gives file as "videoplayback.mp4", so can you fix it and file  rename should be exactly as it shows in youtube?

2. Can you add support for link shortners like linkvertise or adf.ly? they have api too.
When download is ready, user must go through linkvertise or any link shortner service and then be able to download?

**Comment by Rudloff** [comment]
Hello,
1. By default, Alltube redirects the browser to the video file, so the filename is the one served by the server hosting it.
Alltube can only rename the file if stream mode is enabled: https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#the-downloaded-videos-have-a-strange-name-like-videoplaybackmp4
1. Can you please provide an example URL?

**Comment by askfriends** [comment]
> Hello,
> 
> 1. By default, Alltube redirects the browser to the video file, so the filename is the one served by the server hosting it.
>    Alltube can only rename the file if stream mode is enabled: https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#the-downloaded-videos-have-a-strange-name-like-videoplaybackmp4
> 2. Can you please provide an example URL?

1. Got it.
2. there are many websites available who does this, most of them have api too.
basically when file is ready to download, and user click on download, then user will go through an advertisement page, where he will wait for 5 seconds may be 10, and then he hits Skip, finally he will come back to download page. here is example url
http://bc.vc/cy5vMpC

**Comment by Rudloff** [comment]
> http://bc.vc/cy5vMpC

Wow, this is full of phishing ads.

If I understand correctly, you want AllTube to show ads before redirecting to the download? You are free to do that is you host your own instance, but I will not support that.
