### ISSUE TITLE
Video files are streaming instead of download

### ISSUE THREAD

**Issue by telegrambotdev** [Rudloff/alltube#313]
When i try to download any youtube videos,it keeps streaming to my browser,instead of downloading.i already turned of STREAM to false.then why it keep streaming ? any solutions ?

**Comment by Rudloff** [comment]
Please read this: https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#my-browser-plays-the-video-instead-of-downloading-it

If you enable stream mode, it will force the browser to download the video. ("Stream" here refers to streaming through the server, not to the browser streaming the video.)

**Comment by telegrambotdev** [comment]
understood
