### ISSUE TITLE
Bad URL timestamp error for downloading instagram reel videos

### ISSUE THREAD

**Issue by telegrambotdev** [Rudloff/alltube#314]
`Bad URL timestamp error` for downloading instagram reel videos

eg : https://www.instagram.com/reel/CFtjDfaha6M/

Kindly fix it

**Comment by Rudloff** [comment]
Please don't remove the issue template.

Instagram reels are not supported by youtube-dl: https://github.com/ytdl-org/youtube-dl/issues/26234
