### ISSUE TITLE
More than one MPM loaded error while deploying to heroku

### ISSUE THREAD

**Issue by telegrambotdev** [Rudloff/alltube#315]
When i try to deploy in heroku as a docker container,it produce More than one  MPM loaded error.but the  same Dockerfile works fine in my Server.so whats wrong ?
 The deafult heroku deploy button working fine,i am talking about deploy as a Docker container in heroku,produces the below error.any fixes ? i didnt modified any configs.

I am using latest version of alltube master branch code.

`heroku[web.1]: Starting process with command `/usr/sbin/apache2ctl -D FOREGROUND`
2020-10-11T05:23:32.401979+00:00 heroku[web.1]: Process exited with status 1
2020-10-11T05:23:32.438952+00:00 heroku[web.1]: State changed from starting to crashed
2020-10-11T05:23:32.334647+00:00 app[web.1]: AH00534: apache2: Configuration error: More than one MPM loaded.
2020-10-11T05:23:32.347094+00:00 app[web.1]: Action '-D FOREGROUND' failed.
2020-10-11T05:23:32.347096+00:00 app[web.1]: The Apache error log may have more information.`

**Comment by Rudloff** [comment]
I have never used this Heroku feature.

AllTube itself does not specify a MPM, so this is probably a problem with Heroku or the base Docker image.

**Comment by telegrambotdev** [comment]
> I have never used this Heroku feature.
> 
> AllTube itself does not specify a MPM, so this is probably a problem with Heroku or the base Docker image.
yup.i generated a hotfix for heroku docker deploy.will be make a pr

**Comment by telegrambotdev** [comment]
> I have never used this Heroku feature.
> 
> AllTube itself does not specify a MPM, so this is probably a problem with Heroku or the base Docker image.

yup.i generated a hotfix for that heroku docker deploy error.i will make a pr soon.

**Comment by Rudloff** [comment]
I found this issue which provides some explanation: https://github.com/docker-library/wordpress/issues/293

**Comment by telegrambotdev** [comment]
> I found this issue which provides some explanation: [docker-library/wordpress#293](https://github.com/docker-library/wordpress/issues/293)

yup its the heroku side error.
