### ISSUE TITLE
"Unable to extract JS player URL", even if the url is correct

### ISSUE THREAD

**Issue by stemy2** [Rudloff/alltube#326]
New issue
Your environment

Please answer these questions when reporting a new issue:

What is your operating system (Windows, Linux, OSX, etc.)?
Linux
What is your web server (Apache, IIS, etc.)?
NGINX
What version of AllTube are you using?
2.3.0
How did you install AllTube (with Git or with a release package)?
Yunohost package
What version of PHP are you using?
7.3
What version of Python are you using?
2.7.16
What version of youtube-dl are you using?
Don't know
Do you get any PHP-related errors in your webserver's logs?
No
What is the content of your config/config.yml file?
Path to your youtube-dl binary

youtubedl: vendor/ytdl-org/youtube-dl/youtube_dl/main.py
Path to your python binary

python: /usr/bin/python
An array of parameters to pass to youtube-dl

params:
- --no-warnings
- --ignore-errors
- --flat-playlist
- --restrict-filenames
- --no-playlist
True to enable audio conversion

convert: true
True to enable advanced conversion mode

convertAdvanced: true
List of formats available in advanced conversion mode

convertAdvancedFormats: [mp3, avi, flv, wav]
Path to your avconv or ffmpeg binary

avconv: /usr/bin/ffmpeg
avconv/ffmpeg logging level.

avconvVerbosity: error
Path to the directory that contains the phantomjs binary.

phantomjsDir: vendor/bin/
True to disable URL rewriting

uglyUrls: false
True to stream videos through server

stream: true
True to enable remux mode (merge best audio and best video)

remux: true
MP3 bitrate when converting (in kbit/s)

audioBitrate: 128
App name

appName: AllTube Download

Please provide the URL of a video that causes the issue.
https://www.youtube.com/watch?v=h26riCup9cU
Describe your issue

Can't retrieve a video. The app think the URL is wrong, but it isn't.

`ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by Rudloff** [comment]
Thanks for the report.
Updating youtube-dl to 2020.11.01.1 seems to fix the issue.

**Comment by Rudloff** [comment]
My bad, 2020.11.01.1 still fails but with a different error:
```
 ERROR: h26riCup9cU: YouTube said: Unable to extract video data
```

However, since the youtube-dl repository is down, we can't report this error upstream.

**Comment by stemy2** [comment]
> However, since the youtube-dl repository is down, we can't report this error upstream.

Now, there are many alternative repositories for youtube-dl. We can try to report to them, maybe some of them are able to fix it.

**Comment by Rudloff** [comment]
`Unable to extract video data` seems to be a random error (maybe caused by network issues ?), so I consider this fixed.
