### ISSUE TITLE
Download and save in background (server side)

### ISSUE THREAD

**Issue by SaswatPadhi** [Rudloff/alltube#334]
Enhancement:

Instead of triggering a client-side (browser) download / streaming, alltube could save the video to a predefined location (may be in the config file) on the server side. It would also be nice if the web UI could show a list of previously downloaded and currently downloading videos.

**Comment by SaswatPadhi** [comment]
Ah, just noticed that it's related to #303.

**Comment by Rudloff** [comment]
The goal of AllTube is to download videos to the client.
There are other softwares that do what you ask ([youtube-dl-web-ui](https://github.com/ryoon/youtube-dl-web-ui), for example).

**Comment by SaswatPadhi** [comment]
Thanks. Closing this issue since it's out of scope.
