### ISSUE TITLE
How to use flag --netrc (.netrc authentication data) of youtube-dl

### ISSUE THREAD

**Issue by krswin** [Rudloff/alltube#335]
I have used docker image of rudloff/alltube from docker hub. 
I want to set Authentication data for youtube login to download private videos. 
How can I attach Volume to container and set this config files.
How to use flag --netrc (.netrc authentication data) of youtube-dl?

Please help. thanks.

**Comment by Rudloff** [comment]
You can use the `params` setting to customize options passed to `youtube-dl`: https://github.com/Rudloff/alltube/blob/c9aa41d20665799681cee320c22dd0e7d0648d15/config/config.example.yml#L9

**Comment by Rudloff** [comment]
@krswin Did you manage to do what you wanted? Can we close this?

**Comment by krswin** [comment]
yes you can close it. thanks.
