### ISSUE TITLE
List of Instances

### ISSUE THREAD

**Issue by Mennaruuk** [Rudloff/alltube#339]
Is there a list of self-hosted alltube instances like [the list for Invidious instances](https://invidio.us/)?

**Comment by Rudloff** [comment]
I don't have such a list but it would be great if someone could contribute one.

Here are some instances I know:
* https://alltube.drycat.fr/
* https://alltube.stemy.me/

**Comment by Mennaruuk** [comment]
Found a bunch more!! All of these are securely encrypted.

- https://ytvideodownload.net
- https://marlee-tube.herokuapp.com
- https://alltube.servicesforfree.com
- https://phr.ee
- https://alltubedownload.peertube.uno
- https://mcej.net/yt
- https://drastical.tech/alltube

**Comment by Mennaruuk** [comment]
I think it'd be awesome if a Wiki page can be created similar to that of [Nitter](https://github.com/zedeus/nitter/wiki/Instances). It can be a non-exhaustive list of encrypted instances. I checked the SSL grades of all these websites and it is as follows, I think they're all good:

- [https://alltubedownload.net (SSL Labs test)](https://www.ssllabs.com/ssltest/analyze.html?d=alltubedownload.net)
- [https://ytvideodownload.net (SSL Labs test)](https://www.ssllabs.com/ssltest/analyze.html?d=ytvideodownload.net)
- [https://marlee-tube.herokuapp.com (SSL Labs test)](https://www.ssllabs.com/ssltest/analyze.html?d=marlee-tube.herokuapp.com)
- [https://alltube.servicesforfree.com (SSL Labs test)](https://www.ssllabs.com/ssltest/analyze.html?d=alltube.servicesforfree.com)
- [https://phr.ee (SSL Labs test)](https://www.ssllabs.com/analyze.html?d=phr.ee)
- [https://alltubedownload.peertube.uno (ImmuniWeb test)](https://www.immuniweb.com/ssl/?id=bNlLYEdr)
- [https://mcej.net/yt (SSL Labs test)](https://www.ssllabs.com/ssltest/analyze.html?d=mcej.net) and [ImmuniWeb test](https://www.immuniweb.com/ssl/?id=WOwTwb54)
- [https://drastical.tech/alltube (SSL Labs test)](https://www.ssllabs.com/analyze.html?d=drastical.tech)

**Comment by ManeraKai** [comment]
Why is this closed? Won't be there any plans for this in the future?

**Comment by Rudloff** [comment]
I don't have time for this but anyone is free to maintain such a list.

**Comment by ManeraKai** [comment]
Having it on your Repo will make it more popular for people to join.

**Comment by Rudloff** [comment]
I am not a big fan of promoting instances that I know nothing about. For example, I have seen AllTube instances with ads/tracking.
I would prefer if this could be a community-curated list.
