### ISSUE TITLE
Site is down (again)

### ISSUE THREAD

**Issue by kaixxx** [Rudloff/alltube#348]
alltubedownload.net seems to be down. It's the same error rouelibre1 reported back in january : #338 
Maybe you can have a look. Thank you!

Error message:
-------------------------------
Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail 
-------------------------------

Browser: Firefox 86.0.1 (64-Bit) on Windows

**Comment by Rudloff** [comment]
Hello,
I tried to access the website and I don't any error.

**Comment by kaixxx** [comment]
The site works again. Seems to be some kind of intermittend problem. I will close this issue.
(Thank you for alltube - it's great!)
