### ISSUE TITLE
Tiktok error

### ISSUE THREAD

**Issue by mikagrand** [Rudloff/alltube#354]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

Hello, the script find the urls but want download the video file:

URL: https://alltubedownload.net/info?url=https%3A%2F%2Fwww.tiktok.com%2F%40starleyrezende%2Fvideo%2F6956679552697486597%3Fsender_device%3Dpc%26sender_web_id%3D6932471844961338885%26is_from_webapp%3Dv1%26is_copy_url%3D0

Can you help ?

**Comment by Rudloff** [comment]
TikTok requires sending some cookies to access the video.
By default, AllTube only redirects you to the video so it is not able to send those cookies.

If you host AllTube yourself, you can [enable stream mode](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#enable-streaming-videos-through-the-server) to work around this problem.

**Comment by mikagrand** [comment]
Hello, thank for reply,
i already do that but it's not working, you can test it on your online site demo you will see yourself.

**Comment by Rudloff** [comment]
> you can test it on your online site demo you will see yourself.

Stream mode is not enabled on https://alltubedownload.net/.

However, I tried locally and TikTok returns a 403 error although we are sending the `Cookie` and `Referer` headers.
Sending the same request with curl in a CLI returns a 200, so I am not sure what is happening here.

**Comment by mikagrand** [comment]
Ok, but i i'm not sure to understand you, but what the solution from now?

**Comment by Rudloff** [comment]
I did not understand if you are self-hosting AllTube or not (since you did not fill the issue template..).
If you are only using https://alltubedownload.net/, there is no solution.
If you are self-hosting AllTube, the solution is to wait for someone to understand (and fix) why TikTok is returning a 403 error.

**Comment by mikagrand** [comment]
A ok i see, thank. 
I used self-hosting, but due to many social network platforms not working i deleted.

**Comment by Rudloff** [comment]
I found the issue with Tiktok downloads.
The URL and the cookies were generated separately so they were not matching.

This will be fixed in the next release.
