### ISSUE TITLE
Need help with video file name

### ISSUE THREAD

**Issue by mikagrand** [Rudloff/alltube#355]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

Hello, 
i want to change videos and audio downloadable file, can you help me please.
I use option "True to stream videos through server" to TRUE.

Thank

**Comment by Rudloff** [comment]
Hello,
Please don't ignore the issue template.

What are you trying to achieve exactly?
The filename can be customize with the `--output` option passed to youtube-dl.
For example, you can add something like this to your `config.yml` file:
```yaml
params:
  - --no-warnings
  - --ignore-errors
  - --flat-playlist
  - --restrict-filenames
  - --no-playlist
  - '--output=%(id)s.%(ext)s'
```

The format is explained [here](https://github.com/ytdl-org/youtube-dl/#output-template).

**Comment by mikagrand** [comment]
oh ok, i just want to replace video ID by site URL in file name and also replace "_" by space " ".

Thank

**Comment by Rudloff** [comment]
> And last, please how to add external script like google analytics, because i get src security error.

The CSP is configured in `CspMiddleware::applyHeader()` so you would need to customize the directives here, but I won't provide support for doing that.
