### ISSUE TITLE
I have 2 questions ?

### ISSUE THREAD

**Issue by mikagrand** [Rudloff/alltube#356]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

Hello,
1). Can you please explain how to use cookies with your script (to try fix facebook, tiktok and instagram issue) ?
2). How to add more language on the script ?

Thank.

**Comment by Rudloff** [comment]
> Can you please explain how to use cookies with your script (to try fix facebook, tiktok and instagram issue) ?

alltube-library [automatically sends HTTP headers provided by youtube-dl](https://github.com/Rudloff/alltube-library/blob/5c4d39cd2b3f0f680ca55557fc0fc6cd54d3150f/classes/Downloader.php#L486) (including the `Cookie` header), so if youtube-dl generates a cookie, it will be sent when fetching the video.
(Note that this was apparently broken until https://github.com/Rudloff/alltube-library/commit/a0548ea473748b10f6146ba8f029e2947b332a46.)

If you are talking about setting a cookie manually, this is not supported.

> How to add more language on the script ?

Locales are defined in [the `i18n/` folder](https://github.com/Rudloff/alltube/tree/master/i18n).
To add a new locale, you need to create a new folder with `.po` and follow the same structure as the other folders.

**Comment by mikagrand** [comment]
Hello,
I don't understand you, uoutube-dl not support set cookies manually or it's only your script will not support ?

**Comment by Rudloff** [comment]
youtube-dl does support settings cookies but AllTube does not provide an easy way to pass this option to youtube-dl.
