### ISSUE TITLE
How to pass cookies parameter?

### ISSUE THREAD

**Issue by yothin** [Rudloff/alltube#358]
Hi, 
How to pass cookies file parameter in config.yml file 
`- --cookies my-cookie.txt`
But not work

Thanks

**Comment by Rudloff** [comment]
Hello,
I have never tried this myself but the correct syntax is:
```yaml
params:
    - --cookies 
    - my-cookie.txt
```

**Comment by yothin** [comment]
Thank you so much, I'll try
