### ISSUE TITLE
How to create multiple custom page

### ISSUE THREAD

**Issue by mikagrand** [Rudloff/alltube#362]
Hello,
I need your help, i want to create urls pages for every site support like: 
ex (https://alltubedownload.net/dailymotion-videos-downloader
      https://alltubedownload.net/tiktok-videos-downloader
      https://alltubedownload.net/vimeo-videos-downloader
      etc...)
Please help me.

Thank.

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

**Comment by Rudloff** [comment]
I am not sure I understand what you are asking.
What would these pages achieve?

**Comment by mikagrand** [comment]
Hi friend,
In these page i will explain to visitor how to download TikTok videos, Dailymotion videos, Vimeo videos etc...

**Comment by Rudloff** [comment]
AllTube does not support adding custom content pages. You will have to do that by yourself.

**Comment by mikagrand** [comment]
OH!, ok thank.
