### ISSUE TITLE
Vimeo best/bestvideo not working with "stream videos" and "MP3 convert"

### ISSUE THREAD

**Issue by mikagrand** [Rudloff/alltube#364]
Hi,
Vimeo best/bestvideo not working with "stream videos" and "MP3 convert", only worstvideo and some videos quality work, how to fix this ?

For MP3 i get this error: 
"An error occurred
Conversion of DASH segments is not supported."

For videos i get a not working video file with 0mb

Thank

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

**Comment by Rudloff** [comment]
Please at least provide an example URL.

**Comment by mikagrand** [comment]
I don't want to send my domain here i will send you imbox

**Comment by Rudloff** [comment]
I am talking about a Vimeo URL that can be used to reproduce the problem (since you did not fill the issue template...).

**Comment by mikagrand** [comment]
Any vimeo urls, you can test any vimeo urls, but with option "stream videos" and "MP3 convert" Active on config.yml

**Comment by mikagrand** [comment]
Ok, please look this
