### ISSUE TITLE
Vimeo best/bestvideo not working with "stream videos" and "MP3 convert"

### ISSUE THREAD

**Issue by mikagrand** [Rudloff/alltube#365]
Ok, please look this error:

The error: https://online-videos-downloader.com/download?url=https%3A%2F%2Fvimeo.com%2F410477604&audio=on

you can test with any other vimeo video url

Need help please.

Thank

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

**Comment by Rudloff** [comment]
Hello, please fill the issue template.

Anyway, I can reproduce the error:
> Conversion of DASH segments is not supported.

It seems the best audio format for Vimeo is a DASH URL and AllTube does not support converting DASH formats.
