### ISSUE TITLE
Disable auto language change

### ISSUE THREAD

**Issue by mikagrand** [Rudloff/alltube#390]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

Hi, how to disale auto laguage detect change by region, i want to choose myself the site language.

Thanks.

**Comment by Rudloff** [comment]
You can select the language manually via the menu in the top left corner.

**Comment by mikagrand** [comment]
No, i mean use only one language for the site and disable auto detect region ?

Thanks.

**Comment by Rudloff** [comment]
I guess you could simply delete the unwanted locales from the `i18n/` folder.

**Comment by mikagrand** [comment]
no, it's not working, i just want to disale auto language change.

**Comment by Rudloff** [comment]
There is no option to disable this behaviour.
