### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [Rudloff/alltube#397]
Hey there!

I belong to an open source security research community, and a member (@hitisec) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Rudloff** [comment]
Thanks for the report, I added a [security policy](https://github.com/Rudloff/alltube/security/policy).

**Comment by JamieSlome** [comment]
Thanks, @Rudloff - you should receive an e-mail shortly with a link that will allow you to access the report without having to sign up.

Otherwise, you can view the report directly here:
https://huntr.dev/bounties/4fb39400-e08b-47af-8c1f-5093c9a51203/

**Comment by Rudloff** [comment]
I tagged a new release that fixes the vulnerability and published a security advisory : https://github.com/Rudloff/alltube/security/advisories/GHSA-jmhf-9fj8-88gh
This is my first time interacting with https://huntr.dev/ and I found the process very smooth, thanks!

**Comment by JamieSlome** [comment]
Glad to hear it! 🤝
