### ISSUE TITLE
docker implementation

### ISSUE THREAD

**Issue by Savemech** [Rudloff/alltube#40]
Any chances  to get this fancy runned in docker?
i did try this one, https://hub.docker.com/r/red5d/alltube/
but no luck, links and causes to crash

**Comment by Rudloff** [comment]
I have pushed my build here: https://hub.docker.com/r/rudloff/alltube/
I also added my Dockerfile to the repository so you can build it yourself: https://github.com/Rudloff/alltube/blob/develop/Dockerfile

**Comment by Savemech** [comment]
Thank you very much!
