### ISSUE TITLE
Use cookies on your script

### ISSUE THREAD

**Issue by mikagrand** [Rudloff/alltube#400]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

Hello, how can i use cookies on your script to download video who need login to access video ?

Thank

**Comment by mikagrand** [comment]
No i mine in config.xml file, in option # An array of parameters to pass to youtube-dl
Is it possible to add cookies parameters ?

Thanks.

**Comment by Rudloff** [comment]
Please fill the issue template. I can't help you if I have no idea what version or config you are using, or the URL of the video you are trying to download.

**Comment by mikagrand** [comment]
'/app/.heroku/python/bin/python' 'vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py' '--no-warnings' '--ignore-errors' '--flat-playlist' '--restrict-filenames' '--no-playlist' '--dump-single-json' 'https://www.instagram.com/p/COxbsQ6FN7X/' '-f' 'best[protocol=https]/best[protocol=http]/bestvideo[protocol=https]/bestvideo[protocol=http]' failed with this error:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Rudloff** [comment]
> No i mine in config.xml file, in option # An array of parameters to pass to youtube-dl
> Is it possible to add cookies parameters ?

You can use any option that youtube-dl supports, so I guess you could use `--cookies`.

> ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests

The server made too many requests to Instagram.

**Comment by Rudloff** [comment]
Never filled the issue template...
