### ISSUE TITLE
How to change the background color please?

### ISSUE THREAD

**Issue by gitxxfan** [Rudloff/alltube#401]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
linux
**What is your web server (Apache, IIS, etc.)?**
nginx
**What version of AllTube are you using?**
3.0.0
**How did you install AllTube (with Git or with a release package)?**
package
**What version of PHP are you using?**
7.4
**What version of Python are you using?**
3.10
**What version of youtube-dl are you using?**
latest
**Do you get any PHP-related errors in your webserver's logs?**
no
**What is the content of your `config/config.yml` file?**

```yaml
no need
```

**Please provide the URL of a video that causes the issue.**

## Describe your issue
I want to change the page background color, and I tried to change the values in style.css  but seems it does not work,  Can anyone help on this please, Thanks.

**Comment by gitxxfan** [comment]
> 

Hello, I tried to delete the old fond.jpg and upload a new image named fond.jpg, but it does not work, what could be the reason please? Thanks.

**Comment by gitxxfan** [comment]
> There is currently no option to do this. The background is an image:
> 
> https://github.com/Rudloff/alltube/blob/bf4a761d3a828f4fa4248d31318fc64765ec0655/css/style.css#L3



> There is currently no option to do this. The background is an image:
> 
> https://github.com/Rudloff/alltube/blob/bf4a761d3a828f4fa4248d31318fc64765ec0655/css/style.css#L3

Hello, I tried to delete the old fond.jpg and upload a new image named fond.jpg, but it does not work, what could be the reason please? Thanks.

**Comment by Rudloff** [comment]
This issue tracker is for reporting bug.
If you want to customize AllTube, you are on your own.
