### ISSUE TITLE
Crunchyroll Error

### ISSUE THREAD

**Issue by JReming85** [Rudloff/alltube#407]
# New issue
Getting an error when I try to download from CR, specifically this link but does it on all https://www.crunchyroll.com/ascendance-of-a-bookworm/episode-1-a-world-without-books-791023
![image](https://user-images.githubusercontent.com/21246660/161363840-e1ef5d53-c48a-47c4-ab3b-333eb7bf7463.png)

Also tried using docker as well with the same error

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Ubuntu 20.04.3 LTS

**What is your web server (Apache, IIS, etc.)?**
NGINX / Apache(Docker)

**What version of AllTube are you using?**
Latest

**How did you install AllTube (with Git or with a release package)?**
Git / Docker

**What version of PHP are you using?**
7.4

**What version of Python are you using?**
python2.7 / 3.8 / whatever is used in docker

**What version of youtube-dl are you using?**
Latest

**Do you get any PHP-related errors in your webserver's logs?**
No

**Comment by Rudloff** [comment]
I can't reproduce with 3.0.3 (and stream mode enabled).
Please note that the Docker image is not up to date (because automated builds is now a paid feature...).

**Comment by JReming85** [comment]
let me try updating again, thanks for letting me know about docker that was the main reason I thought I was on latest

**Comment by JReming85** [comment]
Yea working now, looks like I messed up when I was doing git commands to update it with master.

Had to download the zip for 3.0.3 and replace with that and now its working.
