### ISSUE TITLE
How to download YouTube to MP3 audio online?

### ISSUE THREAD

**Issue by zeref-dragneel** [Rudloff/alltube#411]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?** 

> Windows

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?** 

> alltubedownload.net

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

> https://alltubedownload.net/info?url=https%3A%2F%2Fyoutu.be%2FNnaOhS8TNOI

## Describe your issue

> No sound from downloaded videos, can you add audio download feature?

<img src="https://i.imgur.com/yqT2PWV.png" height="256">

**Comment by Rudloff** [comment]
Audio conversion is disabled on https://alltubedownload.net/ because it uses a lot of resources.
You can enable it if you host AllTube on your own server.
