### ISSUE TITLE
Conversion to MP3 not working - avconv not installed?

### ISSUE THREAD

**Issue by TimoVer** [Rudloff/alltube#42]
Hi Rudloff!

I have a home server running Ubuntu 15.10, apache2 installed, downloaded the alltube release and put it into the /var/www/html folder. Normal video/audio download is possible.

I also used the command you provided to enable avconv & ffmpeg:

<code>
sudo apt-get install libavcodec-extra rtmpdump
</code>

& enabled config to set conversion = true, but conversion is not working and gives me empty mp3 files. I also see in the provided config.php file that avconv path is vendor/bin/ffmpeg, but it is not present there.

Something else I need to do to enable conversion?

**Comment by Rudloff** [comment]
Hello,

The release package does not contain vendor/bin/ffmpeg because it is too big.
You have two solutions:
* Run `composer install` to download ffmpeg in vendor/
* Edit your config so that avconv points to your ffmpeg/avconv binary (probably /usr/bin/avconv)

**Comment by TimoVer** [comment]
Seems that the packages libavcodec-extra & rtmpdump do not include avconv (at least not on ubuntu 15.10). Was able to install avconv by installing package libav-tools (which also installs ffmpeg if not present) and then redirect config.yml to /usr/bin/avconv ;).

**Comment by Rudloff** [comment]
Oh you're right, I used the wrong package name in the README.
