### ISSUE TITLE
End of alltubedownload.net hosting

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/alltube#422]
https://alltubedownload.net/ is hosted on a free Heroku dyno and Heroku is stopping this service at the end of november: https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

I have no intention of paying to host this instance so I will probably let the hosting expire.

**Comment by jamesbruice** [comment]
What about using https://render.com/ or https://fly.io/?

**Comment by Rudloff** [comment]
I decided to not host an official instance anymore.
Anyone is of course free to host a public AllTube instance.

**Comment by tshpr** [comment]
How much it would cost to host it? I can takeover the instance and the domain if you want to keep it running.

**Comment by Rudloff** [comment]
Thanks but I will not maintain this app anymore (see https://github.com/Rudloff/alltube/issues/435).
