### ISSUE TITLE
Deployment Issue Heroku22

### ISSUE THREAD

**Issue by marvinto23** [Rudloff/alltube#430]
### What is your operating system (Windows, Linux, OSX, etc.)?

Heroku22

### What is your web server (Apache, IIS, etc.)?

Heroku22

### What version of AllTube are you using?

Latest

### How did you install AllTube?

Other (please specify)

### What version of PHP are you using?

Heroku Supported ones

### What version of Python are you using?

Heroku supported ones

### What version of youtube-dl are you using?

Latest

### Do you get any PHP-related errors in your webserver's logs?

```plain text
-----> Building on the Heroku-22 stack
-----> Using buildpacks:
       1. heroku/php
       2. heroku/python
-----> PHP app detected
-----> Bootstrapping...
-----> Preparing platform package installation...
-----> Installing platform packages...
 !     ERROR: Failed to install system packages!
 !     
 !     Your platform requirements (for runtimes and extensions) could
 !     not be resolved to an installable set of dependencies, or a
 !     platform package repository was unreachable.
 !     
 !     This usually means that you (or packages you are using) depend
 !     on a combination of PHP versions and/or extensions that are
 !     currently not available on Heroku.
 !     
 !     The following is the full output from the installation attempt:
 !     
 !     > Loading repositories with available runtimes and extensions
 !     > Updating dependencies
 !     > Your requirements could not be resolved to an installable set of packages.
 !     > 
 !     >   Problem 1
 !     >     - Root composer.json requires rinvex/countries v6.1.2 -> satisfiable by rinvex/countries[v6.1.2].
 !     >     - rinvex/countries v6.1.2 requires php ^7.2.0 -> found php[8.1.6, ..., 8.2.3] but it does not match the constraint.
 !     > 
 !     > Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
 !     
 !     For reference, the following runtimes are currently available:
 !     
 !     PHP:  8.2.3, 8.2.2, 8.2.1, 8.1.16, 8.1.15, 8.1.14, 8.1.13, 
 !     8.1.12, 8.1.11, 8.1.10, 8.1.9, 8.1.8, 8.1.7, 8.1.6
 !     
 !     Please verify that all requirements for runtime versions in
 !     'composer.lock' are compatible with the list above, and ensure
 !     all required extensions are available for the desired runtimes.
 !     
 !     When choosing a PHP runtimes and extensions, please also ensure
 !     they are available on your app's stack (heroku-22), and select
 !     a different stack if needed after consulting the article below.
 !     
 !     For a list of supported runtimes & extensions on Heroku, please
 !     refer to: https://devcenter.heroku.com/articles/php-support
 !     Push rejected, failed to compile PHP app.
 !     Push failed
```

### Please provide the URL of a video that causes the issue.

See screenshot

### Describe your issue

Hi Guys,

i get the following error on deployment on heroku22 do you habe any solution for that? Im not a real professional so ye

-----> Building on the Heroku-22 stack
-----> Using buildpacks:
       1. heroku/php
       2. heroku/python
-----> PHP app detected
-----> Bootstrapping...
-----> Preparing platform package installation...
-----> Installing platform packages...
 !     ERROR: Failed to install system packages!
 !     
 !     Your platform requirements (for runtimes and extensions) could
 !     not be resolved to an installable set of dependencies, or a
 !     platform package repository was unreachable.
 !     
 !     This usually means that you (or packages you are using) depend
 !     on a combination of PHP versions and/or extensions that are
 !     currently not available on Heroku.
 !     
 !     The following is the full output from the installation attempt:
 !     
 !     > Loading repositories with available runtimes and extensions
 !     > Updating dependencies
 !     > Your requirements could not be resolved to an installable set of packages.
 !     > 
 !     >   Problem 1
 !     >     - Root composer.json requires rinvex/countries v6.1.2 -> satisfiable by rinvex/countries[v6.1.2].
 !     >     - rinvex/countries v6.1.2 requires php ^7.2.0 -> found php[8.1.6, ..., 8.2.3] but it does not match the constraint.
 !     > 
 !     > Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
 !     
 !     For reference, the following runtimes are currently available:
 !     
 !     PHP:  8.2.3, 8.2.2, 8.2.1, 8.1.16, 8.1.15, 8.1.14, 8.1.13, 
 !     8.1.12, 8.1.11, 8.1.10, 8.1.9, 8.1.8, 8.1.7, 8.1.6
 !     
 !     Please verify that all requirements for runtime versions in
 !     'composer.lock' are compatible with the list above, and ensure
 !     all required extensions are available for the desired runtimes.
 !     
 !     When choosing a PHP runtimes and extensions, please also ensure
 !     they are available on your app's stack (heroku-22), and select
 !     a different stack if needed after consulting the article below.
 !     
 !     For a list of supported runtimes & extensions on Heroku, please
 !     refer to: https://devcenter.heroku.com/articles/php-support
 !     Push rejected, failed to compile PHP app.
 !     Push failed

**Comment by marvinto23** [comment]
Thanks, i now did it with cloudron, im wondering if there is a way to change the logo ? is there any config parameter? or where can i find the img folder to replace the picture?

**Comment by Rudloff** [comment]
Changing the logo is not supported.
