### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by paulchartres** [Rudloff/alltube#432]
### What is your operating system (Windows, Linux, OSX, etc.)?

Linux Debian

### What is your web server (Apache, IIS, etc.)?

Docker image

### What version of AllTube are you using?

Latest

### How did you install AllTube?

Docker

### What version of PHP are you using?

The one in the image

### What version of Python are you using?

The one in the image

### What version of youtube-dl are you using?

The one in the image

### Please provide the URL of a video that causes the issue.

https://www.youtube.com/watch?v=dQw4w9WgXcQ

### Describe your issue

I'm getting an error related to youtube-dl:  

```
'/usr/bin/python' 'vendor/ytdl-org/youtube-dl/youtube_dl/__main__.py' '--no-warnings' '--ignore-errors' '--flat-playlist' '--restrict-filenames' '--no-playlist' '--dump-single-json' 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' '-f' 'best[protocol=https]/best[protocol=http]/bestvideo[protocol=https]/bestvideo[protocol=http]' failed with this error:
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```  
  
Seems to be happening on every video I try.

**Comment by st-ivan** [comment]
hello.. sorry, new to github.. so how do i fix this? how do i switch to yt-dlp?

**Comment by Rudloff** [comment]
I switched the develop branch to yt-dlp, so the next release will use it and it should fix the bug you reported.
