### ISSUE TITLE
Object not found error (404)

### ISSUE THREAD

**Issue by TimoVer** [Rudloff/alltube#44]
Hi Rudloff!

I'm trying to install alltube on an arch linux server. Using standard apache & php installs, cloned git repository, installed using npm & composer install (needed to also manually install composer since xz support was only introced recently).

Index page showing up normally, but from the moment I insert any video url (youtube, cnn, etc...) and click the download button, I get an object not found error (see screenshot attached).

Any other setting I need to change in my apache/php install?
<img width="864" alt="error" src="https://cloud.githubusercontent.com/assets/7707120/13199679/16d0d566-d82c-11e5-86cf-a1ce8220a41f.PNG">

**Comment by TimoVer** [comment]
Pastebin of localhost-error_log: http://pastebin.com/EuQNxcSP

**Comment by Rudloff** [comment]
Hello,

It seems your ```composer install``` did not run correctly:
```
[Sat Feb 20 23:05:33.345678 2016] [:error] [pid 6940] [client 10.124.161.104:61383] PHP Warning:  require_once(/home/fileserver/Media/Network/nonsecure/alltube/vendor/autoload.php): failed to open stream: No such file or directory in /home/fileserver/Media/Network/nonsecure/alltube/index.php on line 15
```

Can you run ```composer install``` again and paste the output here?

**Comment by TimoVer** [comment]
Composer install seems fine to me... I think that log was still from when version of composer was installed that did not support xz...

Pastebin npm install log: http://pastebin.com/VUhvpinA
Pastebin composer install log: http://pastebin.com/yxrqVhdU

I also have an Ubuntu server install where I did succesfully install alltube. It seems that when a video is requested for the first time, smarty place video.tpl in the templates_c folder (with some kind of hash in front of it), but somehow it doesn't do that on my arch install...

**Comment by Rudloff** [comment]
Apache seems to return a 404 error so it could be that URL rewriting is not working correctly.
Can you check the AllowOverride setting in your Apache config. It needs to be set to All or FileInfo.

**Comment by TimoVer** [comment]
Sometimes errors are found in small places... I use virtual hosts in Apache to /srv/http/html (with Allow Override All) but the main config file has a /srv/http host with Allow Override None. Setting it to All fixed the issue! Thanks!

**Comment by Rudloff** [comment]
I added something about it to the README: https://github.com/Rudloff/alltube/commit/8d46da3b6f8d0cc3e9f70818d8e7065b3d6d215b
