### ISSUE TITLE
Generic param

### ISSUE THREAD

**Issue by Kaos1337** [Rudloff/alltube#45]
Hi,
I've the necessity to to add the param "-4" (to force the ipv4). I added it into the params configuration but, if an user downloads the mp3, there is a command (... __main__.py --get-filename http...) that isn't affected by "params", then a command that hasn't the added flag (-4), can you set a configuration that is generic for every command of youtube-dl?
The same problem when into the FrontController there is the command "curl --user-agent", without the needed param.
Regards.

**Comment by Rudloff** [comment]
Hello,

It has been fixed on the develop branch, the custom flags are now used everytime youtube-dl is called.
And you can now use the curl_params setting to add your custom curl flags.

Regards,

**Comment by Rudloff** [comment]
Please note that on the develop branch `params` and `curl_params` are now arrays instead of strings: https://github.com/Rudloff/alltube/blob/develop/config.example.yml
