### ISSUE TITLE
"No input file specified." error on download 

### ISSUE THREAD

**Issue by Issam2204** [Rudloff/alltube#52]
When I click on the download button I have the following error:

> No input file specified.

Nginx error log:

> 2016/05/05 16:32:39 [error] 16099#0: *18 FastCGI sent in stderr: "Unable to open primary script: /var/www/html/index.php (No such file or directory)" while reading response header from upstream, client: 213.213.229.32, server: SERVER.net, request: "GET /alltube/bower_components/opensans-googlefont/OpenSans-Regular.ttf HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "SERVER.net", referrer: "https://SERVER.net/alltube/dist/main.css"

>2016/05/05 16:32:39 [error] 16099#0: *13 FastCGI sent in stderr: "Unable to open primary script: /var/www/html/index.php (No such file or directory)" while reading response header from upstream, client: 213.213.229.32, server: SERVER.net, request: "GET /alltube/bower_components/opensans-googlefont/OpenSans-Light.ttf HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "SERVER.net", referrer: "https://SERVER.net/alltube/dist/main.css"

>2016/05/05 16:32:42 [error] 16099#0: *18 FastCGI sent in stderr: "Unable to open primary script: /var/www/html/index.php (No such file or directory)" while reading response header from upstream, client: 213.213.229.32, server: SERVER.net, request: "GET /alltube/video?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DNV59LloZ0WY HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "SERVER.net", referrer: "https://SERVER.net/alltube/"

This is my Nginx server conf:

>server {
  listen 80;
  server_name SERVER.net www.SERVER.net;
  return 301 https://$host$request_uri;
}
>
>server {
  listen 443 ssl;
  server_name SERVER.net www.SERVER.net;
>
>  ssl_certificate /etc/letsencrypt/live/SERVER.net/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/SERVER.net/privkey.pem;
>
>  root /var/www/html;
  index index.php index.html index.htm;
>
>  rewrite ^(.*\.php)(/)(.*)$ $1?file=/$3 last;
>
>  location / {
    # try_files $uri $uri/ =404;
    try_files $uri $uri/ /index.php?q=$uri&$args;
  }
>
>  location ^~ /.well-known/ {
    allow all;
  }
>
>  location ~ [^/]\.php(/|$) {
    fastcgi_split_path_info  ^(.+\.php)(/.+)$;
    fastcgi_index            index.php;
    fastcgi_pass             unix:/var/run/php5-fpm.sock;
    include                  fastcgi_params;
    fastcgi_param   PATH_INFO       $fastcgi_path_info;
    fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
   }
}

Could you please give me a hand to fix this issue?

**Comment by Rudloff** [comment]
I don't know much about Nginx but it seems it can't find your Alltube folder:
`Unable to open primary script: /var/www/html/index.php (No such file or directory)`

Can you check that the _root_ parameter in your Nginx config really points to where Alltube is installed?

**Comment by Issam2204** [comment]
Thanks for the answer.

My Nginx web root folder is indeed /var/www/html

Alltube is installed in /var/www/html/alltube

I access it by https://myserver.net/alltube

Why Nginx searches for the index.php in the root instead of the Alltube folder?

**Comment by Issam2204** [comment]
I was able to fix it with this: https://github.com/Rudloff/alltube/issues/47

Basically I had to create a subdomain for Alltube.

Thanks!
