### ISSUE TITLE
CSS File not found

### ISSUE THREAD

**Issue by xoxys** [Rudloff/alltube#55]
Hi,

im trying to run alltube on CentOS with nginx. The problem is, alltube cant find CSS and JS files:
```
2016/05/16 01:24:30 [error] 17407#17407: *16 open() "/var/www/.../alltube/dist/main.css" failed (2: No such file or directory)
2016/05/16 01:24:30 [error] 17407#17407: *16 open() "/var/www/.../alltube/dist/main.js" failed (2: No such file or directory)

```
Any idea? Thanks for your help.

**Comment by Rudloff** [comment]
What version of Alltube are you runinng?
The [packaged zip release](https://github.com/Rudloff/alltube/releases/download/0.4.5/alltube-release.zip) includes these files but if you are using the Git branch directly, you need to run Grunt in order to build the files in the dist/ folder:
```
npm install
grunt
```

**Comment by xoxys** [comment]
You are right i have cloned the git. After running grunt it works great. Thank you so much :-)
