### ISSUE TITLE
Docker: keep Alltube running

### ISSUE THREAD

**Issue by R0GGER** [Rudloff/alltube#59]
I had a problem with keeping it running in Docker...
Found the problem the CMD line should be changed to `/bin/sh -c "/usr/sbin/apache2ctl -D FOREGROUND"`.

**Dockerfile:**
`CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]`

More info: https://coreos.com/os/docs/latest/getting-started-with-docker.html#run-apache-in-foreground

**Comment by Rudloff** [comment]
What version of Alltube are you running? Did you build the Docker image yourself?
If you build the docker image from the develop branch (`docker build .`), it should work correctly as it is based on the php:5.6-apache image which does use `-D FOREGROUND`.

**Comment by R0GGER** [comment]
The latest version of the Master branch.

It's a known error:
> AH00170: caught SIGWINCH, shutting down gracefully    
More info: https://github.com/docker-library/php/issues/64

**Comment by R0GGER** [comment]
Testing Develop version now... I will let you know.

**Comment by R0GGER** [comment]
Dev is ok.

**Comment by Rudloff** [comment]
I can reproduce your issue with SIGWINCH but according to the Apache team, this is not a bug: https://bz.apache.org/bugzilla/show_bug.cgi?id=50669
I know it is annoying but adding your CMD to the Dockerfile makes it ignore all signals, which is not a good thing IMHO.

I think the easiest solution if you want to ignore signales is to launch `docker run` with `--sig-proxy=false`.
However the clean way to run Apache in Docker is with `docker run -d`.

**Comment by R0GGER** [comment]
I agree... I will test some more.
