### ISSUE TITLE
i have problem with installation [HELP]

### ISSUE THREAD

**Issue by yas9999** [Rudloff/alltube#61]
Hello,
i have this problem when i run: composer install

 Problem 1
    - Installation request for jeremykendall/php-domain-parser 3.0.0 -> satisfiable by jeremykendall/php-domain-parser[3.0.0].
    - jeremykendall/php-domain-parser 3.0.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 2
    - Installation request for league/uri 4.1.0 -> satisfiable by league/uri[4.1.0].
    - league/uri 4.1.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 3
    - league/uri 4.1.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - rudloff/smarty-plugin-noscheme 0.1.0 requires league/uri ~4.0 -> satisfiable by league/uri[4.1.0].
    - Installation request for rudloff/smarty-plugin-noscheme 0.1.0 -> satisfiable by rudloff/smarty-plugin-noscheme[0.1.0].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php5/cli/php.ini
    - /etc/php5/cli/conf.d/05-opcache.ini
    - /etc/php5/cli/conf.d/10-pdo.ini
    - /etc/php5/cli/conf.d/20-curl.ini
    - /etc/php5/cli/conf.d/20-json.ini
    - /etc/php5/cli/conf.d/20-mysql.ini
    - /etc/php5/cli/conf.d/20-mysqli.ini
    - /etc/php5/cli/conf.d/20-pdo_mysql.ini
    - /etc/php5/cli/conf.d/20-readline.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
i have Ubuntu 14.04.4 LTS 64bit + nodejs v4.4.7

please help me

**Comment by Rudloff** [comment]
Hello,
You probably need to install `php5-intl`.

**Comment by yas9999** [comment]
Thank you so much Rudloff but i still have some unknown issues maybe some .css files !
please check http://195.154.117.122/
also please test to download something from youtube

**Comment by Rudloff** [comment]
You need to run `npm install` in order to generate the CSS files. If that doesn't work, please paste the output here.

You can't download videos from Youtube because the version of youtube-dl used on the master branch is quite old.
I just published a new release that uses a more recent version of youtube-dl so you should use that instead: https://github.com/Rudloff/alltube/releases/tag/0.5.0
(You will have to run `composer install` again.)

**Comment by yas9999** [comment]
thank you Rudloff,
i just downloaded v 0.5.0 & css work without nmp install but once i run it i got this error :
sudo npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path /var/www/html/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/var/www/html/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/npm-debug.log

also for composer install : there is no composer.json in zip file (https://github.com/Rudloff/alltube/releases/tag/0.5.0)

PS:  how can i activate audio only (mp3) http://imgur.com/a/GolCq
regards,

**Comment by Rudloff** [comment]
As explained in README.md, if you download a release zip, you don't need to run npm and composer.
But if you download from git (which I assumed you did in your first post), you do need to run them.

In order to enable audio conversion, you need to add this to your `config.yml` file:
```yaml
convert: true
```
You will also need to install `avconv` and `curl` on your server:
```bash
sudo apt-get install libav-tools curl
```

**Comment by yas9999** [comment]
Hello yes i had activate it but once i hit download for mp3 format i got this error :
![image](https://cloud.githubusercontent.com/assets/5939771/17196089/f7a8f33a-5459-11e6-8b30-e2984ffac7c0.png)

:(

**Comment by Rudloff** [comment]
Can you provide some error log from your web server please ?

**Comment by yas9999** [comment]
i'm not so good about linux, but i can't download mp3 files if you have an email i can send you ssh access !

**Comment by Rudloff** [comment]
What web server are you using? If it is Apache, you need to look at `/var/log/apache2/error.log` and see if there are any errors that appear when your try to convert a file. If there are, please paste them here.

**Comment by yas9999** [comment]
this is what i got !

[Wed Jul 27 00:52:55.591001 2016] [mpm_event:notice] [pid 5713:tid 139954758760320] AH00489: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Wed Jul 27 00:52:55.592050 2016] [core:notice] [pid 5713:tid 139954758760320] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 27 00:53:11.690881 2016] [mpm_event:notice] [pid 5713:tid 139954758760320] AH00491: caught SIGTERM, shutting down
[Wed Jul 27 00:53:12.879210 2016] [mpm_prefork:notice] [pid 7617] AH00163: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Wed Jul 27 00:53:12.881529 2016] [core:notice] [pid 7617] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 27 00:53:13.527734 2016] [mpm_prefork:notice] [pid 7617] AH00169: caught SIGTERM, shutting down
[Wed Jul 27 00:53:14.857809 2016] [mpm_prefork:notice] [pid 7701] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 configured -- resuming normal operations
[Wed Jul 27 00:53:14.857965 2016] [core:notice] [pid 7701] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 27 00:54:04.769343 2016] [mpm_prefork:notice] [pid 7701] AH00169: caught SIGTERM, shutting down
[Wed Jul 27 00:54:05.940191 2016] [mpm_prefork:notice] [pid 7788] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 configured -- resuming normal operations
[Wed Jul 27 00:54:05.940377 2016] [core:notice] [pid 7788] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 27 00:56:29.986975 2016] [mpm_prefork:notice] [pid 7788] AH00169: caught SIGTERM, shutting down
[Wed Jul 27 00:56:31.561469 2016] [mpm_prefork:notice] [pid 8355] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 configured -- resuming normal operations
[Wed Jul 27 00:56:31.561643 2016] [core:notice] [pid 8355] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 27 01:04:45.238926 2016] [:error] [pid 8359] [client 66.249.75.132:62248] PHP Warning:  require_once(/var/www/html/vendor/autoload.php): failed to open stream$
[Wed Jul 27 01:04:45.239075 2016] [:error] [pid 8359] [client 66.249.75.132:62248] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/vendor/auto$
[Wed Jul 27 01:11:13.882659 2016] [:error] [pid 8360] [client 105.154.113.166:65064] PHP Warning:  require_once(/var/www/html/vendor/autoload.php): failed to open stre$
[Wed Jul 27 01:11:13.882819 2016] [:error] [pid 8360] [client 105.154.113.166:65064] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/vendor/au$
[Wed Jul 27 01:11:16.737423 2016] [:error] [pid 8361] [client 105.154.113.166:65065] PHP Warning:  require_once(/var/www/html/vendor/autoload.php): failed to open stre$
[Wed Jul 27 01:11:16.737569 2016] [:error] [pid 8361] [client 105.154.113.166:65065] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/vendor/au$
[Wed Jul 27 01:14:30.587824 2016] [mpm_prefork:notice] [pid 8355] AH00169: caught SIGTERM, shutting down
[Wed Jul 27 01:14:31.773011 2016] [mpm_prefork:notice] [pid 13333] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 configured -- resuming normal operations
[Wed Jul 27 01:14:31.773199 2016] [core:notice] [pid 13333] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 27 01:19:46.919358 2016] [mpm_prefork:notice] [pid 13333] AH00169: caught SIGTERM, shutting down
[Wed Jul 27 01:19:48.107548 2016] [mpm_prefork:notice] [pid 13426] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 configured -- resuming normal operations
[Wed Jul 27 01:19:48.107722 2016] [core:notice] [pid 13426] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 27 01:20:00.812242 2016] [:error] [pid 13430] [client 105.154.113.166:65217] PHP Warning:  require_once(/var/www/html/vendor/autoload.php): failed to open str$
[Wed Jul 27 01:20:00.812442 2016] [:error] [pid 13430] [client 105.154.113.166:65217] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/vendor/a$
[Wed Jul 27 01:20:03.713315 2016] [:error] [pid 13431] [client 105.154.113.166:65218] PHP Warning:  require_once(/var/www/html/vendor/autoload.php): failed to open str$
[Wed Jul 27 01:20:03.713455 2016] [:error] [pid 13431] [client 105.154.113.166:65218] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/vendor/a$
[Wed Jul 27 01:24:21.151363 2016] [mpm_prefork:notice] [pid 13426] AH00169: caught SIGTERM, shutting down
[Wed Jul 27 01:24:22.344790 2016] [mpm_prefork:notice] [pid 13520] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 configured -- resuming normal operations
[Wed Jul 27 01:24:22.345068 2016] [core:notice] [pid 13520] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 27 01:46:29.259332 2016] [:error] [pid 13524] [client 195.117.119.225:53515] PHP Warning:  require_once(/var/www/html/vendor/autoload.php): failed to open str$
[Wed Jul 27 01:46:29.259506 2016] [:error] [pid 13524] [client 195.117.119.225:53515] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/vendor/a$
[Wed Jul 27 01:46:46.991722 2016] [:error] [pid 13525] [client 187.108.212.204:54608] PHP Warning:  require_once(/var/www/html/vendor/autoload.php): failed to open str$
[Wed Jul 27 01:46:46.991889 2016] [:error] [pid 13525] [client 187.108.212.204:54608] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/vendor/a$
[Wed Jul 27 01:53:58.735783 2016] [mpm_prefork:notice] [pid 13520] AH00169: caught SIGTERM, shutting down
[Wed Jul 27 01:53:59.939996 2016] [mpm_prefork:notice] [pid 14314] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 configured -- resuming normal operations

**Comment by Rudloff** [comment]
Hum, there's nothing helpful here.
Maybe you are affected by #62.
Can you try to apply [this change](https://github.com/Rudloff/alltube/commit/ae241a9812385c0240523525193111c6efecdbe8) to ` classes/Config.php`, please?

**Comment by Rudloff** [comment]
You also need to make sure that the `avconv` parameter in `config.yml` points to a avconv or ffmpeg binary.

**Comment by yas9999** [comment]
yes it's working good :smile: 
![image](https://cloud.githubusercontent.com/assets/5939771/17196836/60f02d22-545f-11e6-8b7e-8d4d01c191ff.png)
but download speed is a low i'm using a dedicated server with 1Gbps

**Comment by Rudloff** [comment]
Your download speed is probably limited by the speed at which your server can convert audio.

If everything is working, I'm closing the issue.

**Comment by yas9999** [comment]
thank you so much bro :smile:
