### ISSUE TITLE
Error 500 on audio only

### ISSUE THREAD

**Issue by SphinxTwo** [Rudloff/alltube#62]
So I have just recently updated to the latest version of alltube, now I have an error when I try to set the conversion/download to audio only.
Also, I have noticed that while pressing on Download via the video download page, the browser just redirects to the link of the video and is then played by the browser.
Anyways, here is the error message from my log, hopefully someone can help.

> PHP message: PHP Catchable fatal error:  Argument 1 passed to Symfony\Component\Process\ProcessBuilder::create() must be of the type array, null given, called in /var/www/html/all/controllers/FrontController.php on line 208 and defined in /var/www/html/all/vendor/symfony/process/ProcessBuilder.php on line 51" while reading response header from upstream, client: editedoutclientiphere server: tube.thebeast.tech, request: "GET /video?url=https%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPL2JiZAV5BmDXiLQ8I-pIG58ykUL6ee71Z&audio=on HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "tube.thebeast.tech"

**Comment by Rudloff** [comment]
Hello,
I pushed a new commit on develop that should fix this bug: https://github.com/Rudloff/alltube/commit/ae241a9812385c0240523525193111c6efecdbe8
Can you try it please?

About the browser playing the videos, we currently have no way to force the browser the download a video. (But you can always do File > Save to or ctrl + S to download it.)

**Comment by SphinxTwo** [comment]
Alright. I'll check this out as soon as possible. Thanks for the reply.

**Comment by SphinxTwo** [comment]
It works, however for some reason, doing the _git pull_ command didn't update the file unless I am doing something wrong. I just manually added that line myself.
