### ISSUE TITLE
[info] recommended server performance 

### ISSUE THREAD

**Issue by yas9999** [Rudloff/alltube#69]
Hello @Rudloff ,
can i have some information about your server because it's run fast & smooth no like mine !
i need to wait 20-30s to extract audio from  4 min video
i have a dedicated server from oneprovider with 2GB ram, 1Gbps connection speed & CPU VIA Nano U2250 1.6Ghz

i guess the problem come from my CPU !

Best regards,

**Comment by Rudloff** [comment]
Hello,
alltubedownload.net runs on a free [Heroku](https://www.heroku.com/) instance.
We also use [Cloudflare](https://www.cloudflare.com/fr/) but that should only be required if you have a lot of users.
