### ISSUE TITLE
Extract Audio as MP3 using FFMPEG?

### ISSUE THREAD

**Issue by firmanelhakim** [Rudloff/alltube#7]
Hi,

Could you please suggest how to integrate this command line into your script:

youtube-dl --extract-audio --audio-format mp3 videoURL

So that we can download the video as MP3 file (by converting it using FFMPEG).

Thanks.

**Comment by Rudloff** [comment]
We had this functionality before but had to disable it on our server. I added it back.
Beware that it can use a lot of resources on your server.

**Comment by firmanelhakim** [comment]
Thanks for the update.

I have checked the codes that you committed recently.

There are two options:
1. Using rtmpdump and pass it to avconv
2. Download using wget and pass it to avconv 

My question is, instead of those two approaches, could we use the native solution that has been provided by youtube-dl?

youtube-dl --extract-audio --audio-format mp3 videoURL

Thanks.

**Comment by Rudloff** [comment]
With my code, the MP3 file is streamed to the browser.
The youtube-dl command would only write the file on the server.

**Comment by firmanelhakim** [comment]
Which one do you think that is using less resources?

**Comment by Rudloff** [comment]
They both use FFMPEG/Avconv so I don't think there is much of a difference.
