### ISSUE TITLE
Call to undefined function 

### ISSUE THREAD

**Issue by Mysterius** [Rudloff/alltube#70]
Hello,

I tried installing alltube from the latest release package but when I access the page it triggers an error 500 and writes this in the logs :

[Sun Oct 09 09:58:08.618731 2016] [:error] [pid 3280] Slim Application Error:\nType: Error\nMessage: Call to undefined function League\\Uri\\Components\\idn_to_ascii()\nFile: /var/www/html/cabanon/alltube/vendor/league/uri/src/Components/HostnameTrait.php\nLine: 60\nTrace: #0 [internal function]: League\\Uri\\UriParser->League\\Uri\\Components\\{closure}('www')\n#1 /var/www/html/cabanon/alltube/vendor/league/uri/src/Components/HostnameTrait.php(61): array_map(Object(Closure), Array)\n#2 /var/www/html/cabanon/alltube/vendor/league/uri/src/UriParser.php(178): League\\Uri\\UriParser->validateStringHost('www.moncabanon....')\n#3 /var/www/html/cabanon/alltube/vendor/league/uri/src/UriParser.php(162): League\\Uri\\UriParser->filterHost('www.moncabanon....')\n#4 /var/www/html/cabanon/alltube/vendor/league/uri/src/UriParser.php(142): League\\Uri\\UriParser->parseHostname('moc.nonabacnom....')\n#5 /var/www/html/cabanon/alltube/vendor/league/uri/src/UriParser.php(82): League\\Uri\\UriParser->parseAuthority('//www.moncabano...')\n#6 /var/www/html/cabanon/alltube/vendor/league/uri/src/UriParser.php(67): League\\Uri\\UriParser->parse('http://www.monc...')\n#7 /var/www/html/cabanon/alltube/vendor/league/uri/src/Schemes/Generic/AbstractHierarchicalUri.php(88): League\\Uri\\UriParser->__invoke('http://www.monc...')\n#8 /var/www/html/cabanon/alltube/vendor/rudloff/smarty-plugin-noscheme/modifier.noscheme.php(22): League\\Uri\\Schemes\\Generic\\AbstractHierarchicalUri::createFromString('http://www.monc...')\n#9 /var/www/html/cabanon/alltube/templates_c/e463faa883b9c1c4bab2c7984a28361f696f8224_0.file.head.tpl.php(39): Smarty_Modifier_noscheme('http://www.monc...')\n#10 /var/www/html/cabanon/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_57f9f8909593a0_38723893(Object(Smarty_Internal_Template))\n#11 /var/www/html/cabanon/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(170): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))\n#12 /var/www/html/cabanon/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(184): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))\n#13 /var/www/html/cabanon/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(350): Smarty_Internal_Template->render()\n#14 /var/www/html/cabanon/alltube/templates_c/b63323dd23af971c731df177ebd832814ba4230c_0.file.index.tpl.php(27): Smarty_Internal_Template->_subTemplateRender('file:inc/head.t...', NULL, NULL, 0, 3600, Array, 0, false)\n#15 /var/www/html/cabanon/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_57f9f890930b46_07126122(Object(Smarty_Internal_Template))\n#16 /var/www/html/cabanon/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(170): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))\n#17 /var/www/html/cabanon/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(184): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))\n#18 /var/www/html/cabanon/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(199): Smarty_Internal_Template->render(false, 0)\n#19 /var/www/html/cabanon/alltube/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(99): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)\n#20 /var/www/html/cabanon/alltube/vendor/mathmarques/smarty-view/src/Smarty.php(113): Smarty_Internal_TemplateBase->fetch('index.tpl')\n#21 /var/www/html/cabanon/alltube/vendor/mathmarques/smarty-view/src/Smarty.php(126): Slim\\Views\\Smarty->fetch('index.tpl', Array)\n#22 /var/www/html/cabanon/alltube/controllers/FrontController.php(68): Slim\\Views\\Smarty->render(Object(Slim\\Http\\Response), 'index.tpl', Array)\n#23 [internal function]: Alltube\\Controller\\FrontController->index(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#24 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#25 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/Route.php(325): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#26 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#27 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/Route.php(297): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#28 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/App.php(443): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#29 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#30 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/App.php(337): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#31 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/App.php(298): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#32 /var/www/html/cabanon/alltube/index.php(47): Slim\\App->run()\n#33 {main}\nView in rendered output by enabling the "displayErrorDetails" setting.\n

[Sun Oct 09 09:58:08.618910 2016] [:error] [pid 3280] PHP Fatal error:  Uncaught RuntimeException: Unexpected data in output buffer. Maybe you have characters before an opening <?php tag? in /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/App.php:552\nStack trace:\n#0 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/App.php(344): Slim\\App->finalize(Object(Slim\\Http\\Response))\n#1 /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/App.php(298): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#2 /var/www/html/cabanon/alltube/index.php(47): Slim\\App->run()\n#3 {main}\n  thrown in /var/www/html/cabanon/alltube/vendor/slim/slim/Slim/App.php on line 552

Any idea? :)
The server is running Apache. Mime and rewrite are enabled.

**Comment by Rudloff** [comment]
Hello,
You probably need to install PHP intl module (php5-intl on Debian).

**Comment by Mysterius** [comment]
You were right. It works with php intl. I have other problems now (blank page when downloading from youtube, 403 error when downloading from dailymotion) but I'll just take some time to look around for solutions.

Thanks

**Comment by Rudloff** [comment]
If you are not running Alltube locally, this is probably due to this known issue: https://github.com/Rudloff/alltube/issues/39

**Comment by Mysterius** [comment]
Oh... I see ! So that means Alltube won't be useful to me then :/. I wanted to use it to be able to easily download videos when i'm at work. Thanks Pierre :)
