### ISSUE TITLE
[enhancement] store media in hard drive

### ISSUE THREAD

**Issue by yas9999** [Rudloff/alltube#71]
Hello @Rudloff , 

i wonder about video download can it be like download video to server then serve it to users since some hosts like dailymontion youtube & others don't allow us to download

Best regards,

**Comment by Rudloff** [comment]
The feature/stream branch does that but as explained in #39, we won't merge that in the master branch because it uses too much resources.

**Comment by yas9999** [comment]
hùm i don't thing so because this is not what i mean.
what i mean that the user will wait until the video be downloaded in the server then he will got download URL
PS: this will be not friendly with large size maybe more than 60 Mb, because there is no download progress bar xD

regards,

**Comment by Rudloff** [comment]
Well, this is clearly out of the scope of this project, as it would require a lot of disk space and would also raise some legal concerns if we are hosting copyrighted videos.

You should try this project that seems to do what you need: https://github.com/manbearwiz/youtube-dl-server

**Comment by yas9999** [comment]
yeah you have right about legal concerns thank you so much @Rudloff for everything :+1:
