### ISSUE TITLE
Distribute a ready-to-use package

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/alltube#8]
Some people asked for a download with youtube-dl included.

**Comment by nodiscc** [comment]
@Rudloff you can attach arbitrary zip files to Github releases https://github.com/blog/1547-release-your-software (include the youtube-dl binary there)

**Comment by Rudloff** [comment]
Thanks for the doc!
I have uploaded a zip file with the youtube-dl binary and minified CSS/JS: https://github.com/Rudloff/alltube/releases/tag/0.2.1
