### ISSUE TITLE
Twitter videos error

### ISSUE THREAD

**Issue by HyShai** [Rudloff/alltube#84]
When trying to download a twitter video (e.g. https://twitter.com/verge/status/813055465324056576/video/1) , I get this error:
```
An error occured

Please check the URL of your video.
ERROR: requested format not available
``` 

(I tried settinf the ffmpeg binary path and convert: true - doesn't make a difference)

**Comment by Rudloff** [comment]
Twitter serves [an M3U8 file](https://video.twimg.com/amplify_video/800836371413811202/pl/1280x720/_Z4RxZh_muysb9Ir.m3u8) which means the video can't be easily downloaded with a browser so this format is currently disabled in Alltube.

**Comment by HyShai** [comment]
Perhaps the same way audio conversion (via avconv) is supported - m3u8 files can be piped through ffmpeg/avconv also?

**Comment by Rudloff** [comment]
The `feature/stream` branch actually does that with HTTP streams.
I updated it to support M3U8 streams as well. It is still pretty experimental but you can try it.
