### ISSUE TITLE
Feature Request: Set Download Location

### ISSUE THREAD

**Issue by jpartain89** [Rudloff/alltube#85]
A major use for a web-based youtube-dl, I'd think, would be specifically for downloading videos to the server hosting the alltube page/service.... Right? 

Not only would I be able to have all files automatically downloaded to my media server, but it would also be using the network connection best suited for these downloads, rather than running through the web browser. 

To whit, if this feature is added, the possibility of having a user-auth service would be beneficial as well, obviously. Or, just add "basic auth" information for the nginx web server configuration. 

But, the "download to location on server" option would be so so amazing.

**Comment by Rudloff** [comment]
Sorry but this is out of the scope of this project. We focus on downloading videos with the browser.
I think an app that downloads to the server would require a pretty different UI (e.g. a list of all your downloads) and it needs some restrictions (auth, disk quotas, max download speed, etc.).

If you can write PHP code, there are libraries you can use to download to your server:
* https://github.com/norkunas/youtube-dl-php
* https://github.com/labzone/Youtube-dl-php
