### ISSUE TITLE
Not parsing available formats for some sites (eg: Naver/ODK)

### ISSUE THREAD

**Issue by melrhombus** [Rudloff/alltube#91]
If I run youtube-dl from cli I get this output
youtube-dl --list-formats http://www.ondemandkorea.com/kpop-star-season-6-e14.html
[OnDemandKorea] kpop-star-season-6-e14: Downloading webpage
[OnDemandKorea] kpop-star-season-6-e14: Downloading m3u8 information
[info] Available formats for kpop-star-season-6-e14:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL
hls-408      mp4        320x180     408k , avc1.77.30@ 260k, mp4a.40.2@125k
hls-567      mp4        416x234     567k , avc1.77.30@ 410k, mp4a.40.2@125k
hls-896      mp4        640x360     896k , avc1.100.30@ 720k, mp4a.40.2@125k
hls-1362     mp4        640x360    1362k , avc1.100.31@1160k, mp4a.40.2@125k
hls-1903     mp4        960x540    1903k , avc1.100.31@1670k, mp4a.40.2@125k
hls-2666     mp4        1280x720   2666k , avc1.100.31@2390k, mp4a.40.2@125k
hls-5485     mp4        1920x1080  5485k , avc1.100.40@5050k, mp4a.40.2@125k (best)

If I run it through the gui front end I get [this](http://imgur.com/a/CemeI) and if I hit download I get requested format not available

Now, if I run what I'm assuming is being pushed to youtube-dl
youtube-dl -f best[protocol^=http] http://www.ondemandkorea.com/kpop-star-season-6-e14.html
[OnDemandKorea] kpop-star-season-6-e14: Downloading webpage
[OnDemandKorea] kpop-star-season-6-e14: Downloading m3u8 information
ERROR: requested format not available

If I remove the -f and run this from cli it works
youtube-dl http://www.ondemandkorea.com/kpop-star-season-6-e14.html
[OnDemandKorea] kpop-star-season-6-e14: Downloading webpage
[OnDemandKorea] kpop-star-season-6-e14: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 437
[download] Destination: KPOP STAR Season 6  - E08- Part2-kpop-star-season-6-e14.mp4
[download]   0.3% of ~2.83GiB at  2.00MiB/s ETA 16:35^C

I tried removing the -f from the config.yml but same error... I'm guessing it plugs "best" in regardless and I don't have the detailed formats to pick anything aside from best/worst

I noticed the same issue with Naver
Using the GIT version of alltube

**Comment by Rudloff** [comment]
Hello,
I can't really test because this video is not available in my country. Do you have any other URL that I could use?

But it is probably because it is an M3U8  video and we disable those in Alltube because a browser doesn't know how to download this kind of stream.
You can however try the experimental feature/stream Git branch that should be able to stream M3U8 to your browser.

**Comment by melrhombus** [comment]
Here's another one tvcast.naver.com/v/1326531
Same issue... blank detailed media

youtube-dl --list-formats tvcast.naver.com/v/1326531
WARNING: The url doesn't specify the protocol, trying with http
[Naver] 1326531: Downloading webpage
[Naver] 1326531: Downloading JSON metadata
[info] Available formats for 1326531:
format code                extension  resolution note
avc1_270P_480_500_128      mp4        480x270     359k video@ 263k, audio@ 96k, 46.05MiB
avc1_360P_640_650_96       mp4        640x360     525k video@ 429k, audio@ 96k, 67.09MiB
avc1_480P_854_1024_128     mp4        854x480     692k video@ 564k, audio@128k, 88.43MiB
avc1_720P_1280_2048_192_B  mp4        1280x720   1298k video@1106k, audio@192k, 165.47MiB
avc1_1080P_1920_5120_192   mp4        1920x1080  2728k video@2536k, audio@192k, 347.48MiB (best)

I'll give the experimental branch a try and let you know... tks!

**Comment by Rudloff** [comment]
`tvcast.naver.com/v/1326531` redirects me to http://tv.naver.com/v/1326531 which is not supported by youtube-dl:
```
[generic] 1326531: Requesting header
WARNING: Could not send HEAD request to http://tv.naver.com/v/1326531: HTTP Error 403: Forbidden
[generic] 1326531: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 1326531: Extracting information
ERROR: Unsupported URL: http://tv.naver.com/v/1326531
```

**Comment by melrhombus** [comment]
What causes the redirect?
If I used youtube-dl directly that doesn't happen

**Comment by Rudloff** [comment]
OK, I don't really get why it redirects my browser and not youtube-dl but anyway it seems to be an upstream issue: https://github.com/rg3/youtube-dl/issues/11720

**Comment by melrhombus** [comment]
Well that was a quick turn around...
I'll update my youtube-dl and see how it goes

Thanks for all the help!

**Comment by Rudloff** [comment]
I can't reproduce. With the latest youtube-dl master, I get the correct formats in Alltube.
Are you sure your build works correctly? Does it work if you run `youtube-dl --get-url http://tvcast.naver.com/v/1326531 -f best[protocol^=http]`?

**Comment by melrhombus** [comment]
Just ran a clean/make all and copied the file over
Works!! I see a list now and it pulls the file

Tks again for the help!
