### ISSUE TITLE
[QUESTION] How to update when using develop branch & git pull?

### ISSUE THREAD

**Issue by TimoVerbrugghe** [Rudloff/alltube#95]
Hi Rudloff,

Recently started using this project again to have my own instance of alltube on my private server. Cloned the develop branch (living on the edge).

Since my knowledge around coding (& npm/composer/web based languages) is extremely limited, I was wondering if outside of git pull, I still need to do something to get everything updated.

Do I need to run npm install/composer install again after git pull? Something else?

Thanks

**Comment by Rudloff** [comment]
Hello,

You need to run npm and Composer again, in case some dependencies have been updated.
I added a note about that in the README: https://github.com/Rudloff/alltube/blob/develop/README.md#update

**Comment by TimoVerbrugghe** [comment]
Ah perfect! Thanks man! Using a systemd  file to  automatically update git repos, will add  it.
