### ISSUE TITLE
Bypass geoip restrictions

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/alltube#97]
Ideas:
* Use free SOCKS proxies
* Use TOR

**Comment by yas9999** [comment]
i guess free SOCKS proxies & TOR will be not good idea if there is more than 100 users / hour ...
however Admin can buy multiple cheap VPS from different location like digitalocean, or buy multiple premium Proxies that allow high speed (not recommended u will banned if u abuse bandwidth )
also i believe there is an option to add proxy directly youtube-dl config file

**Comment by Rudloff** [comment]
We currently have ~1000 visitors/day but the idea is not to use a proxy for every request but only if a specific video needs it (probably with a checkbox that will enable youtube-dl's `--geo-verification-proxy` option).
The proxy/VPN won't be used for downloading the actual video file, only for extracting the video URL.

I agree VPS are the way to go if we want good performances but:
* This is a free time project and I don't want to invest money in it.
* I want to implement a solution that can be used on self-hosted instances of Alltube as well.

**Comment by yas9999** [comment]
yeah you have right if Youtube allow us to download with different IP address: IP-1 to extract video URL & IP-2 to download video.
also implement alltube in a self-hosted instance is actually a great idea 👍

**Comment by Rudloff** [comment]
I implemented proxies on the feature/proxy branch but the main remaining issue is that we can't be sure that proxies returned by proxy-lists are working

**Comment by Rudloff** [comment]
Closing this since there really isn't a simple solution here.
I might implement youtube-dl's `--geo-bypass-country` later though (but it only works on a small number of websites).
