### ISSUE TITLE
403 forbidden ： if edit  nginx.conf   add line "fastcgi_param     PATH_TRANSLATED $document_root$fastcgi_path_info;"

### ISSUE THREAD

**Issue by wenlanhuitai** [Rudloff/alltube#98]
I edit my nginx.conf like the example config  as much as possible，but when access index.php by browser, I got 403 forbidden error.
then I  delete the line ：**fastcgi_param     PATH_TRANSLATED $document_root$fastcgi_path_info;**     it can be access！ but when I copy the videoLink ，and press the button start to “*****.com/video?url=****”page  It appear 500 error again！
I has check two days  but has no ideo , who can help me ?  that`s why ？

**Comment by Rudloff** [comment]
Sorry I don't use Nginx so I can't really help you.
Also it would help if you could provide some logs.

**Comment by wenlanhuitai** [comment]
Thank you, I have resolved the problem  ：  cgi. fix_pathinfo (in PHP. Ini) was set to 1
