### ISSUE TITLE
Docker missing audio only download

### ISSUE THREAD

**Issue by next2non** [Rudloff/alltube#99]
Hi Rudloff

I installed the docker version of alltube on my synology and video is working fine, it only missing the audio (mp3) only button like on your website. Is it possible to update your docker to match the one on your website please!

Regards,
Tariq

**Comment by Rudloff** [comment]
I enabled audio conversion on the develop branch. Can you please try it? (`docker pull rudloff/alltube:develop`)

**Comment by next2non** [comment]
Yes it's there and working fine, thanks.

**Comment by shanmugam023** [comment]
Hi ,
I installed the alltube  video is working fine, it only missing the audio (mp3) only button like on your website how to enable audio button  i couldn't enable it  kindly share the configuration location  thank you so much

**Comment by Rudloff** [comment]
Please open a new ticket instead of reviving an old one like this.
As explained in the [FAQ](https://github.com/Rudloff/alltube/blob/master/FAQ.md#how-do-i-enable-audio-conversion), you need to add `convert: true` to your `config.yml` file.
